const styles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10000,
        padding: '20px',
    },
    modal: {
        backgroundColor: 'var(--bg-charcoal-deep)',
        borderRadius: '16px',
        width: '90%',
        maxWidth: '1200px',
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '0 20px 60px rgba(0, 0, 0, 0.5)',
        overflow: 'hidden',
    },
    header: {
        padding: '20px 24px',
        borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerLeft: {
        display: 'flex',
        alignItems: 'center',
    },
    title: {
        margin: 0,
        color: 'var(--color-white)',
        fontSize: '24px',
        fontWeight: 'bold',
    },
    closeButton: {
        background: 'none',
        border: 'none',
        color: 'var(--text-secondary)',
        fontSize: '24px',
        cursor: 'pointer',
        padding: '8px',
        transition: 'color 0.2s',
    },
    tabs: {
        display: 'flex',
        padding: '0 24px',
        borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
        gap: '8px',
    },
    tab: {
        background: 'none',
        border: 'none',
        color: 'var(--text-secondary)',
        padding: '12px 20px',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '600',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        borderBottom: '2px solid transparent',
        transition: 'all 0.2s',
    },
    activeTab: {
        color: 'var(--color-white)',
        borderBottomColor: 'var(--color-primary)',
    },
    content: {
        flex: 1,
        overflowY: 'auto',
        padding: '24px',
    },
    sectionTitle: {
        color: 'var(--color-white)',
        fontSize: '20px',
        marginBottom: '20px',
        fontWeight: 'bold',
    },
    plansGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
        gap: '20px',
    },
    planCard: {
        backgroundColor: 'var(--bg-void)',
        borderRadius: '12px',
        padding: '20px',
        border: '2px solid transparent',
        transition: 'all 0.3s',
        position: 'relative',
    },
    popularCard: {
        border: '2px solid var(--color-warning)',
        transform: 'scale(1.05)',
    },
    popularBadge: {
        position: 'absolute',
        top: '-12px',
        right: '20px',
        backgroundColor: 'var(--color-warning)',
        color: 'var(--color-black)',
        padding: '4px 12px',
        borderRadius: '12px',
        fontSize: '11px',
        fontWeight: 'bold',
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
    },
    planHeader: {
        borderBottom: '2px solid var(--color-primary)',
        paddingBottom: '16px',
        marginBottom: '16px',
    },
    planName: {
        color: 'var(--color-white)',
        fontSize: '18px',
        margin: '0 0 8px 0',
        fontWeight: 'bold',
    },
    planPrice: {
        display: 'flex',
        alignItems: 'baseline',
        gap: '4px',
    },
    price: {
        color: 'var(--color-white)',
        fontSize: '32px',
        fontWeight: 'bold',
    },
    currency: {
        color: 'var(--text-secondary)',
        fontSize: '14px',
    },
    featuresList: {
        marginBottom: '20px',
    },
    feature: {
        color: 'var(--text-primary)',
        fontSize: '14px',
        padding: '8px 0',
        borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
    },
    purchaseButton: {
        width: '100%',
        padding: '12px',
        borderRadius: '8px',
        border: 'none',
        color: 'var(--color-white)',
        fontWeight: 'bold',
        fontSize: '14px',
        cursor: 'pointer',
        marginBottom: '8px',
        transition: 'transform 0.2s',
    },
    yearlyButton: {
        width: '100%',
        padding: '10px',
        borderRadius: '8px',
        border: '1px solid var(--color-primary)',
        backgroundColor: 'transparent',
        color: 'var(--color-primary)',
        fontWeight: '600',
        fontSize: '12px',
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    currentPlanButton: {
        width: '100%',
        padding: '12px',
        borderRadius: '8px',
        border: '1px solid var(--text-disabled)',
        backgroundColor: 'transparent',
        color: 'var(--text-disabled)',
        fontWeight: 'bold',
        fontSize: '14px',
        cursor: 'not-allowed',
    },
    storeGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
        gap: '16px',
    },
    storeItem: {
        backgroundColor: 'var(--bg-void)',
        borderRadius: '12px',
        padding: '20px',
        textAlign: 'center',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        transition: 'all 0.3s',
    },
    itemIcon: {
        fontSize: '48px',
        marginBottom: '12px',
    },
    itemName: {
        color: 'var(--color-white)',
        fontSize: '16px',
        margin: '0 0 8px 0',
        fontWeight: 'bold',
    },
    itemDescription: {
        color: 'var(--text-secondary)',
        fontSize: '13px',
        margin: '0 0 12px 0',
    },
    itemPrice: {
        color: 'var(--color-warning)',
        fontSize: '20px',
        fontWeight: 'bold',
        marginBottom: '12px',
    },
    buyButton: {
        width: '100%',
        padding: '10px',
        borderRadius: '8px',
        border: 'none',
        backgroundColor: 'var(--color-primary)',
        color: 'var(--color-white)',
        fontWeight: 'bold',
        fontSize: '14px',
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    boostDescription: {
        color: 'var(--text-secondary)',
        fontSize: '14px',
        marginBottom: '24px',
    },
    boostTiers: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
        gap: '16px',
        marginBottom: '24px',
    },
    boostTier: {
        backgroundColor: 'var(--bg-void)',
        borderRadius: '12px',
        padding: '20px',
        border: '1px solid rgba(255, 255, 255, 0.1)',
    },
    boostButton: {
        width: '100%',
        maxWidth: '400px',
        padding: '16px',
        borderRadius: '8px',
        border: 'none',
        backgroundColor: 'var(--color-warning)',
        color: 'var(--color-black)',
        fontWeight: 'bold',
        fontSize: '16px',
        cursor: 'pointer',
        display: 'block',
        margin: '0 auto',
    },
    boostTab: {
        padding: '10px 0',
    },
    boostHeader: {
        textAlign: 'center',
        marginBottom: '30px',
    },
    boostTitle: {
        color: 'var(--color-white)',
        fontSize: '28px',
        fontWeight: '700',
        margin: '0 0 10px 0',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '10px',
    },
    boostIcon: {
        fontSize: '32px',
    },
    boostSubtitle: {
        color: 'var(--text-secondary)',
        fontSize: '15px',
        margin: 0,
    },
    boostTiersContainer: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: '20px',
        marginBottom: '30px',
    },
    boostTierCard: {
        background: 'linear-gradient(145deg, var(--bg-charcoal-deep), var(--bg-void))',
        borderRadius: '16px',
        padding: '25px 20px',
        border: '2px solid',
        position: 'relative',
        transition: 'all 0.3s ease',
        textAlign: 'center',
    },
    tierBadge: {
        width: '60px',
        height: '60px',
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        margin: '0 auto 15px auto',
        boxShadow: '0 4px 15px rgba(0, 0, 0, 0.3)',
    },
    tierNumber: {
        color: 'var(--color-white)',
        fontSize: '28px',
        fontWeight: 'bold',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
    },
    tierTitle: {
        color: 'var(--color-white)',
        fontSize: '20px',
        fontWeight: '700',
        margin: '0 0 5px 0',
    },
    tierRequirement: {
        color: 'var(--text-muted)',
        fontSize: '13px',
        margin: '0 0 15px 0',
    },
    tierFeatureList: {
        listStyle: 'none',
        padding: 0,
        margin: 0,
        textAlign: 'left',
    },
    tierFeature: {
        color: 'var(--text-primary)',
        fontSize: '13px',
        padding: '6px 0',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
    },
    featureIcon: {
        fontSize: '14px',
    },
    popularBadgeAlt: {
        position: 'absolute',
        top: '-12px',
        left: '50%',
        transform: 'translateX(-50%)',
        background: 'linear-gradient(135deg, var(--color-primary), #7c8af2)',
        color: 'var(--color-white)',
        fontSize: '11px',
        fontWeight: 'bold',
        padding: '4px 14px',
        borderRadius: '12px',
        boxShadow: '0 2px 10px rgba(88, 101, 242, 0.4)',
    },
    premiumBadge: {
        position: 'absolute',
        top: '-12px',
        left: '50%',
        transform: 'translateX(-50%)',
        background: 'linear-gradient(135deg, #ffd700, #ff8c00)',
        color: 'var(--color-black)',
        fontSize: '11px',
        fontWeight: 'bold',
        padding: '4px 14px',
        borderRadius: '12px',
        boxShadow: '0 2px 10px rgba(255, 215, 0, 0.4)',
    },
    boostPurchaseButton: {
        width: '100%',
        maxWidth: '350px',
        padding: '16px 24px',
        borderRadius: '12px',
        border: 'none',
        background: 'linear-gradient(135deg, #ff6b9d, var(--color-warning), #ffd700)',
        color: 'var(--color-black)',
        fontWeight: 'bold',
        fontSize: '16px',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '10px',
        margin: '0 auto',
        boxShadow: '0 4px 20px rgba(240, 178, 50, 0.4)',
        transition: 'all 0.3s ease',
    },
    boostButtonIcon: {
        fontSize: '20px',
    },
};

export default styles;
