// Helper to convert hex color to rgba hover background
const hexToRgba = (hex, alpha) => {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return `rgba(${r},${g},${b},${alpha})`;
};

export const getHoverBg = (color) => hexToRgba(color, 0.2);

export const FEATURE_SECTIONS = [
    {
        title: '⚙️ General Settings',
        titleKey: 'featureHub.generalSettings',
        color: '#5865f2',
        items: [
            {
                icon: '⚙️',
                label: 'User Settings',
                labelKey: 'featureHub.userSettings',
                modal: 'userSettings',
            },
            {
                icon: '⌨️',
                label: 'Keyboard Shortcuts',
                labelKey: 'featureHub.keyboardShortcuts',
                modal: 'keyboardShortcuts',
            },
            {
                icon: '🔍',
                label: 'Command Palette',
                labelKey: 'featureHub.commandPalette',
                modal: 'commandPalette',
            },
            {
                icon: '🌍',
                label: 'Discover Servers',
                labelKey: 'featureHub.discoverServers',
                modal: 'serverDiscovery',
            },
            {
                icon: '🎨',
                label: 'Appearance',
                labelKey: 'featureHub.appearance',
                modal: 'appearanceSettings',
            },
            {
                icon: '🌐',
                label: 'Language Selection',
                labelKey: 'featureHub.languageSelection',
                modal: 'languageSelector',
            },
            {
                icon: '📋',
                label: 'Changelog',
                labelKey: 'featureHub.changelog',
                modal: 'changelog',
            },
            {
                icon: '🔊',
                label: 'Notification Sounds',
                labelKey: 'featureHub.notificationSounds',
                modal: 'notificationSounds',
            },
            {
                icon: '⚡',
                label: 'Quick Switcher',
                labelKey: 'featureHub.quickSwitcher',
                modal: 'quickSwitcher',
            },
            { icon: '🚪', label: 'Logout', labelKey: 'featureHub.logout', modal: 'logoutConfirm' },
        ],
    },
    {
        title: '🔐 Security & Privacy',
        titleKey: 'featureHub.securityPrivacy',
        color: '#f23f42',
        items: [
            {
                icon: '🔐',
                label: 'Login History',
                labelKey: 'featureHub.loginHistory',
                modal: 'loginHistory',
            },
            {
                icon: '🛡️',
                label: 'Security Settings',
                labelKey: 'featureHub.securitySettings',
                modal: 'securitySettings',
            },
            {
                icon: '🔒',
                label: 'Privacy Settings',
                labelKey: 'featureHub.privacySettings',
                modal: 'privacySettings',
            },
            {
                icon: '🚫',
                label: 'Block List',
                labelKey: 'featureHub.blockList',
                modal: 'blockList',
            },
            {
                icon: '🔐',
                label: 'E2E Encryption',
                labelKey: 'featureHub.e2eEncryption',
                modal: 'e2EESettings',
            },
            {
                icon: '❌',
                label: 'Account Deletion',
                labelKey: 'featureHub.accountDeletion',
                modal: 'accountDeletion',
            },
        ],
    },
    {
        title: '💬 Communication',
        titleKey: 'featureHub.communication',
        color: '#3ba55d',
        items: [
            {
                icon: '💬',
                label: 'Message Threads',
                labelKey: 'featureHub.messageThreads',
                modal: 'threadView',
            },
            {
                icon: '⏰',
                label: 'Scheduled Messages',
                labelKey: 'featureHub.scheduledMessages',
                modal: 'scheduledMessages',
            },
            {
                icon: '⏰',
                label: 'Reminders',
                labelKey: 'featureHub.reminders',
                modal: 'reminders',
            },
            { icon: '📋', label: 'Forum', labelKey: 'featureHub.forum', modal: 'forum' },
            {
                icon: '🎤',
                label: 'Stage Channel',
                labelKey: 'featureHub.stageChannel',
                modal: 'stageChannel',
            },
            {
                icon: '📹',
                label: 'Video Call',
                labelKey: 'featureHub.videoCall',
                modal: 'videoCall',
            },
            {
                icon: '🎙️',
                label: 'Voice Settings',
                labelKey: 'featureHub.voiceSettings',
                modal: 'voiceSettings',
            },
            {
                icon: '🔍',
                label: 'Message Search',
                labelKey: 'featureHub.messageSearch',
                modal: 'messageSearch',
            },
            {
                icon: '🎬',
                label: 'Watch Together',
                labelKey: 'featureHub.watchTogether',
                modal: 'watchTogether',
            },
        ],
    },
    {
        title: '🏠 Server Management',
        titleKey: 'featureHub.serverManagement',
        color: '#f0b232',
        items: [
            {
                icon: '🤖',
                label: 'Auto Roles',
                labelKey: 'featureHub.autoRoles',
                modal: 'autoRoles',
            },
            {
                icon: '🎭',
                label: 'Reaction Roles',
                labelKey: 'featureHub.reactionRoles',
                modal: 'reactionRoles',
            },
            {
                icon: '👋',
                label: 'Welcome Messages',
                labelKey: 'featureHub.welcomeMessages',
                modal: 'welcomeMessages',
            },
            {
                icon: '📅',
                label: 'Event Calendar',
                labelKey: 'featureHub.eventCalendar',
                modal: 'eventCalendar',
            },
            { icon: '🎉', label: 'Giveaway', labelKey: 'featureHub.giveaway', modal: 'giveaway' },
            {
                icon: '🎫',
                label: 'Ticket System',
                labelKey: 'featureHub.ticketSystem',
                modal: 'ticketSystem',
            },
            {
                icon: '⭐',
                label: 'Starboard',
                labelKey: 'featureHub.starboard',
                modal: 'starboard',
            },
            {
                icon: '💾',
                label: 'Server Backup',
                labelKey: 'featureHub.serverBackup',
                modal: 'serverBackup',
            },
            {
                icon: '⚖️',
                label: 'Ban Appeals',
                labelKey: 'featureHub.banAppeals',
                modal: 'banAppeals',
            },
            {
                icon: '🤖',
                label: 'Custom Commands',
                labelKey: 'featureHub.customCommands',
                modal: 'customCommands',
            },
            {
                icon: '📊',
                label: 'Level System',
                labelKey: 'featureHub.levelSystem',
                modal: 'levelingSystem',
            },
            {
                icon: '📺',
                label: 'Live Stream',
                labelKey: 'featureHub.liveStream',
                modal: 'liveStream',
            },
        ],
    },
    {
        title: '🎮 Entertainment & Social',
        titleKey: 'featureHub.entertainmentSocial',
        color: '#5865f2',
        items: [
            {
                icon: '🏆',
                label: 'Achievements',
                labelKey: 'featureHub.achievements',
                modal: 'achievements',
            },
            {
                icon: '🎂',
                label: 'Birthdays',
                labelKey: 'featureHub.birthdays',
                modal: 'birthdaySystem',
            },
            { icon: '💎', label: 'Premium', labelKey: 'featureHub.premium', modal: 'premium' },
            {
                icon: '🎵',
                label: 'Music Player',
                labelKey: 'featureHub.musicPlayer',
                modal: 'musicPlayer',
            },
            {
                icon: '🤖',
                label: 'Bot Marketplace',
                labelKey: 'featureHub.botMarketplace',
                modal: 'botMarketplace',
            },
            {
                icon: '👤',
                label: 'Customize Profile',
                labelKey: 'featureHub.customizeProfile',
                modal: 'profileCustomization',
            },
            {
                icon: '🔗',
                label: 'Integrations',
                labelKey: 'featureHub.integrations',
                modal: 'integrationHub',
            },
            {
                icon: '🏆',
                label: 'Tournaments',
                labelKey: 'featureHub.tournaments',
                modal: 'tournaments',
            },
        ],
    },
    {
        title: '🔧 Advanced',
        titleKey: 'featureHub.advanced',
        color: '#e67e22',
        items: [
            {
                icon: '💡',
                label: 'Highlights',
                labelKey: 'featureHub.highlights',
                modal: 'highlights',
            },
            {
                icon: '📦',
                label: 'Custom Embed',
                labelKey: 'featureHub.customEmbed',
                modal: 'customEmbed',
            },
            {
                icon: '🎵',
                label: 'Spotify Connection',
                labelKey: 'featureHub.spotifyConnection',
                modal: 'spotifyIntegration',
            },
            {
                icon: '📋',
                label: 'Clone Server',
                labelKey: 'featureHub.cloneServer',
                modal: 'serverClone',
            },
            {
                icon: '🎯',
                label: 'Weekly Challenges',
                labelKey: 'featureHub.weeklyChallenges',
                modal: 'weeklyChallenges',
            },
            {
                icon: '🤖',
                label: 'AI Chatbot',
                labelKey: 'featureHub.aiChatbot',
                modal: 'aIChatbot',
            },
            {
                icon: '👨‍💻',
                label: 'Code Editor',
                labelKey: 'featureHub.codeEditor',
                modal: 'codeEditor',
            },
            {
                icon: '🖥️',
                label: 'Screen Share',
                labelKey: 'featureHub.screenShare',
                modal: 'screenShare',
            },
            {
                icon: '📺',
                label: 'Live Stream',
                labelKey: 'featureHub.liveStreamModal',
                modal: 'liveStreamModal',
            },
            {
                icon: '📈',
                label: 'Advanced Analytics',
                labelKey: 'featureHub.advancedAnalytics',
                modal: 'advancedAnalytics',
            },
            {
                icon: '📁',
                label: 'File Manager',
                labelKey: 'featureHub.fileManager',
                modal: 'fileManager',
            },
            { icon: '📊', label: 'Reports', labelKey: 'featureHub.reports', modal: 'reports' },
            {
                icon: '🐛',
                label: 'Error Reporting',
                labelKey: 'featureHub.errorReporting',
                modal: 'errorReporting',
            },
        ],
    },
    {
        title: '🔰 Moderation & Management',
        titleKey: 'featureHub.moderationManagement',
        color: '#e74c3c',
        items: [
            {
                icon: '🛡️',
                label: 'Moderation Tools',
                labelKey: 'featureHub.moderationTools',
                modal: 'moderatorTools',
            },
            {
                icon: '🤖',
                label: 'AI Moderation',
                labelKey: 'featureHub.aiModeration',
                modal: 'aIModeration',
            },
            {
                icon: '🚫',
                label: 'Spam Protection',
                labelKey: 'featureHub.spamProtection',
                modal: 'spamDetection',
            },
            {
                icon: '📋',
                label: 'Audit Logs',
                labelKey: 'featureHub.auditLogs',
                modal: 'auditLogs',
            },
            {
                icon: '⛔',
                label: 'Ban History',
                labelKey: 'featureHub.banHistory',
                modal: 'banHistory',
            },
            {
                icon: '📜',
                label: 'Moderation Logs',
                labelKey: 'featureHub.moderationLogs',
                modal: 'moderationLogs',
            },
            {
                icon: '🛡️',
                label: 'Raid Protection',
                labelKey: 'featureHub.raidProtection',
                modal: 'raidProtection',
            },
            {
                icon: '🚨',
                label: 'Security Alerts',
                labelKey: 'featureHub.securityAlerts',
                modal: 'securityAlerts',
            },
        ],
    },
    {
        title: '💬 Messaging & Media',
        titleKey: 'featureHub.messagingMedia',
        color: '#1abc9c',
        items: [
            {
                icon: '🔖',
                label: 'Bookmarks',
                labelKey: 'featureHub.bookmarks',
                modal: 'bookmarks',
            },
            {
                icon: '🎞️',
                label: 'GIF Picker',
                labelKey: 'featureHub.gifPicker',
                modal: 'gIFPicker',
            },
            {
                icon: '📊',
                label: 'Poll Create',
                labelKey: 'featureHub.pollCreate',
                modal: 'pollCreator',
            },
            { icon: '🎨', label: 'Stickers', labelKey: 'featureHub.stickers', modal: 'stickers' },
            {
                icon: '💾',
                label: 'Saved Messages',
                labelKey: 'featureHub.savedMessages',
                modal: 'savedMessages',
            },
            {
                icon: '🔔',
                label: 'Notifications Center',
                labelKey: 'featureHub.notificationsCenter',
                modal: 'notificationsCenter',
            },
            {
                icon: '📝',
                label: 'Message Summary',
                labelKey: 'featureHub.messageSummary',
                modal: 'messageSummary',
            },
            {
                icon: '🌍',
                label: 'Translation Panel',
                labelKey: 'featureHub.translationPanel',
                modal: 'translation',
            },
        ],
    },
    {
        title: '🏠 Extended Server Management',
        titleKey: 'featureHub.extendedServerManagement',
        color: '#2ecc71',
        items: [
            {
                icon: '⚙️',
                label: 'Channel Settings',
                labelKey: 'featureHub.channelSettings',
                modal: 'channelSettings',
            },
            {
                icon: '📨',
                label: 'Invite Management',
                labelKey: 'featureHub.inviteManagement',
                modal: 'inviteModal',
            },
            {
                icon: '📋',
                label: 'Server Templates',
                labelKey: 'featureHub.serverTemplates',
                modal: 'serverTemplates',
            },
            {
                icon: '📊',
                label: 'Server Analytics',
                labelKey: 'featureHub.serverAnalytics',
                modal: 'serverAnalytics',
            },
            {
                icon: '👑',
                label: 'Roles Manager',
                labelKey: 'featureHub.rolesManager',
                modal: 'rolesManager',
            },
            {
                icon: '👋',
                label: 'Welcome Screen',
                labelKey: 'featureHub.welcomeScreen',
                modal: 'welcomeScreenEditor',
            },
            {
                icon: '🏘️',
                label: 'Community Settings',
                labelKey: 'featureHub.communitySettings',
                modal: 'communitySettings',
            },
            {
                icon: '🔗',
                label: 'Invite Links',
                labelKey: 'featureHub.inviteLinks',
                modal: 'inviteLinkManager',
            },
        ],
    },
    {
        title: '🤖 Bot & Developer',
        titleKey: 'featureHub.botDeveloper',
        color: '#3498db',
        items: [
            {
                icon: '🤖',
                label: 'Bot Builder',
                labelKey: 'featureHub.botBuilder',
                modal: 'botBuilder',
            },
            {
                icon: '🧑‍💻',
                label: 'Developer Portal',
                labelKey: 'featureHub.developerPortal',
                modal: 'botDevPortal',
            },
            {
                icon: '🔗',
                label: 'Webhook Manager',
                labelKey: 'featureHub.webhookManager',
                modal: 'webhookManager',
            },
            { icon: '🔑', label: 'API Keys', labelKey: 'featureHub.apiKeys', modal: 'aPIKeys' },
            {
                icon: '⚡',
                label: 'Slash Commands',
                labelKey: 'featureHub.slashCommands',
                modal: 'slashCommands',
            },
            {
                icon: '💻',
                label: 'Code Runner',
                labelKey: 'featureHub.codeRunner',
                modal: 'codeRunner',
            },
        ],
    },
    {
        title: '👤 Profile & Social',
        titleKey: 'featureHub.profileSocial',
        color: '#e91e63',
        items: [
            {
                icon: '👤',
                label: 'Profile Card',
                labelKey: 'featureHub.profileCard',
                modal: 'profileCard',
            },
            {
                icon: '📝',
                label: 'User Notes',
                labelKey: 'featureHub.userNotes',
                modal: 'userNotes',
            },
            {
                icon: '🟢',
                label: 'Status Picker',
                labelKey: 'featureHub.statusPicker',
                modal: 'statusPicker',
            },
            {
                icon: '👥',
                label: 'Mutual Friends',
                labelKey: 'featureHub.mutualFriends',
                modal: 'mutuals',
            },
            {
                icon: '🏅',
                label: 'Profile Showcase',
                labelKey: 'featureHub.profileShowcase',
                modal: 'profileShowcase',
            },
            {
                icon: '📱',
                label: 'Session Manager',
                labelKey: 'featureHub.sessionManager',
                modal: 'sessionManager',
            },
        ],
    },
    {
        title: '💎 Premium & Economy',
        titleKey: 'featureHub.premiumEconomy',
        color: '#f1c40f',
        items: [
            {
                icon: '🪙',
                label: 'Coin Store',
                labelKey: 'featureHub.coinStore',
                modal: 'coinStore',
            },
            {
                icon: '💎',
                label: 'Premium Management',
                labelKey: 'featureHub.premiumManagement',
                modal: 'premiumManagement',
            },
            {
                icon: '📋',
                label: 'Subscription Manager',
                labelKey: 'featureHub.subscriptionManager',
                modal: 'subscriptionManager',
            },
            {
                icon: '🎁',
                label: 'Gift Premium',
                labelKey: 'featureHub.giftPremium',
                modal: 'giftPremium',
            },
            {
                icon: '🛒',
                label: 'Premium Store',
                labelKey: 'featureHub.premiumStore',
                modal: 'premiumMarketplace',
            },
            {
                icon: '🎨',
                label: 'Theme Marketplace',
                labelKey: 'featureHub.themeMarketplace',
                modal: 'themeMarketplace',
            },
        ],
    },
];
