// frontend/src/components/EmojiPicker.js
import React, { useState, useEffect, useCallback } from 'react';
import PropTypes from 'prop-types';
import { useTranslation } from 'react-i18next';
import styles from '../EmojiPicker/styles';
import { API_BASE_URL } from '../../utils/apiEndpoints';

// -- dynamic style helpers (pass 2) --

const S = {
    el: {
        ...styles.categoryButton,
    },
    txt: { fontSize: '11px', color: '#949ba4', marginRight: 2, userSelect: 'none' },
    flex: {
        display: 'flex',
        gap: 5,
        padding: '4px 12px 6px',
        alignItems: 'center',
        borderBottom: '1px solid #0b0e1b',
    },
};

// ─── localStorage helpers for Recents & Favorites ───

const RECENTS_KEY = 'pawscord_recent_emojis';
const FAVS_KEY = 'pawscord_favorite_emojis';
const SKIN_TONE_KEY = 'pawscord_skin_tone';
const MAX_RECENTS = 24;

// ─── Skin tone modifiers ───
const SKIN_TONES = ['', '\u{1F3FB}', '\u{1F3FC}', '\u{1F3FD}', '\u{1F3FE}', '\u{1F3FF}'];
const SKIN_TONE_COLORS = ['#ffd83d', '#ffe0b3', '#f5c47e', '#cc9141', '#8d5524', '#4a2912'];
const SKIN_TONE_LABELS_KEYS = ['default', 'light', 'mediumLight', 'medium', 'mediumDark', 'dark'];
// Emojis that support skin tone modifiers (hand gestures + person)
const SKIN_TONE_EMOJIS = new Set([
    '👋',
    '🤚',
    '🖐️',
    '✋',
    '🖖',
    '👌',
    '🤌',
    '🤏',
    '✌️',
    '🤞',
    '🤟',
    '🤘',
    '🤙',
    '👈',
    '👉',
    '👆',
    '🖕',
    '👇',
    '☝️',
    '👍',
    '👎',
    '✊',
    '👊',
    '🤛',
    '🤜',
    '👏',
    '🙌',
    '👐',
    '🤲',
    '🤝',
    '🙏',
    '✍️',
    '💅',
    '🤳',
    '💪',
    '🫵',
    '🫶',
    '🫱',
    '🫲',
]);
const getSkinTone = () => {
    try {
        return localStorage.getItem(SKIN_TONE_KEY) || '';
    } catch {
        return '';
    }
};
const saveSkinTone = (t) => {
    try {
        localStorage.setItem(SKIN_TONE_KEY, t);
    } catch {}
};

const getRecents = () => {
    try {
        return JSON.parse(localStorage.getItem(RECENTS_KEY)) || [];
    } catch {
        return [];
    }
};
const addRecent = (emoji) => {
    const arr = getRecents().filter((e) => e !== emoji);
    arr.unshift(emoji);
    localStorage.setItem(RECENTS_KEY, JSON.stringify(arr.slice(0, MAX_RECENTS)));
};
const getFavorites = () => {
    try {
        return JSON.parse(localStorage.getItem(FAVS_KEY)) || [];
    } catch {
        return [];
    }
};
const toggleFavorite = (emoji) => {
    const arr = getFavorites();
    const idx = arr.indexOf(emoji);
    if (idx >= 0) arr.splice(idx, 1);
    else arr.push(emoji);
    localStorage.setItem(FAVS_KEY, JSON.stringify(arr));
    return [...arr];
};

const EMOJI_CATEGORIES = {
    'Trending 🔥': [], // 🆕 Will be populated from API
    Faces: [
        '😀',
        '😃',
        '😄',
        '😁',
        '😆',
        '😅',
        '🤣',
        '😂',
        '🙂',
        '🙃',
        '😉',
        '😊',
        '😇',
        '🥰',
        '😍',
        '🤩',
        '😘',
        '😗',
        '😚',
        '😙',
        '🥲',
        '😋',
        '😛',
        '😜',
        '🤪',
        '😝',
        '🤑',
        '🤗',
        '🤭',
        '🤫',
        '🤔',
        '🤐',
        '🤨',
        '😐',
        '😑',
        '😶',
        '😏',
        '😒',
        '🙄',
        '😬',
        '🤥',
        '😌',
        '😔',
        '😪',
        '🤤',
        '😴',
        '😷',
        '🤒',
        '🤕',
        '🤢',
        '🤮',
        '🤧',
        '🥵',
        '🥶',
        '😶‍🌫️',
        '🥴',
        '😵',
        '🤯',
        '🤠',
        '🥳',
        '🥸',
        '😎',
        '🤓',
        '🧐',
    ],
    Kalpler: [
        '❤️',
        '🧡',
        '💛',
        '💚',
        '💙',
        '💜',
        '🖤',
        '🤍',
        '🤎',
        '💔',
        '❣️',
        '💕',
        '💞',
        '💓',
        '💗',
        '💖',
        '💘',
        '💝',
        '💟',
    ],
    'El İşaretleri': [
        '👋',
        '🤚',
        '🖐️',
        '✋',
        '🖖',
        '👌',
        '🤌',
        '🤏',
        '✌️',
        '🤞',
        '🤟',
        '🤘',
        '🤙',
        '👈',
        '👉',
        '👆',
        '🖕',
        '👇',
        '☝️',
        '👍',
        '👎',
        '✊',
        '👊',
        '🤛',
        '🤜',
        '👏',
        '🙌',
        '👐',
        '🤲',
        '🤝',
        '🙏',
    ],
    Hayvanlar: [
        '🐶',
        '🐱',
        '🐭',
        '🐹',
        '🐰',
        '🦊',
        '🐻',
        '🐼',
        '🐨',
        '🐯',
        '🦁',
        '🐮',
        '🐷',
        '🐸',
        '🐵',
        '🐔',
        '🐧',
        '🐦',
        '🐤',
        '🦆',
        '🦅',
        '🦉',
        '🦇',
        '🐺',
        '🐗',
        '🐴',
        '🦄',
        '🐝',
        '🐛',
        '🦋',
        '🐌',
        '🐞',
        '🐜',
        '🦟',
        '🦗',
        '🕷️',
        '🦂',
        '🐢',
        '🐍',
        '🦎',
        '🦖',
        '🦕',
        '🐙',
        '🦑',
        '🦐',
        '🦀',
        '🐡',
        '🐠',
        '🐟',
        '🐬',
        '🐳',
        '🐋',
        '🦈',
        '🐊',
        '🐅',
        '🐆',
        '🦓',
        '🦍',
        '🦧',
        '🐘',
        '🦛',
        '🦏',
        '🐪',
        '🐫',
        '🦒',
        '🦘',
        '🐃',
        '🐂',
        '🐄',
        '🐎',
        '🐖',
        '🐏',
        '🐑',
        '🦙',
        '🐐',
        '🦌',
        '🐕',
        '🐩',
        '🦮',
        '🐕‍🦺',
        '🐈',
        '🐈‍⬛',
        '🐓',
        '🦃',
        '🦚',
        '🦜',
        '🦢',
        '🦩',
        '🕊️',
        '🐇',
        '🦝',
        '🦨',
        '🦡',
        '🦦',
        '🦥',
        '🐁',
        '🐀',
        '🐿️',
        '🦔',
    ],
    Yiyecek: [
        '🍏',
        '🍎',
        '🍐',
        '🍊',
        '🍋',
        '🍌',
        '🍉',
        '🍇',
        '🍓',
        '🫐',
        '🍈',
        '🍒',
        '🍑',
        '🥭',
        '🍍',
        '🥥',
        '🥝',
        '🍅',
        '🍆',
        '🥑',
        '🥦',
        '🥬',
        '🥒',
        '🌶️',
        '🫑',
        '🌽',
        '🥕',
        '🫒',
        '🧄',
        '🧅',
        '🥔',
        '🍠',
        '🥐',
        '🥯',
        '🍞',
        '🥖',
        '🥨',
        '🧀',
        '🥚',
        '🍳',
        '🧈',
        '🥞',
        '🧇',
        '🥓',
        '🥩',
        '🍗',
        '🍖',
        '🌭',
        '🍔',
        '🍟',
        '🍕',
        '🫓',
        '🥪',
        '🥙',
        '🧆',
        '🌮',
        '🌯',
        '🫔',
        '🥗',
        '🥘',
        '🫕',
        '🥫',
        '🍝',
        '🍜',
        '🍲',
        '🍛',
        '🍣',
        '🍱',
        '🥟',
        '🦪',
        '🍤',
        '🍙',
        '🍚',
        '🍘',
        '🍥',
        '🥠',
        '🥮',
        '🍢',
        '🍡',
        '🍧',
        '🍨',
        '🍦',
        '🥧',
        '🧁',
        '🍰',
        '🎂',
        '🍮',
        '🍭',
        '🍬',
        '🍫',
        '🍿',
        '🍩',
        '🍪',
        '🌰',
        '🥜',
        '🍯',
        '🥛',
        '🍼',
        '🫖',
        '☕',
        '🍵',
        '🧃',
        '🥤',
        '🧋',
        '🍶',
        '🍺',
        '🍻',
        '🥂',
        '🍷',
        '🥃',
        '🍸',
        '🍹',
        '🧉',
        '🍾',
        '🧊',
        '🥄',
        '🍴',
        '🍽️',
        '🥣',
        '🥡',
        '🥢',
        '🧂',
    ],
    Aktiviteler: [
        '⚽',
        '🏀',
        '🏈',
        '⚾',
        '🥎',
        '🎾',
        '🏐',
        '🏉',
        '🥏',
        '🎱',
        '🪀',
        '🏓',
        '🏸',
        '🏒',
        '🏑',
        '🥍',
        '🏏',
        '🪃',
        '🥅',
        '⛳',
        '🪁',
        '🏹',
        '🎣',
        '🤿',
        '🥊',
        '🥋',
        '🎽',
        '🛹',
        '🛼',
        '🛷',
        '⛸️',
        '🥌',
        '🎿',
        '⛷️',
        '🏂',
        '🪂',
        '🏋️',
        '🤼',
        '🤸',
        '🤺',
        '⛹️',
        '🤾',
        '🏌️',
        '🏇',
        '🧘',
        '🏊',
        '🏄',
        '🚣',
        '🧗',
        '🚵',
        '🚴',
        '🏆',
        '🥇',
        '🥈',
        '🥉',
        '🏅',
        '🎖️',
        '🏵️',
        '🎗️',
        '🎫',
        '🎟️',
        '🎪',
        '🤹',
        '🎭',
        '🩰',
        '🎨',
        '🎬',
        '🎤',
        '🎧',
        '🎼',
        '🎹',
        '🥁',
        '🪘',
        '🎷',
        '🎺',
        '🪗',
        '🎸',
        '🪕',
        '🎻',
        '🎲',
        '♟️',
        '🎯',
        '🎳',
        '🎮',
        '🎰',
        '🧩',
    ],
    Seyahat: [
        '🚗',
        '🚕',
        '🚙',
        '🚌',
        '🚎',
        '🏎️',
        '🚓',
        '🚑',
        '🚒',
        '🚐',
        '🛻',
        '🚚',
        '🚛',
        '🚜',
        '🦯',
        '🦽',
        '🦼',
        '🛴',
        '🚲',
        '🛵',
        '🏍️',
        '🛺',
        '🚨',
        '🚔',
        '🚍',
        '🚘',
        '🚖',
        '🚡',
        '🚠',
        '🚟',
        '🚃',
        '🚋',
        '🚞',
        '🚝',
        '🚄',
        '🚅',
        '🚈',
        '🚂',
        '🚆',
        '🚇',
        '🚊',
        '🚉',
        '✈️',
        '🛫',
        '🛬',
        '🛩️',
        '💺',
        '🛰️',
        '🚀',
        '🛸',
        '🚁',
        '🛶',
        '⛵',
        '🚤',
        '🛥️',
        '🛳️',
        '⛴️',
        '🚢',
        '⚓',
        '⛽',
        '🚧',
        '🚦',
        '🚥',
        '🚏',
        '🗺️',
        '🗿',
        '🗽',
        '🗼',
        '🏰',
        '🏯',
        '🏟️',
        '🎡',
        '🎢',
        '🎠',
        '⛲',
        '⛱️',
        '🏖️',
        '🏝️',
        '🏜️',
        '🌋',
        '⛰️',
        '🏔️',
        '🗻',
        '🏕️',
        '⛺',
        '🛖',
        '🏠',
        '🏡',
        '🏘️',
        '🏚️',
        '🏗️',
        '🏭',
        '🏢',
        '🏬',
        '🏣',
        '🏤',
        '🏥',
        '🏦',
        '🏨',
        '🏪',
        '🏫',
        '🏩',
        '💒',
        '🏛️',
        '⛪',
        '🕌',
        '🕍',
        '🛕',
        '🕋',
    ],
    Objeler: [
        '⌚',
        '📱',
        '📲',
        '💻',
        '⌨️',
        '🖥️',
        '🖨️',
        '🖱️',
        '🖲️',
        '🕹️',
        '🗜️',
        '💾',
        '💿',
        '📀',
        '📼',
        '📷',
        '📸',
        '📹',
        '🎥',
        '📽️',
        '🎞️',
        '📞',
        '☎️',
        '📟',
        '📠',
        '📺',
        '📻',
        '🎙️',
        '🎚️',
        '🎛️',
        '🧭',
        '⏱️',
        '⏲️',
        '⏰',
        '🕰️',
        '⌛',
        '⏳',
        '📡',
        '🔋',
        '🔌',
        '💡',
        '🔦',
        '🕯️',
        '🪔',
        '🧯',
        '🛢️',
        '💸',
        '💵',
        '💴',
        '💶',
        '💷',
        '🪙',
        '💰',
        '💳',
        '💎',
        '⚖️',
        '🪜',
        '🧰',
        '🪛',
        '🔧',
        '🔨',
        '⚒️',
        '🛠️',
        '⛏️',
        '🪚',
        '🔩',
        '⚙️',
        '🪤',
        '🧱',
        '⛓️',
        '🧲',
        '🔫',
        '💣',
        '🧨',
        '🪓',
        '🔪',
        '🗡️',
        '⚔️',
        '🛡️',
        '🚬',
        '⚰️',
        '🪦',
        '⚱️',
        '🏺',
        '🔮',
        '📿',
        '🧿',
        '💈',
        '⚗️',
        '🔭',
        '🔬',
        '🕳️',
        '🩹',
        '🩺',
        '💊',
        '💉',
        '🩸',
        '🧬',
        '🦠',
        '🧫',
        '🧪',
        '🌡️',
        '🧹',
        '🪠',
        '🧺',
        '🧻',
        '🚽',
        '🚰',
        '🚿',
        '🛁',
        '🛀',
        '🧼',
        '🪒',
        '🧽',
        '🪣',
        '🧴',
        '🛎️',
        '🔑',
        '🗝️',
        '🚪',
        '🪑',
        '🛋️',
        '🛏️',
        '🛌',
        '🧸',
        '🪆',
        '🖼️',
        '🪞',
        '🪟',
        '🛍️',
        '🛒',
        '🎁',
        '🎈',
        '🎏',
        '🎀',
        '🪄',
        '🪅',
        '🎊',
        '🎉',
        '🎎',
        '🏮',
        '🎐',
        '🧧',
        '✉️',
        '📩',
        '📨',
        '📧',
        '💌',
        '📥',
        '📤',
        '📦',
        '🏷️',
        '🪧',
        '📪',
        '📫',
        '📬',
        '📭',
        '📮',
        '📯',
        '📜',
        '📃',
        '📄',
        '📑',
        '🧾',
        '📊',
        '📈',
        '📉',
        '🗒️',
        '🗓️',
        '📆',
        '📅',
        '🗑️',
        '📇',
        '🗃️',
        '🗳️',
        '🗄️',
        '📋',
        '📁',
        '📂',
        '🗂️',
        '🗞️',
        '📰',
        '📓',
        '📔',
        '📒',
        '📕',
        '📗',
        '📘',
        '📙',
        '📚',
        '📖',
        '🔖',
        '🧷',
        '🔗',
        '📎',
        '🖇️',
        '📐',
        '📏',
        '🧮',
        '📌',
        '📍',
        '✂️',
        '🖊️',
        '🖋️',
        '✒️',
        '🖌️',
        '🖍️',
        '📝',
        '✏️',
        '🔍',
        '🔎',
        '🔏',
        '🔐',
        '🔒',
        '🔓',
    ],
    Semboller: [
        '❤️',
        '🧡',
        '💛',
        '💚',
        '💙',
        '💜',
        '🖤',
        '🤍',
        '🤎',
        '💔',
        '❣️',
        '💕',
        '💞',
        '💓',
        '💗',
        '💖',
        '💘',
        '💝',
        '💟',
        '☮️',
        '✝️',
        '☪️',
        '🕉️',
        '☸️',
        '✡️',
        '🔯',
        '🕎',
        '☯️',
        '☦️',
        '🛐',
        '⛎',
        '♈',
        '♉',
        '♊',
        '♋',
        '♌',
        '♍',
        '♎',
        '♏',
        '♐',
        '♑',
        '♒',
        '♓',
        '🆔',
        '⚛️',
        '🉑',
        '☢️',
        '☣️',
        '📴',
        '📳',
        '🈶',
        '🈚',
        '🈸',
        '🈺',
        '🈷️',
        '✴️',
        '🆚',
        '💮',
        '🉐',
        '㊙️',
        '㊗️',
        '🈴',
        '🈵',
        '🈹',
        '🈲',
        '🅰️',
        '🅱️',
        '🆎',
        '🆑',
        '🅾️',
        '🆘',
        '❌',
        '⭕',
        '🛑',
        '⛔',
        '📛',
        '🚫',
        '💯',
        '💢',
        '♨️',
        '🚷',
        '🚯',
        '🚳',
        '🚱',
        '🔞',
        '📵',
        '🚭',
        '❗',
        '❕',
        '❓',
        '❔',
        '‼️',
        '⁉️',
        '🔅',
        '🔆',
        '〽️',
        '⚠️',
        '🚸',
        '🔱',
        '⚜️',
        '🔰',
        '♻️',
        '✅',
        '🈯',
        '💹',
        '❇️',
        '✳️',
        '❎',
        '🌐',
        '💠',
        'Ⓜ️',
        '🌀',
        '💤',
        '🏧',
        '🚾',
        '♿',
        '🅿️',
        '🛗',
        '🈳',
        '🈂️',
        '🛂',
        '🛃',
        '🛄',
        '🛅',
        '🚹',
        '🚺',
        '🚼',
        '⚧️',
        '🚻',
        '🚮',
        '🎦',
        '📶',
        '🈁',
        '🔣',
        'ℹ️',
        '🔤',
        '🔡',
        '🔠',
        '🆖',
        '🆗',
        '🆙',
        '🆒',
        '🆕',
        '🆓',
        '0️⃣',
        '1️⃣',
        '2️⃣',
        '3️⃣',
        '4️⃣',
        '5️⃣',
        '6️⃣',
        '7️⃣',
        '8️⃣',
        '9️⃣',
        '🔟',
        '🔢',
        '#️⃣',
        '*️⃣',
        '⏏️',
        '▶️',
        '⏸️',
        '⏯️',
        '⏹️',
        '⏺️',
        '⏭️',
        '⏮️',
        '⏩',
        '⏪',
        '⏫',
        '⏬',
        '◀️',
        '🔼',
        '🔽',
        '➡️',
        '⬅️',
        '⬆️',
        '⬇️',
        '↗️',
        '↘️',
        '↙️',
        '↖️',
        '↕️',
        '↔️',
        '↪️',
        '↩️',
        '⤴️',
        '⤵️',
        '🔀',
        '🔁',
        '🔂',
        '🔄',
        '🔃',
        '🎵',
        '🎶',
        '➕',
        '➖',
        '➗',
        '✖️',
        '🟰',
        '♾️',
        '💲',
        '💱',
        '™️',
        '©️',
        '®️',
        '〰️',
        '➰',
        '➿',
        '🔚',
        '🔙',
        '🔛',
        '🔝',
        '🔜',
        '✔️',
        '☑️',
        '🔘',
        '🔴',
        '🟠',
        '🟡',
        '🟢',
        '🔵',
        '🟣',
        '⚫',
        '⚪',
        '🟤',
        '🔺',
        '🔻',
        '🔸',
        '🔹',
        '🔶',
        '🔷',
        '🔳',
        '🔲',
        '▪️',
        '▫️',
        '◾',
        '◽',
        '◼️',
        '◻️',
        '🟥',
        '🟧',
        '🟨',
        '🟩',
        '🟦',
        '🟪',
        '⬛',
        '⬜',
        '🟫',
        '🔈',
        '🔇',
        '🔉',
        '🔊',
        '🔔',
        '🔕',
        '📣',
        '📢',
        '👁️‍🗨️',
        '💬',
        '💭',
        '🗯️',
        '♠️',
        '♣️',
        '♥️',
        '♦️',
        '🃏',
        '🎴',
        '🀄',
        '🕐',
        '🕑',
        '🕒',
        '🕓',
        '🕔',
        '🕕',
        '🕖',
        '🕗',
        '🕘',
        '🕙',
        '🕚',
        '🕛',
        '🕜',
        '🕝',
        '🕞',
        '🕟',
        '🕠',
        '🕡',
        '🕢',
        '🕣',
        '🕤',
        '🕥',
        '🕦',
        '🕧',
    ],
    Bayraklar: [
        '🏁',
        '🚩',
        '🎌',
        '🏴',
        '🏳️',
        '🏳️‍🌈',
        '🏳️‍⚧️',
        '🏴‍☠️',
        '🇦🇨',
        '🇦🇩',
        '🇦🇪',
        '🇦🇫',
        '🇦🇬',
        '🇦🇮',
        '🇦🇱',
        '🇦🇲',
        '🇦🇴',
        '🇦🇶',
        '🇦🇷',
        '🇦🇸',
        '🇦🇹',
        '🇦🇺',
        '🇦🇼',
        '🇦🇽',
        '🇦🇿',
        '🇧🇦',
        '🇧🇧',
        '🇧🇩',
        '🇧🇪',
        '🇧🇫',
        '🇧🇬',
        '🇧🇭',
        '🇧🇮',
        '🇧🇯',
        '🇧🇱',
        '🇧🇲',
        '🇧🇳',
        '🇧🇴',
        '🇧🇶',
        '🇧🇷',
        '🇧🇸',
        '🇧🇹',
        '🇧🇻',
        '🇧🇼',
        '🇧🇾',
        '🇧🇿',
        '🇨🇦',
        '🇨🇨',
        '🇨🇩',
        '🇨🇫',
        '🇨🇬',
        '🇨🇭',
        '🇨🇮',
        '🇨🇰',
        '🇨🇱',
        '🇨🇲',
        '🇨🇳',
        '🇨🇴',
        '🇨🇵',
        '🇨🇷',
        '🇨🇺',
        '🇨🇻',
        '🇨🇼',
        '🇨🇽',
        '🇨🇾',
        '🇨🇿',
        '🇩🇪',
        '🇩🇬',
        '🇩🇯',
        '🇩🇰',
        '🇩🇲',
        '🇩🇴',
        '🇩🇿',
        '🇪🇦',
        '🇪🇨',
        '🇪🇪',
        '🇪🇬',
        '🇪🇭',
        '🇪🇷',
        '🇪🇸',
        '🇪🇹',
        '🇪🇺',
        '🇫🇮',
        '🇫🇯',
        '🇫🇰',
        '🇫🇲',
        '🇫🇴',
        '🇫🇷',
        '🇬🇦',
        '🇬🇧',
        '🇬🇩',
        '🇬🇪',
        '🇬🇫',
        '🇬🇬',
        '🇬🇭',
        '🇬🇮',
        '🇬🇱',
        '🇬🇲',
        '🇬🇳',
        '🇬🇵',
        '🇬🇶',
        '🇬🇷',
        '🇬🇸',
        '🇬🇹',
        '🇬🇺',
        '🇬🇼',
        '🇬🇾',
        '🇭🇰',
        '🇭🇲',
        '🇭🇳',
        '🇭🇷',
        '🇭🇹',
        '🇭🇺',
        '🇮🇨',
        '🇮🇩',
        '🇮🇪',
        '🇮🇱',
        '🇮🇲',
        '🇮🇳',
        '🇮🇴',
        '🇮🇶',
        '🇮🇷',
        '🇮🇸',
        '🇮🇹',
        '🇯🇪',
        '🇯🇲',
        '🇯🇴',
        '🇯🇵',
        '🇰🇪',
        '🇰🇬',
        '🇰🇭',
        '🇰🇮',
        '🇰🇲',
        '🇰🇳',
        '🇰🇵',
        '🇰🇷',
        '🇰🇼',
        '🇰🇾',
        '🇰🇿',
        '🇱🇦',
        '🇱🇧',
        '🇱🇨',
        '🇱🇮',
        '🇱🇰',
        '🇱🇷',
        '🇱🇸',
        '🇱🇹',
        '🇱🇺',
        '🇱🇻',
        '🇱🇾',
        '🇲🇦',
        '🇲🇨',
        '🇲🇩',
        '🇲🇪',
        '🇲🇫',
        '🇲🇬',
        '🇲🇭',
        '🇲🇰',
        '🇲🇱',
        '🇲🇲',
        '🇲🇳',
        '🇲🇴',
        '🇲🇵',
        '🇲🇶',
        '🇲🇷',
        '🇲🇸',
        '🇲🇹',
        '🇲🇺',
        '🇲🇻',
        '🇲🇼',
        '🇲🇽',
        '🇲🇾',
        '🇲🇿',
        '🇳🇦',
        '🇳🇨',
        '🇳🇪',
        '🇳🇫',
        '🇳🇬',
        '🇳🇮',
        '🇳🇱',
        '🇳🇴',
        '🇳🇵',
        '🇳🇷',
        '🇳🇺',
        '🇳🇿',
        '🇴🇲',
        '🇵🇦',
        '🇵🇪',
        '🇵🇫',
        '🇵🇬',
        '🇵🇭',
        '🇵🇰',
        '🇵🇱',
        '🇵🇲',
        '🇵🇳',
        '🇵🇷',
        '🇵🇸',
        '🇵🇹',
        '🇵🇼',
        '🇵🇾',
        '🇶🇦',
        '🇷🇪',
        '🇷🇴',
        '🇷🇸',
        '🇷🇺',
        '🇷🇼',
        '🇸🇦',
        '🇸🇧',
        '🇸🇨',
        '🇸🇩',
        '🇸🇪',
        '🇸🇬',
        '🇸🇭',
        '🇸🇮',
        '🇸🇯',
        '🇸🇰',
        '🇸🇱',
        '🇸🇲',
        '🇸🇳',
        '🇸🇴',
        '🇸🇷',
        '🇸🇸',
        '🇸🇹',
        '🇸🇻',
        '🇸🇽',
        '🇸🇾',
        '🇸🇿',
        '🇹🇦',
        '🇹🇨',
        '🇹🇩',
        '🇹🇫',
        '🇹🇬',
        '🇹🇭',
        '🇹🇯',
        '🇹🇰',
        '🇹🇱',
        '🇹🇲',
        '🇹🇳',
        '🇹🇴',
        '🇹🇷',
        '🇹🇹',
        '🇹🇻',
        '🇹🇼',
        '🇹🇿',
        '🇺🇦',
        '🇺🇬',
        '🇺🇲',
        '🇺🇳',
        '🇺🇸',
        '🇺🇾',
        '🇺🇿',
        '🇻🇦',
        '🇻🇨',
        '🇻🇪',
        '🇻🇬',
        '🇻🇮',
        '🇻🇳',
        '🇻🇺',
        '🇼🇫',
        '🇼🇸',
        '🇽🇰',
        '🇾🇪',
        '🇾🇹',
        '🇿🇦',
        '🇿🇲',
        '🇿🇼',
        '🏴󐁧󐁢󐁥󐁮󐁧󐁿',
        '🏴󐁧󐁢󐁳󐁣󐁴󐁿',
        '🏴󐁧󐁢󐁷󐁬󐁳󐁿',
    ],
};

/**
 * @param {Object} props
 * @param {Function} props.onSelect - Callback when an emoji is selected
 */
const EmojiPicker = ({ onSelect }) => {
    const { t } = useTranslation();
    const [activeCategory, setActiveCategory] = useState('Recently Used ⏱️');
    const [isLoading, setIsLoading] = useState(false);
    const [searchTerm, setSearchTerm] = useState('');
    const [trendingEmojis, setTrendingEmojis] = useState([]);
    const [recentEmojis, setRecentEmojis] = useState(getRecents());
    const [favoriteEmojis, setFavoriteEmojis] = useState(getFavorites());
    const [contextMenu, setContextMenu] = useState(null); // {emoji, x, y}
    const [skinTone, setSkinTone] = useState(getSkinTone);

    const handleSkinToneChange = useCallback((tone) => {
        setSkinTone(tone);
        saveSkinTone(tone);
    }, []);

    // 🆕 Fetch trending emojis from API
    useEffect(() => {
        const fetchTrendingEmojis = async () => {
            try {
                const response = await fetch(`${API_BASE_URL}/emoji/trending/`);
                if (response.ok) {
                    const data = await response.json();
                    const emojis = data.map((item) => item.emoji);
                    setTrendingEmojis(emojis);
                    EMOJI_CATEGORIES['Trending 🔥'] = emojis;
                }
            } catch (error) {
                const fallbackTrending = [
                    '🔥',
                    '❤️',
                    '😂',
                    '👍',
                    '🎉',
                    '💯',
                    '✨',
                    '😍',
                    '🚀',
                    '💪',
                ];
                setTrendingEmojis(fallbackTrending);
                EMOJI_CATEGORIES['Trending 🔥'] = fallbackTrending;
            }
        };
        fetchTrendingEmojis();
    }, []);

    // Close context menu on outside click
    useEffect(() => {
        const close = () => setContextMenu(null);
        if (contextMenu) window.addEventListener('click', close);
        return () => window.removeEventListener('click', close);
    }, [contextMenu]);

    const handleSelect = useCallback(
        (emoji) => {
            const finalEmoji = skinTone && SKIN_TONE_EMOJIS.has(emoji) ? emoji + skinTone : emoji;
            addRecent(finalEmoji);
            setRecentEmojis(getRecents());
            onSelect(finalEmoji);
        },
        [onSelect, skinTone]
    );

    const handleContextMenu = useCallback((e, emoji) => {
        e.preventDefault();
        setContextMenu({ emoji, x: e.clientX, y: e.clientY });
    }, []);

    const handleToggleFav = useCallback((emoji) => {
        const newFavs = toggleFavorite(emoji);
        setFavoriteEmojis(newFavs);
        setContextMenu(null);
    }, []);

    // Build dynamic categories with Recents & Favorites at top
    const allCategories = {
        ...(recentEmojis.length > 0 ? { 'Recently Used ⏱️': recentEmojis } : {}),
        ...(favoriteEmojis.length > 0 ? { 'Favoriler ⭐': favoriteEmojis } : {}),
        ...EMOJI_CATEGORIES,
    };

    // Auto-select first available category if current is empty
    const effectiveCategory = allCategories[activeCategory]
        ? activeCategory
        : Object.keys(allCategories)[0];

    const filteredEmojis = searchTerm
        ? Object.values(EMOJI_CATEGORIES)
              .flat()
              .filter((emoji) => emoji.includes(searchTerm))
        : allCategories[effectiveCategory] || [];

    return (
        <div
            style={styles.container}
            role="dialog"
            aria-label={t('ui.emoji_picker')}
            aria-modal="true"
        >
            {/* Search Bar */}
            <div style={styles.searchBar}>
                <input
                    type="text"
                    placeholder={t('emoji.search')}
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    style={styles.searchInput}
                    aria-label={t('emoji.search')}
                />
            </div>

            {/* Skin Tone Selector */}
            <div style={S.flex}>
                <span style={S.txt}>{t('emoji.skinTone')}:</span>
                {SKIN_TONES.map((tone, i) => (
                    <button
                        key={`item-${i}`}
                        title={t(`emoji.skinTone_${SKIN_TONE_LABELS_KEYS[i]}`)}
                        onClick={() => handleSkinToneChange(tone)}
                        aria-label={t(`emoji.skinTone_${SKIN_TONE_LABELS_KEYS[i]}`)}
                        aria-pressed={skinTone === tone}
                        style={{
                            width: 18,
                            height: 18,
                            borderRadius: '50%',
                            border: skinTone === tone ? '2px solid #fff' : '2px solid transparent',
                            backgroundColor: SKIN_TONE_COLORS[i],
                            cursor: 'pointer',
                            padding: 0,
                            transition: 'transform 0.12s ease, box-shadow 0.12s ease',
                            transform: skinTone === tone ? 'scale(1.25)' : 'scale(1)',
                            boxShadow:
                                skinTone === tone ? '0 0 0 3px rgba(88,101,242,0.5)' : 'none',
                        }}
                    />
                ))}
            </div>

            {/* Category Tabs */}
            {!searchTerm && (
                <div style={styles.categories}>
                    {Object.keys(allCategories).map((category) => (
                        <button
                            key={category}
                            onClick={() => setActiveCategory(category)}
                            style={{
                                ...S.el,
                                ...(effectiveCategory === category && styles.activeCategoryButton),
                            }}
                        >
                            {category}
                        </button>
                    ))}
                </div>
            )}

            {/* Emoji Grid */}
            <div style={styles.emojiGrid} role="grid" aria-label={t('ui.emoji_picker')}>
                {filteredEmojis.map((emoji, index) => (
                    <button
                        key={`${emoji}-${index}`}
                        onClick={() => handleSelect(emoji)}
                        onContextMenu={(e) => handleContextMenu(e, emoji)}
                        style={{
                            ...styles.emojiButton,
                            ...(favoriteEmojis.includes(emoji) &&
                            effectiveCategory !== 'Favoriler ⭐'
                                ? styles.favHighlight
                                : {}),
                        }}
                        title={favoriteEmojis.includes(emoji) ? `${emoji} ⭐` : emoji}
                        aria-label={`Emoji ${emoji}`}
                        role="gridcell"
                    >
                        {emoji}
                    </button>
                ))}
                {filteredEmojis.length === 0 && (
                    <div style={styles.emptyState}>
                        {searchTerm
                            ? t('emoji.noResults')
                            : activeCategory === 'Recently Used ⏱️'
                              ? t('emoji.noRecents')
                              : t('emoji.rightClickToFavorite')}
                    </div>
                )}
            </div>

            {/* Context Menu (Right-click) */}
            {contextMenu && (
                <div>
                    <button
                        aria-label="Toggle"
                        style={styles.contextMenuItem}
                        onClick={() => handleToggleFav(contextMenu.emoji)}
                    >
                        {favoriteEmojis.includes(contextMenu.emoji)
                            ? `💔 ${t('emoji.removeFavorite')}`
                            : `⭐ ${t('emoji.addFavorite')}`}
                    </button>
                </div>
            )}
        </div>
    );
};

const MemoizedEmojiPicker = React.memo(EmojiPicker);

MemoizedEmojiPicker.displayName = 'EmojiPicker';

MemoizedEmojiPicker.propTypes = {
    onSelect: PropTypes.func,
};
export default MemoizedEmojiPicker;
