export const THEME_PRESETS = [
    { name: 'Discord Purple', primary: 'var(--color-primary)', accent: 'var(--color-primary-hover)', bg: 'var(--bg-charcoal-deep)' },
    { name: 'Sunset Orange', primary: '#f26522', accent: '#e04e1b', bg: '#2d2420' },
    { name: 'Forest Green', primary: '#3ba55d', accent: '#2d7d46', bg: '#1f2b23' },
    { name: 'Ocean Blue', primary: '#3498db', accent: '#2980b9', bg: '#1e2838' },
    { name: 'Rose Pink', primary: '#e91e63', accent: '#c2185b', bg: '#2d1f26' },
    { name: 'Golden Yellow', primary: 'var(--color-warning)', accent: '#f57c00', bg: '#2d2819' },
    { name: 'Dark Red', primary: 'var(--color-danger)', accent: '#c03537', bg: '#2d1e1f' },
    { name: 'Cyber Purple', primary: 'var(--color-primary)', accent: '#8e44ad', bg: '#251f2d' },
];

const styles = {
    container: {
        width: '100%',
        height: '100%',
        backgroundColor: 'var(--bg-charcoal)',
        display: 'flex',
        flexDirection: 'column',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '16px 20px',
        borderBottom: '1px solid var(--bg-primary)',
        backgroundColor: 'var(--bg-charcoal-deep)',
    },
    title: {
        margin: 0,
        color: 'var(--color-white)',
        fontSize: '20px',
        fontWeight: '600',
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
    },
    headerActions: { display: 'flex', gap: '12px' },
    previewButton: {
        backgroundColor: 'var(--bg-neutral-dark)',
        color: 'var(--color-white)',
        border: 'none',
        padding: '10px 20px',
        borderRadius: '4px',
        cursor: 'pointer',
        fontWeight: '500',
    },
    previewButtonActive: {
        backgroundColor: 'var(--color-primary)',
        color: 'var(--color-white)',
        border: 'none',
        padding: '10px 20px',
        borderRadius: '4px',
        cursor: 'pointer',
        fontWeight: '500',
    },
    saveButton: {
        backgroundColor: 'var(--color-success-muted)',
        color: 'var(--color-white)',
        border: 'none',
        padding: '10px 20px',
        borderRadius: '4px',
        cursor: 'pointer',
        fontWeight: '500',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    editContainer: { flex: 1, overflowY: 'auto', padding: '20px' },
    section: {
        backgroundColor: 'var(--bg-charcoal-deep)',
        borderRadius: '8px',
        padding: '20px',
        marginBottom: '16px',
    },
    sectionTitle: { color: 'var(--color-white)', fontSize: '16px', fontWeight: '600', marginBottom: '16px' },
    inputGroup: { marginBottom: '16px' },
    label: {
        display: 'block',
        color: 'var(--text-secondary)',
        fontSize: '14px',
        marginBottom: '8px',
        fontWeight: '500',
    },
    colorInput: {
        width: '100%',
        height: '50px',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
    },
    fileInput: { display: 'none' },
    uploadButton: {
        backgroundColor: 'var(--color-primary)',
        color: 'var(--color-white)',
        border: 'none',
        padding: '10px 20px',
        borderRadius: '4px',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    presetGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))',
        gap: '12px',
    },
    presetCard: {
        padding: '20px',
        borderRadius: '8px',
        cursor: 'pointer',
        textAlign: 'center',
        transition: 'transform 0.2s',
    },
    presetName: {
        color: 'var(--color-white)',
        fontSize: '13px',
        fontWeight: '600',
        textShadow: '0 2px 4px rgba(0,0,0,0.3)',
    },
    colorGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
        gap: '16px',
    },
    bioTextarea: {
        width: '100%',
        padding: '12px',
        backgroundColor: 'var(--bg-void)',
        border: '1px solid var(--bg-primary)',
        borderRadius: '4px',
        color: 'var(--color-white)',
        fontSize: '14px',
        resize: 'vertical',
        minHeight: '100px',
        fontFamily: 'inherit',
    },
    charCount: { textAlign: 'right', color: 'var(--text-secondary)', fontSize: '12px', marginTop: '8px' },
    checkbox: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        color: 'var(--text-secondary)',
        fontSize: '14px',
        marginBottom: '12px',
        cursor: 'pointer',
    },
    preview: { flex: 1, overflowY: 'auto', padding: '40px' },
    previewBanner: {
        width: '100%',
        height: '200px',
        borderRadius: '8px 8px 0 0',
        backgroundSize: 'cover',
        backgroundPosition: 'center',
    },
    previewContent: {
        backgroundColor: 'var(--bg-charcoal-deep)',
        borderRadius: '0 0 8px 8px',
        padding: '60px 20px 20px',
        position: 'relative',
    },
    previewAvatar: {
        width: '120px',
        height: '120px',
        borderRadius: '50%',
        backgroundColor: 'var(--color-primary)',
        position: 'absolute',
        top: '-60px',
        left: '20px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '48px',
    },
    previewInfo: { marginTop: '20px' },
    loading: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
        color: 'var(--text-secondary)',
    },
};

export { styles };
export default styles;
