export const styles = {
    overlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.85)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 999999 },
    modal: { backgroundColor: '#1e1e1e', borderRadius: '8px', width: '90%', maxWidth: '900px', maxHeight: '85vh', display: 'flex', flexDirection: 'column', color: '#fff' },
    header: { padding: '20px', borderBottom: '1px solid #444', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
    headerLeft: { display: 'flex', alignItems: 'center', gap: '12px' },
    closeBtn: { background: 'none', border: 'none', color: '#fff', fontSize: '24px', cursor: 'pointer', padding: '8px' },
    content: { padding: '20px', overflowY: 'auto', flex: 1 },
    createSection: { backgroundColor: '#2c2f33', borderRadius: '8px', padding: '20px', marginBottom: '24px' },
    sectionTitle: { fontSize: '16px', fontWeight: '600', marginBottom: '16px' },
    exportTypeSelector: { display: 'flex', gap: '12px' },
    select: { flex: 1, padding: '10px', backgroundColor: '#202225', border: '1px solid #444', borderRadius: '6px', color: '#fff', fontSize: '14px' },
    createBtn: { padding: '10px 24px', backgroundColor: '#5865f2', border: 'none', borderRadius: '6px', color: '#fff', fontSize: '14px', fontWeight: '600', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', whiteSpace: 'nowrap' },
    jobsSection: { marginBottom: '24px' },
    loading: { textAlign: 'center', padding: '40px', color: '#99aab5' },
    empty: { textAlign: 'center', padding: '60px 20px', color: '#dcddde' },
    jobsList: { display: 'flex', flexDirection: 'column', gap: '12px' },
    jobCard: { backgroundColor: '#2c2f33', borderRadius: '8px', padding: '16px', display: 'flex', alignItems: 'center', gap: '16px' },
    jobIcon: { fontSize: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
    jobDetails: { flex: 1 },
    jobTitle: { fontSize: '16px', fontWeight: '600', marginBottom: '4px' },
    jobMeta: { fontSize: '12px', color: '#99aab5', marginBottom: '8px' },
    progressBar: { position: 'relative', height: '20px', backgroundColor: '#202225', borderRadius: '10px', overflow: 'hidden', marginTop: '8px' },
    progressFill: { height: '100%', backgroundColor: '#5865f2', transition: 'width 0.3s ease' },
    progressText: { position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', fontSize: '12px', fontWeight: '600', color: '#fff' },
    fileSize: { fontSize: '12px', color: '#99aab5', marginTop: '4px' },
    jobActions: { display: 'flex', alignItems: 'center', gap: '8px' },
    statusBadge: { padding: '4px 12px', borderRadius: '12px', fontSize: '12px', fontWeight: '600', color: '#fff', textTransform: 'uppercase' },
    downloadBtn: { padding: '8px 12px', backgroundColor: '#43b581', border: 'none', borderRadius: '6px', color: '#fff', cursor: 'pointer', fontSize: '14px' },
    deleteBtn: { padding: '8px 12px', backgroundColor: '#f04747', border: 'none', borderRadius: '6px', color: '#fff', cursor: 'pointer', fontSize: '14px' },
    info: { backgroundColor: '#2c2f33', borderRadius: '8px', padding: '16px' },
    infoText: { fontSize: '14px', color: '#dcddde', margin: '8px 0', lineHeight: '1.6' }
};
