// Extracted from ServerSettingsModal.js — centralized styles object

const styles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0,0,0,0.75)',
        backdropFilter: 'blur(8px)',
        WebkitBackdropFilter: 'blur(8px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 3000,
    },
    modal: {
        backgroundColor: 'rgba(30, 31, 35, 0.92)',
        backdropFilter: 'blur(48px) saturate(180%)',
        WebkitBackdropFilter: 'blur(48px) saturate(180%)',
        border: '1px solid rgba(255,255,255,0.07)',
        borderRadius: '12px',
        width: '900px',
        maxWidth: '95vw',
        height: '650px',
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        boxShadow: '0 0 0 1px rgba(88,101,242,0.08), 0 32px 80px rgba(0,0,0,0.65)',
    },

    // Layout
    layoutContainer: { display: 'flex', flex: 1, overflow: 'hidden' },

    // ═══ SIDEBAR ═══
    sidebar: {
        width: '220px',
        minWidth: '220px',
        backgroundColor: 'rgba(17, 18, 20, 0.6)',
        display: 'flex',
        flexDirection: 'column',
        borderRight: '1px solid rgba(255,255,255,0.06)',
    },
    sidebarHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '20px 16px 16px',
        borderBottom: '1px solid rgba(255,255,255,0.06)',
    },
    sidebarServerIcon: {
        width: '40px',
        height: '40px',
        borderRadius: '12px',
        backgroundColor: 'var(--color-primary)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'var(--color-white)',
        fontWeight: '700',
        fontSize: '16px',
        flexShrink: 0,
    },
    sidebarServerInfo: {
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    sidebarServerName: {
        color: 'var(--color-white)',
        fontWeight: '700',
        fontSize: '14px',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    sidebarServerSub: {
        color: 'var(--text-muted)',
        fontSize: '11px',
        marginTop: '2px',
    },
    sidebarNav: {
        flex: 1,
        overflowY: 'auto',
        padding: '8px',
    },
    navSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
    },
    navSectionLabel: {
        fontSize: '11px',
        fontWeight: '700',
        color: 'var(--text-muted)',
        letterSpacing: '0.04em',
        padding: '8px 10px 4px',
        userSelect: 'none',
    },
    navItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        padding: '8px 10px',
        borderRadius: '6px',
        border: 'none',
        background: 'none',
        color: 'var(--text-secondary)',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '500',
        transition: 'all 0.15s ease',
        textAlign: 'left',
        width: '100%',
    },
    navItemActive: {
        backgroundColor: 'rgba(88,101,242,0.15)',
        color: 'var(--color-white)',
    },
    navIcon: {
        fontSize: '14px',
        opacity: 0.8,
        flexShrink: 0,
    },
    navDivider: {
        height: '1px',
        backgroundColor: 'rgba(255,255,255,0.06)',
        margin: '8px 10px',
    },

    // ═══ MAIN CONTENT ═══
    mainContent: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    contentHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '20px 24px 16px',
        borderBottom: '1px solid rgba(255,255,255,0.06)',
    },
    contentTitle: {
        margin: 0,
        color: 'var(--color-white)',
        fontSize: '1.2em',
        fontWeight: '700',
    },
    closeBtn: {
        background: 'none',
        border: 'none',
        color: 'var(--text-secondary)',
        cursor: 'pointer',
        padding: '4px',
        borderRadius: '8px',
        transition: 'color 0.15s',
    },
    content: { flex: 1, padding: '20px 24px', overflow: 'auto' },

    // Legacy compat (header/tabs removed - kept for inner usage)
    header: { display: 'none' },
    headerTitle: { margin: 0, color: 'var(--color-white)', fontSize: '1.2em' },
    tabs: { display: 'none' },
    tabBtn: { display: 'none' },
    activeTab: {},

    // Sol Menü
    rolesSidebar: {
        width: '200px',
        borderRight: '1px solid var(--bg-primary)',
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    newRoleBtn: {
        padding: '10px',
        backgroundColor: 'var(--bg-void)',
        color: 'var(--color-white)',
        border: '1px solid var(--bg-primary)',
        borderRadius: '8px',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        gap: '5px',
    },
    rolesList: { overflowY: 'auto', flex: 1 },
    roleItem: {
        padding: '10px',
        cursor: 'pointer',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderRadius: '8px',
        marginBottom: '2px',
        color: 'var(--text-secondary)',
    },

    // Sağ Editör
    roleEditor: {
        flex: 1,
        paddingLeft: '20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        overflowY: 'auto',
    },
    editorTitle: {
        margin: 0,
        color: 'var(--color-white)',
        borderBottom: '1px solid var(--bg-input)',
        paddingBottom: '10px',
    },
    inputGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '5px',
        color: 'var(--text-secondary)',
        fontSize: '0.9em',
    },
    input: {
        padding: '10px',
        backgroundColor: 'var(--bg-void)',
        border: 'none',
        borderRadius: '8px',
        color: 'var(--color-white)',
        outline: 'none',
    },
    colorPreview: {
        width: '40px',
        height: '40px',
        borderRadius: '8px',
        border: '1px solid var(--color-white)',
        cursor: 'pointer',
    },

    // 🔥 KAPLAMA (COVER) STİLİ: Tüm ekranı kaplar ama z-index with picker'ın altında kalır
    cover: { position: 'fixed', top: '0px', right: '0px', bottom: '0px', left: '0px', zIndex: 999 },

    permissionsGrid: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
        backgroundColor: 'var(--bg-charcoal-deep)',
        padding: '15px',
        borderRadius: '8px',
    },

    // 🛡️ Moderation Cards - YENİ KAPSAMLI STİLLER
    moderationTab: {
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
    },
    moderationHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '16px 20px',
        backgroundColor: 'var(--bg-void)',
        borderRadius: '12px',
        marginBottom: '8px',
    },
    moderationTitleSection: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
    },
    serverStats: {
        display: 'flex',
        gap: '24px',
    },
    statItem: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    statNumber: {
        fontSize: '24px',
        fontWeight: 'bold',
        color: 'var(--color-primary)',
    },
    statLabel: {
        fontSize: '12px',
        color: 'var(--text-muted)',
    },
    quickStatsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: '12px',
    },
    quickStatCard: {
        backgroundColor: 'var(--bg-charcoal-deep)',
        padding: '16px',
        borderRadius: '8px',
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    quickStatValue: {
        fontSize: '16px',
        fontWeight: '600',
        color: 'var(--color-white)',
    },
    quickStatLabel: {
        fontSize: '12px',
        color: 'var(--text-muted)',
    },
    moderationCardsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
        gap: '16px',
    },
    modCard: {
        backgroundColor: 'var(--bg-charcoal-deep)',
        padding: '20px',
        borderRadius: '12px',
        border: '1px solid var(--bg-primary)',
        transition: 'transform 0.2s, box-shadow 0.2s',
    },
    modCardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: '16px',
    },
    modCardIcon: {
        width: '48px',
        height: '48px',
        borderRadius: '12px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modCardBadge: {
        backgroundColor: 'rgba(88, 101, 242, 0.2)',
        color: 'var(--color-primary)',
        padding: '4px 10px',
        borderRadius: '12px',
        fontSize: '11px',
        fontWeight: '600',
    },
    modCardTitle: {
        margin: '0 0 8px',
        color: 'var(--color-white)',
        fontSize: '16px',
        fontWeight: '600',
    },
    modCardDesc: {
        color: 'var(--text-secondary)',
        fontSize: '13px',
        lineHeight: '1.5',
        marginBottom: '16px',
    },
    modCardFeatures: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
        marginBottom: '16px',
    },
    modCardFeature: {
        backgroundColor: 'var(--bg-void)',
        padding: '6px 10px',
        borderRadius: '6px',
        fontSize: '11px',
        color: 'var(--text-secondary)',
    },
    modCardBtn: {
        width: '100%',
        background: 'linear-gradient(135deg, var(--color-primary), var(--color-primary-hover))',
        color: 'var(--color-white)',
        border: 'none',
        borderRadius: '13px',
        boxShadow: '0 4px 0 #3b45c7, 0 8px 24px rgba(88,101,242,0.40)',
        padding: '12px 16px',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '600',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        transition: 'opacity 0.2s',
    },
    quickActionsSection: {
        backgroundColor: 'var(--bg-void)',
        padding: '20px',
        borderRadius: '12px',
    },
    quickActionsTitle: {
        margin: '0 0 16px',
        color: 'var(--color-white)',
        fontSize: '14px',
        fontWeight: '600',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    quickActionsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
        gap: '12px',
    },
    quickActionBtn: {
        backgroundColor: 'var(--bg-charcoal-deep)',
        color: 'var(--text-secondary)',
        border: '1px solid var(--bg-input)',
        borderRadius: '8px',
        padding: '12px 16px',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: '500',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        transition: 'all 0.2s',
    },
    moderationCard: {
        backgroundColor: 'var(--bg-void)',
        padding: '20px',
        borderRadius: '8px',
        border: '1px solid var(--bg-secondary)',
    },
    moderationBtn: {
        width: '100%',
        backgroundColor: 'var(--color-primary)',
        color: 'var(--color-white)',
        border: 'none',
        borderRadius: '13px',
        padding: '10px 16px',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '600',
        transition: 'background-color 0.2s',
        boxShadow: '0 4px 0 #3b45c7, 0 8px 24px rgba(88,101,242,0.40)',
    },
    permLabel: {
        display: 'flex',
        gap: '10px',
        alignItems: 'center',
        color: 'var(--text-primary)',
        cursor: 'pointer',
    },

    editorFooter: {
        marginTop: 'auto',
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '10px',
        borderTop: '1px solid var(--bg-input)',
        paddingTop: '15px',
    },
    saveBtn: {
        padding: '10px 20px',
        background: 'linear-gradient(135deg, var(--color-success), #1a8f4a)',
        color: 'var(--color-white)',
        border: 'none',
        borderRadius: '13px',
        boxShadow: '0 4px 0 #15803d, 0 8px 24px rgba(35,165,89,0.40)',
        cursor: 'pointer',
        fontWeight: 'bold',
        display: 'flex',
        alignItems: 'center',
        gap: '5px',
    },
    deleteBtn: {
        padding: '10px 20px',
        backgroundColor: 'transparent',
        color: 'var(--color-danger-dark)',
        border: '1px solid var(--bg-primary)',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: 'bold',
        display: 'flex',
        alignItems: 'center',
        gap: '5px',
    },

    // 🔥 YENİ: SUNUCU YÖNETİMİ TAB STİLLERİ
    managementTab: {
        display: 'flex',
        flexDirection: 'column',
        gap: '30px',
        maxWidth: '600px',
        margin: '0 auto',
    },
    sectionTitle: {
        margin: 0,
        color: 'var(--color-white)',
        fontSize: '1.1em',
        borderBottom: '2px solid var(--bg-input)',
        paddingBottom: '10px',
    },
    settingBox: {
        backgroundColor: 'var(--bg-charcoal-deep)',
        padding: '20px',
        borderRadius: '8px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '20px',
    },
    settingInfo: {
        flex: 1,
    },
    settingLabel: {
        color: 'var(--color-white)',
        fontSize: '1em',
        fontWeight: 'bold',
        marginBottom: '5px',
    },
    settingDesc: {
        color: 'var(--text-secondary)',
        fontSize: '0.9em',
    },
    actionBtn: {
        padding: '10px 20px',
        color: 'var(--color-white)',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: 'bold',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        fontSize: '0.95em',
        whiteSpace: 'nowrap',
    },
    divider: {
        height: '1px',
        backgroundColor: 'var(--bg-neutral-dark)',
        margin: '10px 0',
    },
    dangerBox: {
        backgroundColor: 'var(--bg-charcoal-deep)',
        padding: '20px',
        borderRadius: '8px',
        border: '2px solid var(--color-danger-dark)',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: '20px',
    },
    dangerBtn: {
        padding: '10px 20px',
        backgroundColor: 'var(--color-danger-dark)',
        color: 'var(--color-white)',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: 'bold',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        fontSize: '0.95em',
    },
    deleteConfirmation: {
        marginTop: '15px',
        padding: '15px',
        backgroundColor: 'var(--bg-void)',
        borderRadius: '8px',
    },
    confirmInput: {
        width: '100%',
        padding: '10px',
        backgroundColor: 'var(--bg-charcoal)',
        border: '1px solid var(--color-danger-dark)',
        borderRadius: '8px',
        color: 'var(--color-white)',
        fontSize: '0.95em',
        outline: 'none',
    },
    cancelBtn: {
        padding: '10px 20px',
        backgroundColor: 'transparent',
        color: 'var(--text-secondary)',
        border: '1px solid var(--bg-input)',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: 'bold',
    },
};

export default styles;
