// Accessibility API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, apiFetch } from './shared';

// ==========================================
// 🖼️ #50 - View Preferences
// ==========================================
export const viewPreferencesApi = {
    getPreferences: async () => {
        return await apiFetch(`${API_BASE}/api/preferences/view/`);
    },
    updatePreferences: async (data) => {
        return await apiFetch(`${API_BASE}/api/preferences/view/`, {
            method: 'PUT',
            body: JSON.stringify(data)
        });
    }
};

// ==========================================
// ♿ #47 - Screen Reader Optimization (Accessibility)
// ==========================================
export const accessibilityApi = {
    getSettings: async () => {
        return await apiFetch(`${API_BASE}/api/preferences/accessibility/`);
    },
    updateSettings: async (settings) => {
        return await apiFetch(`${API_BASE}/api/preferences/accessibility/`, {
            method: 'PATCH',
            body: JSON.stringify(settings)
        });
    }
};

// ==========================================
// 🔠 #48 - Dyslexia-Friendly Font
// ==========================================
export const dyslexiaApi = {
    getSettings: async () => {
        return await apiFetch(`${API_BASE}/api/preferences/dyslexia/`);
    },
    updateSettings: async (settings) => {
        return await apiFetch(`${API_BASE}/api/preferences/dyslexia/`, {
            method: 'PATCH',
            body: JSON.stringify(settings)
        });
    }
};

// ==========================================
// 📱 #49 - Gesture Controls
// ==========================================
export const gestureApi = {
    getSettings: async () => {
        return await apiFetch(`${API_BASE}/api/preferences/gestures/`);
    },
    updateSettings: async (settings) => {
        return await apiFetch(`${API_BASE}/api/preferences/gestures/`, {
            method: 'PATCH',
            body: JSON.stringify(settings)
        });
    }
};

// ==========================================
// 🌍 #53 - RTL Language Support
// ==========================================
export const rtlApi = {
    getSettings: async () => {
        return await apiFetch(`${API_BASE}/api/preferences/rtl/`);
    },
    updateSettings: async (settings) => {
        return await apiFetch(`${API_BASE}/api/preferences/rtl/`, {
            method: 'PATCH',
            body: JSON.stringify(settings)
        });
    }
};
