// Accessibility API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, getAuthHeaders } from './shared';

// ==========================================
// 🖼️ #50 - View Preferences
// ==========================================
export const viewPreferencesApi = {
    getPreferences: async () => {
        const res = await fetch(`${API_BASE}/api/preferences/view/`, { headers: getAuthHeaders() });
        return res.json();
    },
    updatePreferences: async (data) => {
        const res = await fetch(`${API_BASE}/api/preferences/view/`, {
            method: 'PUT',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    }
};

// ==========================================
// ♿ #47 - Screen Reader Optimization (Accessibility)
// ==========================================
export const accessibilityApi = {
    getSettings: async () => {
        const res = await fetch(`${API_BASE}/api/preferences/accessibility/`, { headers: getAuthHeaders() });
        return res.json();
    },
    updateSettings: async (settings) => {
        const res = await fetch(`${API_BASE}/api/preferences/accessibility/`, {
            method: 'PATCH',
            headers: getAuthHeaders(),
            body: JSON.stringify(settings)
        });
        return res.json();
    }
};

// ==========================================
// 🔠 #48 - Dyslexia-Friendly Font
// ==========================================
export const dyslexiaApi = {
    getSettings: async () => {
        const res = await fetch(`${API_BASE}/api/preferences/dyslexia/`, { headers: getAuthHeaders() });
        return res.json();
    },
    updateSettings: async (settings) => {
        const res = await fetch(`${API_BASE}/api/preferences/dyslexia/`, {
            method: 'PATCH',
            headers: getAuthHeaders(),
            body: JSON.stringify(settings)
        });
        return res.json();
    }
};

// ==========================================
// 📱 #49 - Gesture Controls
// ==========================================
export const gestureApi = {
    getSettings: async () => {
        const res = await fetch(`${API_BASE}/api/preferences/gestures/`, { headers: getAuthHeaders() });
        return res.json();
    },
    updateSettings: async (settings) => {
        const res = await fetch(`${API_BASE}/api/preferences/gestures/`, {
            method: 'PATCH',
            headers: getAuthHeaders(),
            body: JSON.stringify(settings)
        });
        return res.json();
    }
};

// ==========================================
// 🌍 #53 - RTL Language Support
// ==========================================
export const rtlApi = {
    getSettings: async () => {
        const res = await fetch(`${API_BASE}/api/preferences/rtl/`, { headers: getAuthHeaders() });
        return res.json();
    },
    updateSettings: async (settings) => {
        const res = await fetch(`${API_BASE}/api/preferences/rtl/`, {
            method: 'PATCH',
            headers: getAuthHeaders(),
            body: JSON.stringify(settings)
        });
        return res.json();
    }
};
