// Admin API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, getAuthHeaders } from './shared';

// NOTE: Original code used undefined `BASE` and `getToken()` variables.
// Fixed to use API_BASE and getAuthHeaders() for consistency.

// ==========================================
// 🛡️ ADVANCED ADMIN PANEL API
// ==========================================
export const adminPanelApi = {
    // System Logs - Tüm log tiplerini birleştirir
    getSystemLogs: async (params = {}) => {
        const queryParams = new URLSearchParams();
        if (params.type) queryParams.append('type', params.type);
        if (params.limit) queryParams.append('limit', params.limit);
        if (params.offset) queryParams.append('offset', params.offset);
        if (params.search) queryParams.append('search', params.search);
        if (params.severity) queryParams.append('severity', params.severity);
        if (params.date_from) queryParams.append('date_from', params.date_from);
        if (params.date_to) queryParams.append('date_to', params.date_to);

        const res = await fetch(`${API_BASE}/admin/system-logs/?${queryParams}`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },

    // Realtime Metrics
    getRealtimeMetrics: async () => {
        const res = await fetch(`${API_BASE}/admin/realtime-metrics/`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },

    // User Activity Timeline
    getUserActivity: async (userId, limit = 50) => {
        const res = await fetch(`${API_BASE}/admin/users/${userId}/activity/?limit=${limit}`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },

    // Batch User Actions
    batchUserAction: async (action, userIds, reason = '') => {
        const res = await fetch(`${API_BASE}/admin/batch-action/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ action, user_ids: userIds, reason })
        });
        return res.json();
    },

    // IP Blacklist
    getIPBlacklist: async (search = '', limit = 50) => {
        const res = await fetch(`${API_BASE}/admin/ip-blacklist/?search=${search}&limit=${limit}`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },

    addIPToBlacklist: async (ipAddress, reason = '', durationHours = null) => {
        const res = await fetch(`${API_BASE}/admin/ip-blacklist/add/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ ip_address: ipAddress, reason, duration_hours: durationHours })
        });
        return res.json();
    },

    removeIPFromBlacklist: async (blacklistId) => {
        const res = await fetch(`${API_BASE}/admin/ip-blacklist/${blacklistId}/remove/`, {
            method: 'DELETE',
            headers: getAuthHeaders()
        });
        return res.json();
    },

    // Appeals
    getAppeals: async (status = 'pending', limit = 50) => {
        const res = await fetch(`${API_BASE}/admin/appeals/?status=${status}&limit=${limit}`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },

    reviewAppeal: async (appealId, decision, response = '') => {
        const res = await fetch(`${API_BASE}/admin/appeals/${appealId}/review/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ decision, response })
        });
        return res.json();
    },

    // Feature Flags
    getFeatureFlags: async () => {
        const res = await fetch(`${API_BASE}/admin/feature-flags/`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },

    // Log Export
    exportLogs: async (type = 'audit', format = 'json', dateFrom = null, dateTo = null, limit = 1000) => {
        const res = await fetch(`${API_BASE}/admin/logs/export/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ type, format, date_from: dateFrom, date_to: dateTo, limit })
        });

        if (format === 'csv') {
            return res.blob();
        }
        return res.json();
    },

    // Rate Limits
    getRateLimitDashboard: async () => {
        const res = await fetch(`${API_BASE}/admin/rate-limits/`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },

    // Scheduled Tasks
    getScheduledTasks: async () => {
        const res = await fetch(`${API_BASE}/admin/scheduled-tasks/`, {
            headers: getAuthHeaders()
        });
        return res.json();
    }
};
