// Admin API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, apiFetch } from './shared';

// NOTE: Original code used undefined `BASE` and `getToken()` variables.
// Fixed to use API_BASE and apiFetch() for consistency.

// ==========================================
// 🛡️ ADVANCED ADMIN PANEL API
// ==========================================
export const adminPanelApi = {
    // System Logs - Tüm log tiplerini birleştirir
    getSystemLogs: async (params = {}) => {
        const queryParams = new URLSearchParams();
        if (params.type) queryParams.append('type', params.type);
        if (params.limit) queryParams.append('limit', params.limit);
        if (params.offset) queryParams.append('offset', params.offset);
        if (params.search) queryParams.append('search', params.search);
        if (params.severity) queryParams.append('severity', params.severity);
        if (params.date_from) queryParams.append('date_from', params.date_from);
        if (params.date_to) queryParams.append('date_to', params.date_to);

        return await apiFetch(`${API_BASE}/admin/system-logs/?${queryParams}`);
    },

    // Realtime Metrics
    getRealtimeMetrics: async () => {
        return await apiFetch(`${API_BASE}/admin/realtime-metrics/`);
    },

    // User Activity Timeline
    getUserActivity: async (userId, limit = 50) => {
        return await apiFetch(`${API_BASE}/admin/users/${userId}/activity/?limit=${limit}`);
    },

    // Batch User Actions
    batchUserAction: async (action, userIds, reason = '') => {
        return await apiFetch(`${API_BASE}/admin/batch-action/`, {
            method: 'POST',
            body: JSON.stringify({ action, user_ids: userIds, reason })
        });
    },

    // IP Blacklist
    getIPBlacklist: async (search = '', limit = 50) => {
        return await apiFetch(`${API_BASE}/admin/ip-blacklist/?search=${search}&limit=${limit}`);
    },

    addIPToBlacklist: async (ipAddress, reason = '', durationHours = null) => {
        return await apiFetch(`${API_BASE}/admin/ip-blacklist/add/`, {
            method: 'POST',
            body: JSON.stringify({ ip_address: ipAddress, reason, duration_hours: durationHours })
        });
    },

    removeIPFromBlacklist: async (blacklistId) => {
        return await apiFetch(`${API_BASE}/admin/ip-blacklist/${blacklistId}/remove/`, {
            method: 'DELETE'
        });
    },

    // Appeals
    getAppeals: async (status = 'pending', limit = 50) => {
        return await apiFetch(`${API_BASE}/admin/appeals/?status=${status}&limit=${limit}`);
    },

    reviewAppeal: async (appealId, decision, response = '') => {
        return await apiFetch(`${API_BASE}/admin/appeals/${appealId}/review/`, {
            method: 'POST',
            body: JSON.stringify({ decision, response })
        });
    },

    // Feature Flags
    getFeatureFlags: async () => {
        return await apiFetch(`${API_BASE}/admin/feature-flags/`);
    },

    // Log Export
    exportLogs: async (type = 'audit', format = 'json', dateFrom = null, dateTo = null, limit = 1000) => {
        return await apiFetch(`${API_BASE}/admin/logs/export/`, {
            method: 'POST',
            body: JSON.stringify({ type, format, date_from: dateFrom, date_to: dateTo, limit })
        });
    },

    // Rate Limits
    getRateLimitDashboard: async () => {
        return await apiFetch(`${API_BASE}/admin/rate-limits/`);
    },

    // Scheduled Tasks
    getScheduledTasks: async () => {
        return await apiFetch(`${API_BASE}/admin/scheduled-tasks/`);
    }
};
