// Ai API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, getAuthHeaders } from './shared';

// ==========================================
// 🤖 #79 - Custom Bot Builder (No-Code)
// ==========================================
export const botBuilderApi = {
    getBots: async (serverId) => {
        const res = await fetch(`${API_BASE}/api/servers/${serverId}/bots/`, { headers: getAuthHeaders() });
        return res.json();
    },
    createBot: async (serverId, botData) => {
        const res = await fetch(`${API_BASE}/api/servers/${serverId}/bots/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify(botData)
        });
        return res.json();
    },
    getBot: async (botId) => {
        const res = await fetch(`${API_BASE}/api/bots/${botId}/`, { headers: getAuthHeaders() });
        return res.json();
    },
    updateBot: async (botId, data) => {
        const res = await fetch(`${API_BASE}/api/bots/${botId}/`, {
            method: 'PATCH',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    },
    deleteBot: async (botId) => {
        const res = await fetch(`${API_BASE}/api/bots/${botId}/`, {
            method: 'DELETE',
            headers: getAuthHeaders()
        });
        return res.json();
    },
    addTrigger: async (botId, triggerData) => {
        const res = await fetch(`${API_BASE}/api/bots/${botId}/triggers/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify(triggerData)
        });
        return res.json();
    },
    getLogs: async (botId, limit = 50) => {
        const res = await fetch(`${API_BASE}/api/bots/${botId}/logs/?limit=${limit}`, {
            headers: getAuthHeaders()
        });
        return res.json();
    }
};

// ==========================================
// 🧠 #74 - AI Chat Summarization
// ==========================================
export const chatSummaryApi = {
    generateSummary: async (roomId, options = {}) => {
        const res = await fetch(`${API_BASE}/api/summaries/generate/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ room_id: roomId, ...options })
        });
        return res.json();
    },
    getSummaries: async (roomId) => {
        const res = await fetch(`${API_BASE}/api/rooms/${roomId}/summaries/`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },
    getSharedSummary: async (shareToken) => {
        const res = await fetch(`${API_BASE}/api/summaries/shared/${shareToken}/`);
        return res.json();
    }
};

// ==========================================
// 🎨 #75 - AI Image Generation
// ==========================================
export const aiImageApi = {
    generate: async (prompt, options = {}) => {
        const res = await fetch(`${API_BASE}/api/ai/generate-image/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ prompt, ...options })
        });
        return res.json();
    },
    getHistory: async () => {
        const res = await fetch(`${API_BASE}/api/ai/images/`, { headers: getAuthHeaders() });
        return res.json();
    },
    getSettings: async (serverId) => {
        const res = await fetch(`${API_BASE}/api/servers/${serverId}/ai-image/settings/`, { headers: getAuthHeaders() });
        return res.json();
    },
    updateSettings: async (serverId, settings) => {
        const res = await fetch(`${API_BASE}/api/servers/${serverId}/ai-image/settings/`, {
            method: 'PATCH',
            headers: getAuthHeaders(),
            body: JSON.stringify(settings)
        });
        return res.json();
    }
};

// ==========================================
// 🔍 #78 - Content Recommendation Engine
// ==========================================
export const recommendationApi = {
    get: async (type = 'all') => {
        const res = await fetch(`${API_BASE}/api/recommendations/?type=${type}`, { headers: getAuthHeaders() });
        return res.json();
    },
    feedback: async (recId, action) => {
        const res = await fetch(`${API_BASE}/api/recommendations/${recId}/feedback/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ action })
        });
        return res.json();
    }
};

// ==========================================
// 🗨️ #82 - Language Learning Chatbot
// ==========================================
export const languageLearningApi = {
    startSession: async (nativeLanguage, targetLanguage, level = 'beginner') => {
        const res = await fetch(`${API_BASE}/api/language-learning/start/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ native_language: nativeLanguage, target_language: targetLanguage, proficiency_level: level })
        });
        return res.json();
    },
    chat: async (sessionId, message) => {
        const res = await fetch(`${API_BASE}/api/language-learning/sessions/${sessionId}/chat/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ message })
        });
        return res.json();
    },
    getProgress: async (language) => {
        const res = await fetch(`${API_BASE}/api/language-learning/progress/${language}/`, { headers: getAuthHeaders() });
        return res.json();
    }
};
