// Analytics API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, getAuthHeaders } from './shared';

// ==========================================
// 📊 #11 - Social Analytics
// ==========================================
export const socialAnalyticsApi = {
    getStats: async (days = 30) => {
        const res = await fetch(`${API_BASE}/api/analytics/social/?days=${days}`, { headers: getAuthHeaders() });
        return res.json();
    }
};

// ==========================================
// 📈 #96 - Advanced User Analytics
// ==========================================
export const userAnalyticsApi = {
    getSummary: async (userId = null) => {
        const url = userId
            ? `${API_BASE}/api/analytics/user/summary/?user_id=${userId}`
            : `${API_BASE}/api/analytics/user/summary/`;
        const res = await fetch(url, { headers: getAuthHeaders() });
        return res.json();
    },
    getHistory: async (days = 30, userId = null) => {
        let url = `${API_BASE}/api/analytics/user/history/?days=${days}`;
        if (userId) url += `&user_id=${userId}`;
        const res = await fetch(url, { headers: getAuthHeaders() });
        return res.json();
    },
    getWordCloud: async (days = 30, userId = null) => {
        let url = `${API_BASE}/api/analytics/user/wordcloud/?days=${days}`;
        if (userId) url += `&user_id=${userId}`;
        const res = await fetch(url, { headers: getAuthHeaders() });
        return res.json();
    }
};

// ==========================================
// 📊 #97 - Server Growth Metrics
// ==========================================
export const serverGrowthApi = {
    getMetrics: async (serverId, days = 30) => {
        const res = await fetch(`${API_BASE}/api/servers/${serverId}/growth/?days=${days}`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },
    getRetention: async (serverId) => {
        const res = await fetch(`${API_BASE}/api/servers/${serverId}/retention/`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },
    getConversionFunnel: async (serverId, days = 30) => {
        const res = await fetch(`${API_BASE}/api/servers/${serverId}/funnel/?days=${days}`, {
            headers: getAuthHeaders()
        });
        return res.json();
    }
};

// ==========================================
// 🗂️ #98 - Data Export Tools (GDPR)
// ==========================================
export const dataExportApi = {
    getRequests: async () => {
        const res = await fetch(`${API_BASE}/api/export/requests/`, { headers: getAuthHeaders() });
        return res.json();
    },
    createRequest: async (data) => {
        const res = await fetch(`${API_BASE}/api/export/requests/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    },
    download: async (exportId) => {
        const res = await fetch(`${API_BASE}/api/export/${exportId}/download/`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },
    getScheduled: async () => {
        const res = await fetch(`${API_BASE}/api/export/scheduled/`, { headers: getAuthHeaders() });
        return res.json();
    },
    createScheduled: async (data) => {
        const res = await fetch(`${API_BASE}/api/export/scheduled/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    },
    deleteScheduled: async (scheduleId) => {
        const res = await fetch(`${API_BASE}/api/export/scheduled/`, {
            method: 'DELETE',
            headers: getAuthHeaders(),
            body: JSON.stringify({ schedule_id: scheduleId })
        });
        return res.json();
    }
};

// ==========================================
// 📉 #99 - Performance Monitoring Dashboard
// ==========================================
export const performanceApi = {
    getSystemMetrics: async () => {
        const res = await fetch(`${API_BASE}/api/admin/metrics/`, { headers: getAuthHeaders() });
        return res.json();
    },
    getErrorLogs: async (options = {}) => {
        const params = new URLSearchParams();
        if (options.severity) params.append('severity', options.severity);
        if (options.resolved !== undefined) params.append('resolved', options.resolved);
        if (options.limit) params.append('limit', options.limit);

        const url = `${API_BASE}/api/admin/errors/?${params.toString()}`;
        const res = await fetch(url, { headers: getAuthHeaders() });
        return res.json();
    },
    resolveError: async (errorId, note = '') => {
        const res = await fetch(`${API_BASE}/api/admin/errors/${errorId}/resolve/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ note })
        });
        return res.json();
    },
    getEndpointMetrics: async (days = 7) => {
        const res = await fetch(`${API_BASE}/api/admin/endpoints/?days=${days}`, {
            headers: getAuthHeaders()
        });
        return res.json();
    },
    getHealthStatus: async () => {
        const res = await fetch(`${API_BASE}/api/admin/health/`, { headers: getAuthHeaders() });
        return res.json();
    }
};
