// Analytics API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, apiFetch } from './shared';

// ==========================================
// 📊 #11 - Social Analytics
// ==========================================
export const socialAnalyticsApi = {
    getStats: async (days = 30) => {
        return await apiFetch(`${API_BASE}/api/analytics/social/?days=${days}`);
    }
};

// ==========================================
// 📈 #96 - Advanced User Analytics
// ==========================================
export const userAnalyticsApi = {
    getSummary: async (userId = null) => {
        const url = userId
            ? `${API_BASE}/api/analytics/user/summary/?user_id=${userId}`
            : `${API_BASE}/api/analytics/user/summary/`;
        return await apiFetch(url);
    },
    getHistory: async (days = 30, userId = null) => {
        let url = `${API_BASE}/api/analytics/user/history/?days=${days}`;
        if (userId) url += `&user_id=${userId}`;
        return await apiFetch(url);
    },
    getWordCloud: async (days = 30, userId = null) => {
        let url = `${API_BASE}/api/analytics/user/wordcloud/?days=${days}`;
        if (userId) url += `&user_id=${userId}`;
        return await apiFetch(url);
    }
};

// ==========================================
// 📊 #97 - Server Growth Metrics
// ==========================================
export const serverGrowthApi = {
    getMetrics: async (serverId, days = 30) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/growth/?days=${days}`);
    },
    getRetention: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/retention/`);
    },
    getConversionFunnel: async (serverId, days = 30) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/funnel/?days=${days}`);
    }
};

// ==========================================
// 🗂️ #98 - Data Export Tools (GDPR)
// ==========================================
export const dataExportApi = {
    getRequests: async () => {
        return await apiFetch(`${API_BASE}/api/export/requests/`);
    },
    createRequest: async (data) => {
        return await apiFetch(`${API_BASE}/api/export/requests/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    },
    download: async (exportId) => {
        return await apiFetch(`${API_BASE}/api/export/${exportId}/download/`);
    },
    getScheduled: async () => {
        return await apiFetch(`${API_BASE}/api/export/scheduled/`);
    },
    createScheduled: async (data) => {
        return await apiFetch(`${API_BASE}/api/export/scheduled/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    },
    deleteScheduled: async (scheduleId) => {
        return await apiFetch(`${API_BASE}/api/export/scheduled/`, {
            method: 'DELETE',
            body: JSON.stringify({ schedule_id: scheduleId })
        });
    }
};

// ==========================================
// 📉 #99 - Performance Monitoring Dashboard
// ==========================================
export const performanceApi = {
    getSystemMetrics: async () => {
        return await apiFetch(`${API_BASE}/api/admin/metrics/`);
    },
    getErrorLogs: async (options = {}) => {
        const params = new URLSearchParams();
        if (options.severity) params.append('severity', options.severity);
        if (options.resolved !== undefined) params.append('resolved', options.resolved);
        if (options.limit) params.append('limit', options.limit);

        const url = `${API_BASE}/api/admin/errors/?${params.toString()}`;
        return await apiFetch(url);
    },
    resolveError: async (errorId, note = '') => {
        return await apiFetch(`${API_BASE}/api/admin/errors/${errorId}/resolve/`, {
            method: 'POST',
            body: JSON.stringify({ note })
        });
    },
    getEndpointMetrics: async (days = 7) => {
        return await apiFetch(`${API_BASE}/api/admin/endpoints/?days=${days}`);
    },
    getHealthStatus: async () => {
        return await apiFetch(`${API_BASE}/api/admin/health/`);
    }
};
