// Chat API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, getAuthHeaders } from './shared';

// ==========================================
// 💌 #16 - Anonymous Feedback
// ==========================================
export const feedbackApi = {
    sendFeedback: async (data) => {
        const res = await fetch(`${API_BASE}/api/feedback/send/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    },
    getMyFeedbacks: async () => {
        const res = await fetch(`${API_BASE}/api/feedback/`, { headers: getAuthHeaders() });
        return res.json();
    }
};

// ==========================================
// 🔮 #18 - Time Capsule
// ==========================================
export const timeCapsuleApi = {
    getCapsules: async () => {
        const res = await fetch(`${API_BASE}/api/time-capsule/`, { headers: getAuthHeaders() });
        return res.json();
    },
    createCapsule: async (data) => {
        const res = await fetch(`${API_BASE}/api/time-capsule/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    }
};

// ==========================================
// 📱 #20 - QR Codes
// ==========================================
export const qrCodeApi = {
    generate: async (data) => {
        const res = await fetch(`${API_BASE}/api/qr/generate/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    },
    scan: async (code) => {
        const res = await fetch(`${API_BASE}/api/qr/${code}/`, { headers: getAuthHeaders() });
        return res.json();
    }
};

// ==========================================
// 🧵 #21 - Advanced Threading
// ==========================================
export const threadingApi = {
    getSettings: async (threadId) => {
        const res = await fetch(`${API_BASE}/api/threads/${threadId}/settings/`, { headers: getAuthHeaders() });
        return res.json();
    },
    updateSettings: async (threadId, data) => {
        const res = await fetch(`${API_BASE}/api/threads/${threadId}/settings/`, {
            method: 'PUT',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    },
    subscribe: async (threadId, level = 'all') => {
        const res = await fetch(`${API_BASE}/api/threads/${threadId}/subscribe/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ notification_level: level })
        });
        return res.json();
    },
    unsubscribe: async (threadId) => {
        const res = await fetch(`${API_BASE}/api/threads/${threadId}/subscribe/`, {
            method: 'DELETE',
            headers: getAuthHeaders()
        });
        return res.json();
    }
};

// ==========================================
// 📝 #23 - Message Templates
// ==========================================
export const messageTemplatesApi = {
    getTemplates: async (serverId = null) => {
        const url = serverId
            ? `${API_BASE}/api/templates/?server_id=${serverId}`
            : `${API_BASE}/api/templates/`;
        const res = await fetch(url, { headers: getAuthHeaders() });
        return res.json();
    },
    createTemplate: async (data) => {
        const res = await fetch(`${API_BASE}/api/templates/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    }
};

// ==========================================
// 🔍 #25 - Advanced Search
// ==========================================
export const advancedSearchApi = {
    search: async (query, filters = {}) => {
        const res = await fetch(`${API_BASE}/api/search/advanced/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ query, filters })
        });
        return res.json();
    }
};

// ==========================================
// 💾 #27 - Message Auto-Delete
// ==========================================
export const autoDeleteApi = {
    getSettings: async () => {
        const res = await fetch(`${API_BASE}/api/settings/auto-delete/`, { headers: getAuthHeaders() });
        return res.json();
    },
    updateSettings: async (data) => {
        const res = await fetch(`${API_BASE}/api/settings/auto-delete/`, {
            method: 'PUT',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    }
};

// ==========================================
// 🔗 #29 - Link Preview
// ==========================================
export const linkPreviewApi = {
    fetchPreview: async (url) => {
        const res = await fetch(`${API_BASE}/api/link-preview/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ url })
        });
        return res.json();
    }
};

// ==========================================
// 🗣️ #31 - TTS Settings
// ==========================================
export const ttsApi = {
    getSettings: async () => {
        const res = await fetch(`${API_BASE}/api/tts/settings/`, { headers: getAuthHeaders() });
        return res.json();
    },
    updateSettings: async (data) => {
        const res = await fetch(`${API_BASE}/api/tts/settings/`, {
            method: 'PUT',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    }
};

// ==========================================
// 📦 #32 - Message Bundles
// ==========================================
export const messageBundlesApi = {
    getBundles: async () => {
        const res = await fetch(`${API_BASE}/api/bundles/`, { headers: getAuthHeaders() });
        return res.json();
    },
    createBundle: async (data) => {
        const res = await fetch(`${API_BASE}/api/bundles/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    }
};

// ==========================================
// 🔐 #34 - Ephemeral Messages
// ==========================================
export const ephemeralApi = {
    getSettings: async (conversationId = null, roomId = null) => {
        let url = `${API_BASE}/api/ephemeral/settings/`;
        if (conversationId) url += `?conversation_id=${conversationId}`;
        if (roomId) url += `?room_id=${roomId}`;
        const res = await fetch(url, { headers: getAuthHeaders() });
        return res.json();
    },
    updateSettings: async (data) => {
        const res = await fetch(`${API_BASE}/api/ephemeral/settings/`, {
            method: 'PUT',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    }
};

// ==========================================
// 💬 #35 - Translation
// ==========================================
export const translationApi = {
    translate: async (text, targetLanguage = 'en') => {
        const res = await fetch(`${API_BASE}/api/translate/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ text, target_language: targetLanguage })
        });
        return res.json();
    },
    getPreference: async () => {
        const res = await fetch(`${API_BASE}/api/translation/preference/`, { headers: getAuthHeaders() });
        return res.json();
    },
    updatePreference: async (data) => {
        const res = await fetch(`${API_BASE}/api/translation/preference/`, {
            method: 'PUT',
            headers: getAuthHeaders(),
            body: JSON.stringify(data)
        });
        return res.json();
    }
};

// ==========================================
// 📌 #22 - Smart Pinned Messages
// ==========================================
export const smartPinApi = {
    getPins: async (roomId) => {
        const res = await fetch(`${API_BASE}/api/rooms/${roomId}/pins/`, { headers: getAuthHeaders() });
        return res.json();
    },
    createPin: async (roomId, messageId, options = {}) => {
        const res = await fetch(`${API_BASE}/api/rooms/${roomId}/pins/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ message_id: messageId, ...options })
        });
        return res.json();
    },
    deletePin: async (pinId) => {
        const res = await fetch(`${API_BASE}/api/pins/${pinId}/`, {
            method: 'DELETE',
            headers: getAuthHeaders()
        });
        return res.json();
    }
};

// ==========================================
// 📅 #26 - Message Scheduling with Recurrence
// ==========================================
export const messageSchedulingApi = {
    getScheduled: async () => {
        const res = await fetch(`${API_BASE}/api/scheduled-messages/`, { headers: getAuthHeaders() });
        return res.json();
    },
    scheduleMessage: async (roomId, content, scheduledAt, recurrence = {}) => {
        const res = await fetch(`${API_BASE}/api/scheduled-messages/`, {
            method: 'POST',
            headers: getAuthHeaders(),
            body: JSON.stringify({ room_id: roomId, content, scheduled_at: scheduledAt, ...recurrence })
        });
        return res.json();
    },
    cancelScheduled: async (messageId) => {
        const res = await fetch(`${API_BASE}/api/scheduled-messages/${messageId}/`, {
            method: 'DELETE',
            headers: getAuthHeaders()
        });
        return res.json();
    }
};

// ==========================================
// 🎯 #33 - Smart Mention Suggestions
// ==========================================
export const mentionSuggestionApi = {
    getSuggestions: async (roomId, query = '') => {
        const res = await fetch(`${API_BASE}/api/rooms/${roomId}/mention-suggestions/?q=${query}`, {
            headers: getAuthHeaders()
        });
        return res.json();
    }
};
