// Nice-to-Have API Services - Central Index
// Auto-generated by split_nice_to_have_api.py

export { getAuthHeaders, API_BASE } from './shared';

export {
    viewPreferencesApi,
    accessibilityApi,
    dyslexiaApi,
    gestureApi,
    rtlApi
} from './accessibility';

export {
    adminPanelApi
} from './admin';

export {
    botBuilderApi,
    chatSummaryApi,
    aiImageApi,
    recommendationApi,
    languageLearningApi
} from './ai';

export {
    socialAnalyticsApi,
    userAnalyticsApi,
    serverGrowthApi,
    dataExportApi,
    performanceApi
} from './analytics';

export {
    feedbackApi,
    timeCapsuleApi,
    qrCodeApi,
    threadingApi,
    messageTemplatesApi,
    advancedSearchApi,
    autoDeleteApi,
    linkPreviewApi,
    ttsApi,
    messageBundlesApi,
    ephemeralApi,
    translationApi,
    smartPinApi,
    messageSchedulingApi,
    mentionSuggestionApi
} from './chat';

export {
    voiceTranscriptionApi,
    voiceRecordingApi,
    annotationApi,
    callTranscriptApi,
    voiceQueueApi
} from './media';

export {
    gameEventsApi,
    emergencyBroadcastApi,
    customThemesApi,
    notificationScheduleApi,
    miniGamesApi
} from './misc';

export {
    appealApi,
    toxicityApi,
    imageModerationApi,
    spamDetectionApi,
    moderationAssistantApi
} from './moderation';

export {
    securityApi,
    auditRetentionApi,
    e2eeKeysApi,
    hardwareKeyApi,
    altAccountApi
} from './security';

export {
    birthdayApi,
    giftApi,
    leaderboardApi,
    moodApi,
    profileThemeApi,
    achievementShowcaseApi,
    relationshipApi,
    storyApi,
    interestApi
} from './social';

// Import all for default export
import { viewPreferencesApi, accessibilityApi, dyslexiaApi, gestureApi, rtlApi } from './accessibility';
import { adminPanelApi } from './admin';
import { botBuilderApi, chatSummaryApi, aiImageApi, recommendationApi, languageLearningApi } from './ai';
import { socialAnalyticsApi, userAnalyticsApi, serverGrowthApi, dataExportApi, performanceApi } from './analytics';
import { feedbackApi, timeCapsuleApi, qrCodeApi, threadingApi, messageTemplatesApi, advancedSearchApi, autoDeleteApi, linkPreviewApi, ttsApi, messageBundlesApi, ephemeralApi, translationApi, smartPinApi, messageSchedulingApi, mentionSuggestionApi } from './chat';
import { voiceTranscriptionApi, voiceRecordingApi, annotationApi, callTranscriptApi, voiceQueueApi } from './media';
import { gameEventsApi, emergencyBroadcastApi, customThemesApi, notificationScheduleApi, miniGamesApi } from './misc';
import { appealApi, toxicityApi, imageModerationApi, spamDetectionApi, moderationAssistantApi } from './moderation';
import { securityApi, auditRetentionApi, e2eeKeysApi, hardwareKeyApi, altAccountApi } from './security';
import { birthdayApi, giftApi, leaderboardApi, moodApi, profileThemeApi, achievementShowcaseApi, relationshipApi, storyApi, interestApi } from './social';

export default {
    viewPreferences: viewPreferencesApi,
    accessibility: accessibilityApi,
    dyslexia: dyslexiaApi,
    gesture: gestureApi,
    rtl: rtlApi,
    adminPanel: adminPanelApi,
    botBuilder: botBuilderApi,
    chatSummary: chatSummaryApi,
    aiImage: aiImageApi,
    recommendation: recommendationApi,
    languageLearning: languageLearningApi,
    socialAnalytics: socialAnalyticsApi,
    userAnalytics: userAnalyticsApi,
    serverGrowth: serverGrowthApi,
    dataExport: dataExportApi,
    performance: performanceApi,
    feedback: feedbackApi,
    timeCapsule: timeCapsuleApi,
    qrCode: qrCodeApi,
    threading: threadingApi,
    messageTemplates: messageTemplatesApi,
    advancedSearch: advancedSearchApi,
    autoDelete: autoDeleteApi,
    linkPreview: linkPreviewApi,
    tts: ttsApi,
    messageBundles: messageBundlesApi,
    ephemeral: ephemeralApi,
    translation: translationApi,
    smartPin: smartPinApi,
    messageScheduling: messageSchedulingApi,
    mentionSuggestion: mentionSuggestionApi,
    voiceTranscription: voiceTranscriptionApi,
    voiceRecording: voiceRecordingApi,
    annotation: annotationApi,
    callTranscript: callTranscriptApi,
    voiceQueue: voiceQueueApi,
    gameEvents: gameEventsApi,
    emergencyBroadcast: emergencyBroadcastApi,
    customThemes: customThemesApi,
    notificationSchedule: notificationScheduleApi,
    miniGames: miniGamesApi,
    appeal: appealApi,
    toxicity: toxicityApi,
    imageModeration: imageModerationApi,
    spamDetection: spamDetectionApi,
    moderationAssistant: moderationAssistantApi,
    security: securityApi,
    auditRetention: auditRetentionApi,
    e2eeKeys: e2eeKeysApi,
    hardwareKey: hardwareKeyApi,
    altAccount: altAccountApi,
    birthday: birthdayApi,
    gift: giftApi,
    leaderboard: leaderboardApi,
    mood: moodApi,
    profileTheme: profileThemeApi,
    achievementShowcase: achievementShowcaseApi,
    relationship: relationshipApi,
    story: storyApi,
    interest: interestApi,
};
