// Media API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, apiFetch } from './shared';

// ==========================================
// 🎤 #12 - Voice Transcription
// ==========================================
export const voiceTranscriptionApi = {
    transcribe: async (messageId) => {
        return await apiFetch(`${API_BASE}/api/messages/${messageId}/transcribe/`, {
            method: 'POST'
        });
    }
};

// ==========================================
// 🎙️ #56 - Voice Channel Recording
// ==========================================
export const voiceRecordingApi = {
    getRecordings: async (channelId) => {
        return await apiFetch(`${API_BASE}/api/voice-channels/${channelId}/recordings/`);
    },
    startRecording: async (channelId) => {
        return await apiFetch(`${API_BASE}/api/voice-channels/${channelId}/recordings/`, {
            method: 'POST',
            body: JSON.stringify({ action: 'start' })
        });
    },
    stopRecording: async (channelId, recordingId) => {
        return await apiFetch(`${API_BASE}/api/voice-channels/${channelId}/recordings/`, {
            method: 'POST',
            body: JSON.stringify({ action: 'stop', recording_id: recordingId })
        });
    },
    giveConsent: async (recordingId, consent = true) => {
        return await apiFetch(`${API_BASE}/api/recordings/${recordingId}/consent/`, {
            method: 'POST',
            body: JSON.stringify({ consent })
        });
    }
};

// ==========================================
// 🎬 #61 - Screen Share Annotations
// ==========================================
export const annotationApi = {
    getAnnotations: async (sessionId) => {
        return await apiFetch(`${API_BASE}/api/screen-share/${sessionId}/annotations/`);
    },
    addAnnotation: async (sessionId, annotationData) => {
        return await apiFetch(`${API_BASE}/api/screen-share/${sessionId}/annotations/`, {
            method: 'POST',
            body: JSON.stringify(annotationData)
        });
    },
    clearAnnotations: async (sessionId) => {
        return await apiFetch(`${API_BASE}/api/screen-share/${sessionId}/annotations/clear/`, {
            method: 'DELETE'
        });
    }
};

// ==========================================
// 📞 #62 - Call Recording with Transcription
// ==========================================
export const callTranscriptApi = {
    getTranscript: async (recordingId) => {
        return await apiFetch(`${API_BASE}/api/recordings/${recordingId}/transcript/`);
    },
    requestTranscription: async (recordingId) => {
        return await apiFetch(`${API_BASE}/api/recordings/${recordingId}/transcribe/`, {
            method: 'POST'
        });
    }
};

// ==========================================
// 🎤 #63 - Voice Channel Queue System
// ==========================================
export const voiceQueueApi = {
    getQueue: async (channelId) => {
        return await apiFetch(`${API_BASE}/api/voice-channels/${channelId}/queue/`);
    },
    toggleQueue: async (channelId) => {
        return await apiFetch(`${API_BASE}/api/voice-channels/${channelId}/queue/`, {
            method: 'POST',
            body: JSON.stringify({ action: 'toggle' })
        });
    },
    raiseHand: async (channelId) => {
        return await apiFetch(`${API_BASE}/api/voice-channels/${channelId}/queue/`, {
            method: 'POST',
            body: JSON.stringify({ action: 'raise_hand' })
        });
    },
    lowerHand: async (channelId) => {
        return await apiFetch(`${API_BASE}/api/voice-channels/${channelId}/queue/`, {
            method: 'POST',
            body: JSON.stringify({ action: 'lower_hand' })
        });
    },
    nextSpeaker: async (channelId) => {
        return await apiFetch(`${API_BASE}/api/voice-channels/${channelId}/queue/`, {
            method: 'POST',
            body: JSON.stringify({ action: 'next_speaker' })
        });
    }
};
