// Misc API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, apiFetch } from './shared';

// ==========================================
// 🎮 #14 - Game Events
// ==========================================
export const gameEventsApi = {
    getServerEvents: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/events/`);
    },
    createEvent: async (serverId, data) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/events/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    },
    rsvp: async (eventId, status) => {
        return await apiFetch(`${API_BASE}/api/events/${eventId}/rsvp/`, {
            method: 'POST',
            body: JSON.stringify({ status })
        });
    },
    cancelRsvp: async (eventId) => {
        return await apiFetch(`${API_BASE}/api/events/${eventId}/rsvp/`, {
            method: 'DELETE'
        });
    }
};

// ==========================================
// 🚨 #45 - Emergency Broadcast
// ==========================================
export const emergencyBroadcastApi = {
    getBroadcasts: async (serverId = null) => {
        const url = serverId
            ? `${API_BASE}/api/servers/${serverId}/emergency/`
            : `${API_BASE}/api/emergency/`;
        return await apiFetch(url);
    },
    createBroadcast: async (serverId, data) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/emergency/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    },
    acknowledge: async (broadcastId) => {
        return await apiFetch(`${API_BASE}/api/emergency/${broadcastId}/ack/`, {
            method: 'POST'
        });
    }
};

// ==========================================
// 🌓 #46 - Custom Themes
// ==========================================
export const customThemesApi = {
    getThemes: async () => {
        return await apiFetch(`${API_BASE}/api/themes/`);
    },
    createTheme: async (data) => {
        return await apiFetch(`${API_BASE}/api/themes/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    },
    installTheme: async (themeId) => {
        return await apiFetch(`${API_BASE}/api/themes/${themeId}/install/`, {
            method: 'POST'
        });
    },
    uninstallTheme: async (themeId) => {
        return await apiFetch(`${API_BASE}/api/themes/${themeId}/install/`, {
            method: 'DELETE'
        });
    }
};

// ==========================================
// 🔔 #9 - Smart Notification Scheduling
// ==========================================
export const notificationScheduleApi = {
    getSchedules: async () => {
        return await apiFetch(`${API_BASE}/api/notifications/schedules/`);
    },
    createSchedule: async (scheduleData) => {
        return await apiFetch(`${API_BASE}/api/notifications/schedules/`, {
            method: 'POST',
            body: JSON.stringify(scheduleData)
        });
    },
    getFocusMode: async () => {
        return await apiFetch(`${API_BASE}/api/focus-mode/`);
    },
    updateFocusMode: async (settings) => {
        return await apiFetch(`${API_BASE}/api/focus-mode/`, {
            method: 'PATCH',
            body: JSON.stringify(settings)
        });
    },
    toggleFocusMode: async () => {
        return await apiFetch(`${API_BASE}/api/focus-mode/`, {
            method: 'POST'
        });
    }
};

// ==========================================
// 🎲 #84 - Built-in Mini Games
// ==========================================
export const miniGamesApi = {
    getGames: async () => {
        return await apiFetch(`${API_BASE}/api/games/`);
    },
    createMatch: async (gameId, roomId = null) => {
        return await apiFetch(`${API_BASE}/api/games/match/`, {
            method: 'POST',
            body: JSON.stringify({ game_id: gameId, room_id: roomId })
        });
    },
    getMatch: async (matchId) => {
        return await apiFetch(`${API_BASE}/api/games/matches/${matchId}/`);
    },
    joinMatch: async (matchId) => {
        return await apiFetch(`${API_BASE}/api/games/matches/${matchId}/`, {
            method: 'POST',
            body: JSON.stringify({ action: 'join' })
        });
    },
    makeMove: async (matchId, move) => {
        return await apiFetch(`${API_BASE}/api/games/matches/${matchId}/`, {
            method: 'POST',
            body: JSON.stringify({ action: 'move', move })
        });
    },
    endMatch: async (matchId, winnerId = null, isDraw = false) => {
        return await apiFetch(`${API_BASE}/api/games/matches/${matchId}/`, {
            method: 'POST',
            body: JSON.stringify({ action: 'end', winner_id: winnerId, is_draw: isDraw })
        });
    },
    getStats: async (gameId = null) => {
        const url = gameId ? `${API_BASE}/api/games/stats/${gameId}/` : `${API_BASE}/api/games/stats/`;
        return await apiFetch(url);
    },
    getTournaments: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/games/tournaments/`);
    },
    createTournament: async (serverId, tournamentData) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/games/tournaments/`, {
            method: 'POST',
            body: JSON.stringify(tournamentData)
        });
    },
    joinTournament: async (tournamentId) => {
        return await apiFetch(`${API_BASE}/api/games/tournaments/${tournamentId}/join/`, {
            method: 'POST'
        });
    }
};
