// Moderation API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, apiFetch } from './shared';

// ==========================================
// ⚖️ #43 - Appeal System
// ==========================================
export const appealApi = {
    getMyAppeals: async () => {
        return await apiFetch(`${API_BASE}/api/appeals/`);
    },
    createAppeal: async (data) => {
        return await apiFetch(`${API_BASE}/api/appeals/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    },
    getAppealDetails: async (appealId) => {
        return await apiFetch(`${API_BASE}/api/appeals/${appealId}/`);
    },
    reviewAppeal: async (appealId, data) => {
        return await apiFetch(`${API_BASE}/api/appeals/${appealId}/`, {
            method: 'PUT',
            body: JSON.stringify(data)
        });
    }
};

// ==========================================
// 🚨 #36 - AI-Powered Toxicity Detection
// ==========================================
export const toxicityApi = {
    checkContent: async (content, context = {}) => {
        return await apiFetch(`${API_BASE}/api/moderation/toxicity/check/`, {
            method: 'POST',
            body: JSON.stringify({ content, context })
        });
    },
    getSettings: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/toxicity/settings/`);
    },
    updateSettings: async (serverId, settings) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/toxicity/settings/`, {
            method: 'PATCH',
            body: JSON.stringify(settings)
        });
    },
    reportFalsePositive: async (checkId, reason) => {
        return await apiFetch(`${API_BASE}/api/toxicity/${checkId}/false-positive/`, {
            method: 'POST',
            body: JSON.stringify({ reason })
        });
    }
};

// ==========================================
// 📸 #38 - Image Moderation AI
// ==========================================
export const imageModerationApi = {
    scanImage: async (imageUrl) => {
        return await apiFetch(`${API_BASE}/api/moderation/image/scan/`, {
            method: 'POST',
            body: JSON.stringify({ image_url: imageUrl })
        });
    },
    getSettings: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/image-moderation/settings/`);
    },
    updateSettings: async (serverId, settings) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/image-moderation/settings/`, {
            method: 'PATCH',
            body: JSON.stringify(settings)
        });
    },
    getQueue: async (serverId, status = 'pending') => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/image-moderation/queue/?status=${status}`);
    },
    reviewImage: async (serverId, itemId, action) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/image-moderation/queue/`, {
            method: 'POST',
            body: JSON.stringify({ item_id: itemId, action })
        });
    }
};

// ==========================================
// 🚫 #39 - Advanced Spam Detection
// ==========================================
export const spamDetectionApi = {
    checkContent: async (data) => {
        return await apiFetch(`${API_BASE}/api/moderation/spam/check/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    },
    getSettings: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/spam/settings/`);
    },
    updateSettings: async (serverId, settings) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/spam/settings/`, {
            method: 'PATCH',
            body: JSON.stringify(settings)
        });
    }
};

// ==========================================
// 🧩 #81 - AI Content Moderation Assistant
// ==========================================
export const moderationAssistantApi = {
    getSuggestions: async (serverId, status = 'pending') => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/moderation/suggestions/?status=${status}`);
    },
    reviewSuggestion: async (suggestionId, action, note = '') => {
        return await apiFetch(`${API_BASE}/api/moderation/suggestions/${suggestionId}/review/`, {
            method: 'POST',
            body: JSON.stringify({ action, note })
        });
    },
    getSettings: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/moderation/assistant/settings/`);
    },
    updateSettings: async (serverId, settings) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/moderation/assistant/settings/`, {
            method: 'PATCH',
            body: JSON.stringify(settings)
        });
    },
    getEfficiency: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/moderation/efficiency/`);
    }
};
