// Security API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, apiFetch } from './shared';

// ==========================================
// 🕵️ #40 - Security Activity
// ==========================================
export const securityApi = {
    getActivityLog: async () => {
        return await apiFetch(`${API_BASE}/api/security/activity/`);
    },
    getTrustedDevices: async () => {
        return await apiFetch(`${API_BASE}/api/security/devices/`);
    },
    removeDevice: async (deviceId) => {
        return await apiFetch(`${API_BASE}/api/security/devices/${deviceId}/`, {
            method: 'DELETE'
        });
    }
};

// ==========================================
// 📜 #42 - Audit Log Retention
// ==========================================
export const auditRetentionApi = {
    getPolicy: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/audit/policy/`);
    },
    updatePolicy: async (serverId, data) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/audit/policy/`, {
            method: 'PUT',
            body: JSON.stringify(data)
        });
    },
    getArchives: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/audit/archives/`);
    }
};

// ==========================================
// 🔐 #44 - E2EE Keys
// ==========================================
export const e2eeKeysApi = {
    getMyKeys: async () => {
        return await apiFetch(`${API_BASE}/api/e2ee/keys/`);
    },
    registerKeys: async (data) => {
        return await apiFetch(`${API_BASE}/api/e2ee/keys/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    },
    getUserPublicKey: async (userId) => {
        return await apiFetch(`${API_BASE}/api/e2ee/keys/${userId}/`);
    }
};

// ==========================================
// 🔒 #37 - Two-Factor Hardware Key Support
// ==========================================
export const hardwareKeyApi = {
    getKeys: async () => {
        return await apiFetch(`${API_BASE}/api/auth/2fa/hardware-keys/`);
    },
    registerKey: async (keyData) => {
        return await apiFetch(`${API_BASE}/api/auth/2fa/hardware-keys/`, {
            method: 'POST',
            body: JSON.stringify(keyData)
        });
    },
    deleteKey: async (keyId) => {
        return await apiFetch(`${API_BASE}/api/auth/2fa/hardware-keys/`, {
            method: 'DELETE',
            body: JSON.stringify({ key_id: keyId })
        });
    },
    generateBackupCodes: async () => {
        return await apiFetch(`${API_BASE}/api/auth/2fa/backup-codes/`, {
            method: 'POST'
        });
    },
    useBackupCode: async (code) => {
        return await apiFetch(`${API_BASE}/api/auth/2fa/backup-codes/`, {
            method: 'PUT',
            body: JSON.stringify({ code })
        });
    },
    getSettings: async () => {
        return await apiFetch(`${API_BASE}/api/auth/2fa/settings/`);
    },
    updateSettings: async (settings) => {
        return await apiFetch(`${API_BASE}/api/auth/2fa/settings/`, {
            method: 'PATCH',
            body: JSON.stringify(settings)
        });
    }
};

// ==========================================
// 🎭 #41 - Alt Account Detection
// ==========================================
export const altAccountApi = {
    recordFingerprint: async (fingerprintData) => {
        return await apiFetch(`${API_BASE}/api/fingerprint/`, {
            method: 'POST',
            body: JSON.stringify(fingerprintData)
        });
    },
    getSuspicions: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/alt-accounts/`);
    },
    reviewSuspicion: async (suspicionId, result) => {
        return await apiFetch(`${API_BASE}/api/alt-accounts/${suspicionId}/review/`, {
            method: 'POST',
            body: JSON.stringify({ result })
        });
    }
};
