// Shared helpers for nice-to-have API services
// Auto-generated by split_nice_to_have_api.py — Enhanced with error handling

import { API_BASE } from '../../config';
import logger from '../../utils/logger';
import { getToken } from '../../utils/tokenStorage';

export const getAuthHeaders = () => ({
    Authorization: `Bearer ${getToken()}`,
    'Content-Type': 'application/json',
});

/**
 * 🛡️ Resilient fetch wrapper for services/api layer.
 * - Adds auth headers automatically
 * - Checks response.ok → throws descriptive error on failure
 * - Token expired (401) → triggers auth:logout event
 * - Network error → returns null (caller gets null instead of crash)
 */
export const apiFetch = async (url, options = {}) => {
    const headers = { ...getAuthHeaders(), ...options.headers };

    // Remove Content-Type for FormData (browser sets boundary automatically)
    if (options.body instanceof FormData) {
        delete headers['Content-Type'];
    }

    try {
        const response = await fetch(url, { ...options, headers, credentials: 'include' });

        if (response.status === 401) {
            // Token expired — trigger logout
            window.dispatchEvent(new CustomEvent('auth:logout'));
            return null;
        }

        if (!response.ok) {
            // Log but don't crash — caller handles null
            logger.warn(`⚠️ [API] ${options.method || 'GET'} ${url} → ${response.status}`);
            return null;
        }

        // Handle 204 No Content
        if (response.status === 204) return { success: true };

        const contentType = response.headers.get('content-type') || '';
        if (contentType.includes('application/json')) {
            return await response.json();
        }

        // Non-JSON response (blob, text, etc.)
        return await response.text();
    } catch (error) {
        // Network error (offline, DNS, CORS, etc.)
        logger.warn(`⚠️ [API] Network error: ${options.method || 'GET'} ${url}`, error.message);
        return null;
    }
};

export { API_BASE };
