// Shared helpers for nice-to-have API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE } from '../../config';

export const getAuthHeaders = () => ({
    'Authorization': `Bearer ${localStorage.getItem('access_token')}`,
    'Content-Type': 'application/json'
});

export { API_BASE };
