// Social API services
// Auto-generated by split_nice_to_have_api.py

import { API_BASE, apiFetch } from './shared';

// ==========================================
// 🎂 #2 - Birthday Calendar
// ==========================================
export const birthdayApi = {
    getBirthday: async () => {
        return await apiFetch(`${API_BASE}/api/birthday/`);
    },
    setBirthday: async (data) => {
        return await apiFetch(`${API_BASE}/api/birthday/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    },
    getBirthdaysToday: async () => {
        return await apiFetch(`${API_BASE}/api/birthdays/today/`);
    },
    getServerBirthdays: async (serverId) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/birthdays/`);
    }
};

// ==========================================
// 💝 #5 - Gift System
// ==========================================
export const giftApi = {
    sendGift: async (data) => {
        return await apiFetch(`${API_BASE}/api/gifts/send/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    },
    getMyGifts: async () => {
        return await apiFetch(`${API_BASE}/api/gifts/`);
    },
    openGift: async (giftId) => {
        return await apiFetch(`${API_BASE}/api/gifts/${giftId}/open/`, {
            method: 'POST'
        });
    }
};

// ==========================================
// 🏆 #6 - Leaderboard
// ==========================================
export const leaderboardApi = {
    getServerLeaderboard: async (serverId, type = 'xp', limit = 10) => {
        return await apiFetch(`${API_BASE}/api/servers/${serverId}/leaderboard/?type=${type}&limit=${limit}`);
    },
    getGlobalLeaderboard: async (type = 'xp', limit = 10) => {
        return await apiFetch(`${API_BASE}/api/leaderboard/global/?type=${type}&limit=${limit}`);
    }
};

// ==========================================
// 🎭 #7 - User Mood
// ==========================================
export const moodApi = {
    getMood: async () => {
        return await apiFetch(`${API_BASE}/api/mood/`);
    },
    setMood: async (data) => {
        return await apiFetch(`${API_BASE}/api/mood/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    },
    getUserStatus: async (userId) => {
        return await apiFetch(`${API_BASE}/api/users/${userId}/status/`);
    }
};

// ==========================================
// 🎨 #10 - Profile Themes
// ==========================================
export const profileThemeApi = {
    getTheme: async () => {
        return await apiFetch(`${API_BASE}/api/profile/theme/`);
    },
    setTheme: async (data) => {
        return await apiFetch(`${API_BASE}/api/profile/theme/`, {
            method: 'POST',
            body: JSON.stringify(data)
        });
    }
};

// ==========================================
// 🏅 #15 - Achievement Showcase
// ==========================================
export const achievementShowcaseApi = {
    getShowcase: async () => {
        return await apiFetch(`${API_BASE}/api/achievements/showcase/`);
    },
    updateShowcase: async (data) => {
        return await apiFetch(`${API_BASE}/api/achievements/showcase/`, {
            method: 'PUT',
            body: JSON.stringify(data)
        });
    }
};

// ==========================================
// 👫 #1 - User Relationship System
// ==========================================
export const relationshipApi = {
    getAll: async () => {
        return await apiFetch(`${API_BASE}/api/relationships/`);
    },
    create: async (targetUserId, type = 'friend', nickname = null) => {
        return await apiFetch(`${API_BASE}/api/relationships/`, {
            method: 'POST',
            body: JSON.stringify({ target_user_id: targetUserId, relationship_type: type, nickname })
        });
    },
    getDetail: async (relationshipId) => {
        return await apiFetch(`${API_BASE}/api/relationships/${relationshipId}/`);
    },
    delete: async (relationshipId) => {
        return await apiFetch(`${API_BASE}/api/relationships/${relationshipId}/`, {
            method: 'DELETE'
        });
    }
};

// ==========================================
// 📸 #3 - Story/Status System
// ==========================================
export const storyApi = {
    getFeed: async () => {
        return await apiFetch(`${API_BASE}/api/stories/`);
    },
    create: async (storyData) => {
        return await apiFetch(`${API_BASE}/api/stories/`, {
            method: 'POST',
            body: JSON.stringify(storyData)
        });
    },
    view: async (storyId) => {
        return await apiFetch(`${API_BASE}/api/stories/${storyId}/`, {
            method: 'POST',
            body: JSON.stringify({ action: 'view' })
        });
    },
    react: async (storyId, emoji) => {
        return await apiFetch(`${API_BASE}/api/stories/${storyId}/`, {
            method: 'POST',
            body: JSON.stringify({ action: 'react', emoji })
        });
    },
    delete: async (storyId) => {
        return await apiFetch(`${API_BASE}/api/stories/${storyId}/`, {
            method: 'DELETE'
        });
    },
    getHighlights: async () => {
        return await apiFetch(`${API_BASE}/api/stories/highlights/`);
    },
    createHighlight: async (title, storyIds) => {
        return await apiFetch(`${API_BASE}/api/stories/highlights/`, {
            method: 'POST',
            body: JSON.stringify({ title, story_ids: storyIds })
        });
    }
};

// ==========================================
// 🎯 #17 - Interest Tags & Matching
// ==========================================
export const interestApi = {
    getTags: async (category = null) => {
        const url = category ? `${API_BASE}/api/interests/tags/?category=${category}` : `${API_BASE}/api/interests/tags/`;
        return await apiFetch(url);
    },
    getUserInterests: async () => {
        return await apiFetch(`${API_BASE}/api/interests/`);
    },
    addInterest: async (tagId, skillLevel = 'intermediate') => {
        return await apiFetch(`${API_BASE}/api/interests/`, {
            method: 'POST',
            body: JSON.stringify({ tag_id: tagId, skill_level: skillLevel })
        });
    },
    removeInterest: async (interestId) => {
        return await apiFetch(`${API_BASE}/api/interests/`, {
            method: 'DELETE',
            body: JSON.stringify({ interest_id: interestId })
        });
    },
    getMatches: async () => {
        return await apiFetch(`${API_BASE}/api/interests/matches/`);
    }
};
