export const injectInviteStyles = () => {
    if (typeof document === 'undefined') return;
    const id = 'invite-modal-styles';
    if (document.getElementById(id)) return;
    const tag = document.createElement('style');
    tag.id = id;
    tag.textContent = `
        .invite-friend-item:hover { background: rgba(88, 101, 242, 0.06) !important; }
        @keyframes inviteSpin { to { transform: rotate(360deg); } }
    `;
    document.head.appendChild(tag);
};

const st = {
    overlay: {
        position: 'fixed',
        top: 0, left: 0, right: 0, bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 99999,
        backdropFilter: 'blur(4px)',
    },
    modal: {
        backgroundColor: '#313338',
        borderRadius: '12px',
        width: '460px',
        maxWidth: '92vw',
        maxHeight: '80vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '0 16px 48px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.04)',
        overflow: 'hidden',
        animation: 'contextMenuIn 0.15s ease-out',
    },
    header: {
        padding: '20px 20px 8px 20px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    headerRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        marginBottom: '4px',
    },
    serverLabel: {
        color: '#b5bac1',
        fontSize: '12px',
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: '0.02em',
    },
    title: {
        margin: 0,
        color: '#f2f3f5',
        fontSize: '18px',
        fontWeight: '700',
    },
    closeBtn: {
        background: 'none',
        border: 'none',
        color: '#b5bac1',
        cursor: 'pointer',
        fontSize: '18px',
        padding: '4px',
        borderRadius: '4px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchWrap: {
        padding: '8px 20px 4px 20px',
    },
    searchBox: {
        backgroundColor: '#1e1f22',
        borderRadius: '8px',
        padding: '0 12px',
        display: 'flex',
        alignItems: 'center',
    },
    searchIcon: {
        color: '#6d6f78',
        marginRight: '10px',
        fontSize: '14px',
        flexShrink: 0,
    },
    searchInput: {
        backgroundColor: 'transparent',
        border: 'none',
        color: '#f2f3f5',
        padding: '10px 0',
        flex: 1,
        outline: 'none',
        fontSize: '14px',
    },
    friendList: {
        flex: 1,
        overflowY: 'auto',
        padding: '8px 12px',
        minHeight: '120px',
        maxHeight: '280px',
    },
    friendItem: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '8px 10px',
        borderRadius: '8px',
        transition: 'background 0.15s',
        cursor: 'default',
    },
    friendInfo: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        minWidth: 0,
    },
    friendAvatar: {
        width: '36px',
        height: '36px',
        borderRadius: '50%',
        backgroundColor: '#5865f2',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        flexShrink: 0,
    },
    avatarImg: {
        width: '100%',
        height: '100%',
        objectFit: 'cover',
    },
    avatarLetter: {
        color: '#fff',
        fontSize: '15px',
        fontWeight: '600',
    },
    friendName: {
        color: '#f2f3f5',
        fontSize: '14px',
        fontWeight: '500',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    inviteBtn: {
        padding: '6px 16px',
        backgroundColor: 'transparent',
        border: '1px solid #248046',
        color: '#2dc770',
        borderRadius: '4px',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: '500',
        transition: 'all 0.15s',
        whiteSpace: 'nowrap',
        display: 'flex',
        alignItems: 'center',
        flexShrink: 0,
    },
    inviteBtnSent: {
        border: '1px solid #4e5058',
        color: '#b5bac1',
        cursor: 'default',
        backgroundColor: 'transparent',
    },
    emptyState: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '32px 20px',
        gap: '4px',
    },
    emptyText: {
        color: '#6d6f78',
        fontSize: '14px',
        textAlign: 'center',
    },
    spinner: {
        width: '20px',
        height: '20px',
        border: '2px solid #4e5058',
        borderTopColor: '#5865f2',
        borderRadius: '50%',
        animation: 'inviteSpin 0.6s linear infinite',
    },
    linkSection: {
        backgroundColor: '#2b2d31',
        padding: '16px 20px',
        borderTop: '1px solid rgba(255,255,255,0.04)',
    },
    linkLabel: {
        color: '#b5bac1',
        fontSize: '11px',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.02em',
        marginBottom: '10px',
    },
    linkBox: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        backgroundColor: '#1e1f22',
        borderRadius: '8px',
        padding: '4px 4px 4px 12px',
        minHeight: '44px',
    },
    linkInputWrap: {
        display: 'flex',
        alignItems: 'center',
        flex: 1,
        minWidth: 0,
    },
    linkInput: {
        flex: 1,
        backgroundColor: 'transparent',
        border: 'none',
        color: '#00a8fc',
        fontSize: '13px',
        outline: 'none',
        textOverflow: 'ellipsis',
        minWidth: 0,
    },
    linkLoading: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        flex: 1,
        padding: '4px 0',
    },
    linkError: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flex: 1,
        padding: '4px 0',
    },
    copyBtn: {
        padding: '8px 16px',
        backgroundColor: '#5865f2',
        border: 'none',
        borderRadius: '4px',
        color: 'white',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: '600',
        transition: 'background 0.15s',
        whiteSpace: 'nowrap',
        flexShrink: 0,
    },
    copyBtnDone: {
        backgroundColor: '#248046',
    },
    retryBtn: {
        padding: '6px 12px',
        backgroundColor: '#5865f2',
        border: 'none',
        borderRadius: '4px',
        color: 'white',
        cursor: 'pointer',
        fontSize: '12px',
        fontWeight: '500',
    },
    linkNote: {
        color: '#6d6f78',
        fontSize: '11px',
        marginTop: '8px',
    },
    regenBtn: {
        background: 'transparent',
        border: '1px solid rgba(255,255,255,0.1)',
        color: '#b5bac1',
        padding: '6px 12px',
        borderRadius: '4px',
        fontSize: '12px',
        marginTop: '6px',
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        transition: 'all 0.15s',
    },
};

export default st;
