export const styles = {
    pageContainer: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'center',
        minHeight: '100%',
        backgroundColor: 'var(--background-primary, #36393f)',
        color: 'var(--text-primary, #dcddde)',
        fontFamily: 'Poppins, sans-serif',
        padding: '30px 20px',
        boxSizing: 'border-box',
    },
    quizContainer: {
        width: '100%',
        maxWidth: '600px',
        backgroundColor: 'var(--background-secondary, #2f3136)',
        borderRadius: '8px',
        padding: '25px 25px 35px 25px',
        boxShadow: '0 5px 15px rgba(0,0,0,0.5)',
        textAlign: 'center',
        position: 'relative',
        boxSizing: 'border-box',
        marginTop: '10px'
    },
    pageTitle: {
        marginTop: '10px',
        marginBottom: '15px',
        color: 'var(--text-primary, #dcddde)',
    },
    backButton: {
        padding: '10px 15px',
        backgroundColor: 'var(--button-secondary, #4f545c)',
        color: 'white',
        textDecoration: 'none',
        borderRadius: '5px',
        fontWeight: 'bold',
        fontSize: '1em',
        marginBottom: '20px',
    },
    levelAndProgressContainer: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '15px',
        flexWrap: 'wrap',
        gap: '10px'
    },
    controls: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
    },
    progressStats: {
        display: 'flex',
        gap: '15px',
        fontSize: '0.9em',
        color: 'var(--text-secondary, #72767d)',
        justifyContent: 'flex-start',
    },
    totalStatsHeader: {
        fontSize: '0.9em',
        color: 'var(--text-secondary, #72767d)',
        fontWeight: 'bold',
        textTransform: 'uppercase',
        textAlign: 'left',
        margin: '0 0 8px 0',
    },
    label: {
        fontSize: '1.1em',
        color: 'var(--text-primary, #dcddde)',
    },
    select: {
        padding: '8px',
        fontSize: '1em',
        backgroundColor: 'var(--background-tertiary, #202225)',
        color: 'var(--text-primary, #dcddde)',
        border: '1px solid var(--border-primary, #202225)',
        borderRadius: '4px',
    },
    progressBarBackground: {
        width: '100%',
        backgroundColor: 'var(--background-tertiary, #202225)',
        borderRadius: '5px',
        height: '24px',
        overflow: 'hidden',
        position: 'relative',
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: 'var(--text-positive, #43b581)',
        borderRadius: '5px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'white',
        fontWeight: 'bold',
        fontSize: '0.9em',
        transition: 'width 0.3s ease',
    },
    totalProgressBarFill: {
        backgroundColor: 'var(--button-primary, #5865f2)',
    },
    progressTextOutside: {
        position: 'absolute',
        left: '10px',
        top: '50%',
        transform: 'translateY(-50%)',
        color: 'var(--text-primary, #dcddde)',
        fontSize: '0.9em',
        fontWeight: 'bold'
    },
    wordArea: {
        marginTop: '20px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'var(--background-tertiary, #202225)',
        borderRadius: '5px',
        padding: '30px 20px',
        wordBreak: 'break-word',
    },
    term: {
        fontSize: 'clamp(1.8em, 5vw, 2.5em)',
        fontWeight: 'bold',
        color: 'var(--text-primary, #dcddde)',
        margin: 0,
    },
    meanings: {
        fontSize: 'clamp(1.1em, 3vw, 1.5em)',
        color: 'var(--text-positive, #43b581)',
        margin: '10px 0 0 0',
    },
    buttonGroup: {
        marginTop: '30px',
        display: 'flex',
        gap: '10px',
        flexWrap: 'wrap',
    },
    actionButton: {
        flex: 1,
        minWidth: '150px',
        padding: '12px',
        fontSize: '1.1em',
        fontWeight: 'bold',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
        backgroundColor: 'var(--button-secondary, #4f545c)',
        color: 'white',
        transition: 'opacity 0.2s',
    },
    knownButton: {
        backgroundColor: 'var(--text-positive, #43b581)',
    },
    primaryButton: {
        backgroundColor: 'var(--button-primary, #5865f2)',
    },
    errorText: {
        color: 'var(--text-danger, #f04747)',
    }
};
