const styles = {
  container: { width: '100%', height: '100%', backgroundColor: '#313338', overflowY: 'auto', padding: '40px 60px' },
  header: { textAlign: 'center', marginBottom: '40px' },
  title: { color: '#fff', fontSize: '32px', fontWeight: '700', margin: '0 0 8px 0' },
  subtitle: { color: '#b5bac1', fontSize: '16px', margin: 0 },
  searchContainer: { maxWidth: '800px', margin: '0 auto 32px' },
  searchBar: { position: 'relative', display: 'flex', alignItems: 'center' },
  searchIcon: { position: 'absolute', left: '16px', color: '#b5bac1', fontSize: '18px' },
  searchInput: { width: '100%', padding: '14px 14px 14px 48px', backgroundColor: '#1e1f22', border: 'none', borderRadius: '8px', color: '#fff', fontSize: '16px' },
  categories: { display: 'flex', gap: '12px', marginBottom: '40px', flexWrap: 'wrap', justifyContent: 'center' },
  categoryButton: { backgroundColor: '#2b2d31', border: 'none', color: '#b5bac1', padding: '10px 20px', borderRadius: '20px', cursor: 'pointer', fontSize: '14px', fontWeight: '500', display: 'flex', alignItems: 'center', gap: '8px', transition: 'all 0.2s' },
  categoryButtonActive: { backgroundColor: '#5865f2', border: 'none', color: '#fff', padding: '10px 20px', borderRadius: '20px', cursor: 'pointer', fontSize: '14px', fontWeight: '500', display: 'flex', alignItems: 'center', gap: '8px' },
  categoryIcon: { fontSize: '18px' },
  section: { marginBottom: '48px' },
  sectionTitle: { color: '#fff', fontSize: '20px', fontWeight: '600', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '12px' },
  serverGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: '20px' },
  serverCard: { backgroundColor: '#2b2d31', borderRadius: '8px', padding: '20px', border: '1px solid #1e1f22', transition: 'all 0.2s', cursor: 'pointer' },
  serverCardFeatured: { backgroundColor: '#2b2d31', borderRadius: '8px', padding: '20px', border: '2px solid #faa61a', transition: 'all 0.2s', cursor: 'pointer', position: 'relative', overflow: 'hidden' },
  serverIcon: { marginBottom: '16px' },
  serverIconImage: { width: '64px', height: '64px', borderRadius: '50%', objectFit: 'cover' },
  serverIconPlaceholder: { width: '64px', height: '64px', borderRadius: '50%', backgroundColor: '#5865f2', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '28px', fontWeight: '700' },
  serverInfo: { marginBottom: '16px' },
  serverHeader: { display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' },
  serverName: { color: '#fff', fontSize: '18px', fontWeight: '600', margin: 0, display: 'flex', alignItems: 'center', gap: '8px' },
  verifiedBadge: { color: '#5865f2', fontSize: '16px' },
  serverDescription: { color: '#b5bac1', fontSize: '14px', margin: '0 0 12px 0', lineHeight: '1.5' },
  tags: { display: 'flex', gap: '6px', marginBottom: '12px', flexWrap: 'wrap' },
  tag: { backgroundColor: '#383a40', color: '#b5bac1', padding: '4px 10px', borderRadius: '12px', fontSize: '11px', fontWeight: '500' },
  serverStats: { display: 'flex', gap: '16px', alignItems: 'center', color: '#b5bac1', fontSize: '13px' },
  stat: { display: 'flex', alignItems: 'center', gap: '6px' },
  onlineDot: { width: '8px', height: '8px', borderRadius: '50%', backgroundColor: '#3ba55d' },
  joinButton: { width: '100%', backgroundColor: '#5865f2', color: '#fff', border: 'none', padding: '12px', borderRadius: '4px', cursor: 'pointer', fontSize: '14px', fontWeight: '600', marginTop: '16px' },
  loading: { textAlign: 'center', padding: '40px', color: '#b5bac1' },
  empty: { textAlign: 'center', padding: '60px 20px', color: '#b5bac1', gridColumn: '1 / -1', display: 'flex', flexDirection: 'column', alignItems: 'center' }
};

export default styles;
