export const getStyles = (isMobile) => ({
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        background: 'rgba(0, 0, 0, 0.95)',
        backdropFilter: 'blur(10px)',
        zIndex: 2000,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        padding: isMobile ? '0' : '20px',
    },
    modal: {
        width: '100%',
        maxWidth: isMobile ? '100%' : '1200px',
        height: isMobile ? '100%' : 'auto',
        maxHeight: '90vh',
        background: 'linear-gradient(135deg, rgba(30, 31, 34, 0.98), rgba(35, 36, 40, 0.98))',
        borderRadius: isMobile ? '0' : '16px',
        overflow: 'hidden',
        boxShadow: '0 20px 60px rgba(0, 0, 0, 0.8), 0 0 40px rgba(88, 101, 242, 0.3)',
        border: isMobile ? 'none' : '1px solid rgba(88, 101, 242, 0.4)',
        display: 'flex',
        flexDirection: 'column',
    },
    header: {
        padding: isMobile ? '12px' : '16px 20px',
        background: 'linear-gradient(135deg, rgba(88, 101, 242, 0.15), rgba(114, 137, 218, 0.15))',
        borderBottom: '1px solid rgba(88, 101, 242, 0.3)',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    title: {
        fontSize: isMobile ? '18px' : '22px',
        fontWeight: '700',
        color: 'rgba(255, 255, 255, 0.95)',
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
    },
    closeBtn: {
        background: 'rgba(218, 55, 60, 0.2)',
        border: '1px solid rgba(218, 55, 60, 0.4)',
        borderRadius: '8px',
        width: '36px',
        height: '36px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        color: '#da373c',
        fontSize: '18px',
        transition: 'all 0.2s ease',
    },
    content: {
        display: 'flex',
        flexDirection: isMobile ? 'column' : 'row',
        flex: 1,
        overflow: 'hidden',
    },
    playerSection: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        position: 'relative',
    },
    playerWrapper: {
        position: 'relative',
        paddingTop: '56.25%',
        background: '#000',
        overflow: 'hidden',
    },
    reactionsOverlay: {
        position: 'absolute',
        bottom: '80px',
        left: 0,
        right: 0,
        pointerEvents: 'none',
        zIndex: 10,
    },
    reaction: (x) => ({
        position: 'absolute',
        left: `${x}%`,
        bottom: 0,
        fontSize: '40px',
        animation: 'floatUp 3s ease-out forwards',
        textShadow: '0 0 10px rgba(0, 0, 0, 0.8)',
    }),
    controls: {
        padding: isMobile ? '12px' : '16px 20px',
        background: 'rgba(0, 0, 0, 0.4)',
        borderTop: '1px solid rgba(88, 101, 242, 0.2)',
    },
    controlsTop: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        marginBottom: '12px',
    },
    controlBtn: {
        background: 'rgba(88, 101, 242, 0.2)',
        border: '1px solid rgba(88, 101, 242, 0.4)',
        borderRadius: '8px',
        width: isMobile ? '40px' : '44px',
        height: isMobile ? '40px' : '44px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        color: 'rgba(255, 255, 255, 0.9)',
        transition: 'all 0.2s ease',
        fontSize: isMobile ? '16px' : '18px',
    },
    progressBar: {
        width: '100%',
        height: '6px',
        background: 'rgba(255, 255, 255, 0.2)',
        borderRadius: '3px',
        cursor: 'pointer',
        marginBottom: '12px',
        position: 'relative',
    },
    progressFill: (percent) => ({
        height: '100%',
        width: `${percent}%`,
        background: 'linear-gradient(90deg, #5865f2, #7289da)',
        borderRadius: '3px',
        transition: 'width 0.1s linear',
    }),
    timeDisplay: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: isMobile ? '12px' : '13px',
        marginLeft: '8px',
    },
    reactionBar: {
        display: 'flex',
        gap: '8px',
        marginTop: '12px',
        flexWrap: 'wrap',
    },
    reactionBtn: {
        background: 'rgba(88, 101, 242, 0.1)',
        border: '1px solid rgba(88, 101, 242, 0.3)',
        borderRadius: '8px',
        padding: '8px 12px',
        cursor: 'pointer',
        fontSize: '20px',
        transition: 'all 0.2s ease',
        minWidth: '44px',
        minHeight: '44px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    sidebar: {
        width: isMobile ? '100%' : '320px',
        background: 'rgba(0, 0, 0, 0.3)',
        borderLeft: isMobile ? 'none' : '1px solid rgba(88, 101, 242, 0.2)',
        display: 'flex',
        flexDirection: 'column',
        maxHeight: isMobile ? '40vh' : 'auto',
    },
    sidebarHeader: {
        padding: '16px',
        borderBottom: '1px solid rgba(88, 101, 242, 0.2)',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    playlistContainer: {
        flex: 1,
        overflowY: 'auto',
        padding: '12px',
    },
    playlistItem: (isActive) => ({
        padding: '12px',
        background: isActive ? 'rgba(88, 101, 242, 0.3)' : 'rgba(0, 0, 0, 0.2)',
        borderRadius: '8px',
        marginBottom: '8px',
        cursor: 'pointer',
        border: `1px solid ${isActive ? 'rgba(88, 101, 242, 0.6)' : 'rgba(88, 101, 242, 0.2)'}`,
        transition: 'all 0.2s ease',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        minHeight: '44px',
    }),
    addForm: {
        padding: '12px',
        borderTop: '1px solid rgba(88, 101, 242, 0.2)',
        display: 'flex',
        gap: '8px',
    },
    input: {
        flex: 1,
        padding: '12px',
        background: 'rgba(0, 0, 0, 0.3)',
        border: '1px solid rgba(88, 101, 242, 0.3)',
        borderRadius: '8px',
        color: 'rgba(255, 255, 255, 0.95)',
        fontSize: '14px',
        outline: 'none',
    },
    addBtn: {
        padding: '0 20px',
        background: 'linear-gradient(135deg, #5865f2, #7289da)',
        border: 'none',
        borderRadius: '8px',
        color: 'white',
        fontWeight: '600',
        cursor: 'pointer',
        fontSize: '14px',
        minWidth: '44px',
        minHeight: '44px',
    },
});
