import {
    FaUser,
    FaShieldAlt,
    FaPalette,
    FaMicrophone,
    FaBell,
    FaKeyboard,
    FaGlobe,
    FaDesktop,
    FaCog,
    FaGamepad,
    FaLink,
} from 'react-icons/fa';

const TABS = [
    {
        id: 'account',
        labelKey: 'settings.tabLabels.account',
        label: 'My Account',
        icon: FaUser,
        section: 'USER SETTINGS',
        sectionKey: 'settings.sections.user',
    },
    {
        id: 'privacy',
        labelKey: 'settings.tabLabels.privacy',
        label: 'Privacy & Security',
        icon: FaShieldAlt,
        section: 'USER SETTINGS',
        sectionKey: 'settings.sections.user',
    },
    {
        id: 'connections',
        labelKey: 'settings.tabLabels.connections',
        label: 'Connections',
        icon: FaLink,
        section: 'USER SETTINGS',
        sectionKey: 'settings.sections.user',
    },
    {
        id: 'appearance',
        labelKey: 'settings.tabLabels.appearance',
        label: 'Appearance',
        icon: FaPalette,
        section: 'APPLICATION SETTINGS',
        sectionKey: 'settings.sections.app',
    },
    {
        id: 'voice',
        labelKey: 'settings.tabLabels.voice',
        label: 'Voice & Video',
        icon: FaMicrophone,
        section: 'APPLICATION SETTINGS',
        sectionKey: 'settings.sections.app',
    },
    {
        id: 'notifications',
        labelKey: 'settings.tabLabels.notifications',
        label: 'Notifications',
        icon: FaBell,
        section: 'APPLICATION SETTINGS',
        sectionKey: 'settings.sections.app',
    },
    {
        id: 'keybinds',
        labelKey: 'settings.tabLabels.keybinds',
        label: 'Keyboard Shortcuts',
        icon: FaKeyboard,
        section: 'APPLICATION SETTINGS',
        sectionKey: 'settings.sections.app',
    },
    {
        id: 'language',
        labelKey: 'settings.tabLabels.language',
        label: 'Language',
        icon: FaGlobe,
        section: 'APPLICATION SETTINGS',
        sectionKey: 'settings.sections.app',
    },
    {
        id: 'activity',
        labelKey: 'settings.tabLabels.activity',
        label: 'Activity Status',
        icon: FaGamepad,
        section: 'APPLICATION SETTINGS',
        sectionKey: 'settings.sections.app',
    },
    {
        id: 'devices',
        labelKey: 'settings.tabLabels.sessions',
        label: 'Sessions',
        icon: FaDesktop,
        section: 'APPLICATION SETTINGS',
        sectionKey: 'settings.sections.app',
    },
    {
        id: 'advanced',
        labelKey: 'settings.tabLabels.advanced',
        label: 'Advanced',
        icon: FaCog,
        section: 'APPLICATION SETTINGS',
        sectionKey: 'settings.sections.app',
    },
];

export default TABS;
