export const styles = {
  overlay: {
    position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    zIndex: 999999,
  },
  modal: {
    backgroundColor: '#1e1e1e', borderRadius: '8px',
    width: '90%', maxWidth: '800px', maxHeight: '90vh',
    display: 'flex', flexDirection: 'column',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
  },
  header: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    padding: '20px', borderBottom: '1px solid #2c2f33',
  },
  headerLeft: { display: 'flex', alignItems: 'center' },
  title: { margin: 0, fontSize: '20px', color: '#ffffff' },
  closeButton: {
    background: 'none', border: 'none', color: '#99aab5',
    cursor: 'pointer', fontSize: '20px', padding: '5px',
  },
  tabs: { display: 'flex', borderBottom: '1px solid #2c2f33', padding: '0 20px' },
  tab: {
    padding: '12px 20px', backgroundColor: 'transparent', border: 'none',
    color: '#99aab5', cursor: 'pointer', fontSize: '14px',
    display: 'flex', alignItems: 'center',
    borderBottom: '2px solid transparent', transition: 'all 0.2s',
  },
  tabActive: { color: '#5865f2', borderBottom: '2px solid #5865f2' },
  content: { padding: '20px', overflowY: 'auto', flex: 1 },
  loading: { textAlign: 'center', color: '#99aab5', padding: '40px' },
  overview: { display: 'flex', flexDirection: 'column', gap: '20px' },
  boostCard: {
    backgroundColor: '#2c2f33', borderRadius: '8px', padding: '24px',
    display: 'flex', flexDirection: 'column', gap: '20px',
  },
  boostLevel: { textAlign: 'center', padding: '24px', borderRadius: '8px', color: '#ffffff' },
  levelText: { fontSize: '24px', fontWeight: '600', marginTop: '8px' },
  boostCountText: { fontSize: '14px', opacity: 0.9, marginTop: '4px' },
  progressSection: { display: 'flex', flexDirection: 'column', gap: '8px' },
  progressHeader: { display: 'flex', justifyContent: 'space-between', fontSize: '14px', color: '#dcddde' },
  progressBar: { height: '8px', backgroundColor: '#1e1e1e', borderRadius: '4px', overflow: 'hidden' },
  progressFill: { height: '100%', transition: 'width 0.3s' },
  progressFooter: { fontSize: '12px', color: '#99aab5', textAlign: 'center' },
  boostButton: {
    padding: '12px', backgroundColor: '#5865f2', border: 'none', borderRadius: '4px',
    color: '#ffffff', cursor: 'pointer', fontSize: '16px', fontWeight: '600',
    display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'background-color 0.2s',
  },
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '15px' },
  statCard: { backgroundColor: '#2c2f33', borderRadius: '8px', padding: '20px', textAlign: 'center' },
  statIcon: { fontSize: '24px', color: '#5865f2', marginBottom: '8px' },
  statValue: { fontSize: '24px', fontWeight: '600', color: '#ffffff', marginBottom: '4px' },
  statLabel: { fontSize: '12px', color: '#99aab5' },
  boostsList: { display: 'flex', flexDirection: 'column', gap: '10px' },
  empty: { textAlign: 'center', color: '#99aab5', padding: '40px' },
  boostItem: {
    backgroundColor: '#2c2f33', borderRadius: '6px', padding: '15px',
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
  },
  boostUser: { display: 'flex', alignItems: 'center' },
  boostUsername: { color: '#ffffff', fontWeight: '500' },
  boostDate: { fontSize: '12px', color: '#99aab5', marginTop: '2px' },
  boostExpires: { fontSize: '12px', color: '#faa61a' },
  perksList: { display: 'flex', flexDirection: 'column', gap: '24px' },
  perkLevel: { display: 'flex', flexDirection: 'column', gap: '12px' },
  perkLevelHeader: { fontSize: '18px', fontWeight: '600', color: '#ffffff', display: 'flex', alignItems: 'center' },
  perkRequirement: { fontSize: '12px', color: '#99aab5', marginLeft: '8px', fontWeight: '400' },
  perksGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '12px' },
  perkCard: { backgroundColor: '#2c2f33', borderRadius: '6px', padding: '16px', display: 'flex', flexDirection: 'column', gap: '8px' },
  perkIcon: { fontSize: '32px' },
  perkName: { fontSize: '14px', fontWeight: '600', color: '#ffffff' },
  perkDescription: { fontSize: '12px', color: '#99aab5' },
  perkUnlocked: { fontSize: '12px', color: '#43b581', fontWeight: '600', marginTop: '4px' },
};
