// PaymentPanel/styles.js
const styles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        backdropFilter: 'blur(6px)',
        WebkitBackdropFilter: 'blur(6px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 999999,
        animation: 'ppOverlayIn 0.2s ease-out',
    },
    modal: {
        background: 'linear-gradient(180deg, #1e1f23 0%, #111214 100%)',
        borderRadius: '16px',
        width: '90%',
        maxWidth: '800px',
        maxHeight: '82vh',
        display: 'flex',
        flexDirection: 'column',
        color: '#fff',
        position: 'relative',
        overflow: 'hidden',
        boxShadow: '0 24px 80px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.07)',
        animation: 'ppModalIn 0.3s cubic-bezier(0.22,1,0.36,1)',
    },
    header: {
        padding: '20px 24px',
        background: 'linear-gradient(135deg, rgba(88,101,242,0.12) 0%, rgba(88,101,242,0.04) 100%)',
        borderBottom: '1px solid rgba(255,255,255,0.06)',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerLeft: { display: 'flex', alignItems: 'center', gap: '12px' },
    closeBtn: {
        background: 'rgba(255,255,255,0.06)',
        border: 'none',
        color: '#b5bac1',
        fontSize: '18px',
        cursor: 'pointer',
        padding: '6px',
        borderRadius: '50%',
        width: 32,
        height: 32,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'background 0.2s',
    },
    tabs: { display: 'flex', borderBottom: '1px solid rgba(255,255,255,0.06)', padding: '0 20px' },
    tab: {
        background: 'none',
        border: 'none',
        color: '#949ba4',
        padding: '12px 20px',
        cursor: 'pointer',
        fontSize: '14px',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        borderBottom: '2px solid transparent',
        transition: 'all 0.2s',
    },
    activeTab: { color: '#5865f2', borderBottomColor: '#5865f2' },
    content: { padding: '20px', overflowY: 'auto', flex: 1 },
    loading: { textAlign: 'center', padding: '40px', color: '#949ba4' },
    balanceView: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '30px',
    },
    balanceCard: {
        background: 'linear-gradient(135deg, rgba(240,178,50,0.08) 0%, rgba(240,178,50,0.03) 100%)',
        border: '1px solid rgba(240,178,50,0.18)',
        borderRadius: '16px',
        padding: '40px',
        textAlign: 'center',
        width: '100%',
        maxWidth: '400px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '16px',
        boxShadow: '0 8px 32px rgba(0,0,0,0.25)',
    },
    balanceAmount: { fontSize: '48px', fontWeight: 'bold', color: '#f0b232' },
    balanceLabel: { fontSize: '14px', color: '#949ba4' },
    quickActions: { display: 'flex', gap: '12px', width: '100%', maxWidth: '400px' },
    actionBtn: {
        flex: 1,
        padding: '12px 20px',
        background: 'linear-gradient(135deg, #5865f2, #4752c4)',
        border: 'none',
        borderRadius: '10px',
        color: '#fff',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '600',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        transition: 'opacity 0.2s',
        boxShadow: '0 4px 12px rgba(88,101,242,0.3)',
    },
    buyView: { display: 'flex', flexDirection: 'column', gap: '20px' },
    sectionTitle: { fontSize: '16px', fontWeight: '600', margin: 0, marginBottom: '12px' },
    packages: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
        gap: '12px',
    },
    package: {
        background: 'rgba(255,255,255,0.04)',
        border: '1px solid rgba(255,255,255,0.07)',
        borderRadius: '12px',
        padding: '20px',
        textAlign: 'center',
        cursor: 'pointer',
        transition: 'all 0.2s',
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '8px',
    },
    selectedPackage: {
        borderColor: '#5865f2',
        background: 'rgba(88,101,242,0.12)',
        boxShadow: '0 0 0 1px #5865f2',
    },
    pkgAmount: { fontSize: '24px', fontWeight: 'bold', color: '#f0b232' },
    bonus: {
        fontSize: '10px',
        color: '#23a559',
        fontWeight: 'bold',
        padding: '2px 8px',
        backgroundColor: 'rgba(67, 181, 129, 0.12)',
        borderRadius: '4px',
    },
    pkgPrice: { fontSize: '18px', fontWeight: '600', color: '#fff' },
    purchaseSection: { marginTop: '24px' },
    paymentMethods: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '16px',
        marginBottom: '32px',
    },
    paymentMethodCard: {
        padding: '20px',
        background: 'rgba(255,255,255,0.04)',
        border: '1px solid rgba(255,255,255,0.08)',
        borderRadius: '12px',
        textAlign: 'center',
        cursor: 'pointer',
        transition: 'all 0.25s ease',
    },
    selectedPaymentMethod: {
        background: 'rgba(88,101,242,0.18)',
        borderColor: '#5865f2',
        transform: 'scale(1.03)',
        boxShadow: '0 4px 20px rgba(88,101,242,0.35)',
    },
    pmIcon: { fontSize: '48px', marginBottom: '12px' },
    pmTitle: { fontSize: '16px', fontWeight: '600', color: 'white', marginBottom: '6px' },
    pmDesc: { fontSize: '13px', color: '#b5bac1', marginBottom: '8px' },
    pmBadge: {
        display: 'inline-block',
        padding: '4px 12px',
        background: 'rgba(35,165,89,0.12)',
        borderRadius: '12px',
        fontSize: '11px',
        color: '#23a559',
        fontWeight: '600',
    },
    paymentInfo: {
        background: 'rgba(255,255,255,0.04)',
        border: '1px solid rgba(255,255,255,0.07)',
        borderRadius: '12px',
        padding: '16px',
        marginBottom: '16px',
    },
    paymentInfoRow: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: '8px 0',
        fontSize: '14px',
        color: '#b5bac1',
        borderBottom: '1px solid rgba(255,255,255,0.05)',
    },
    paymentNote: { textAlign: 'center', fontSize: '12px', color: '#23a559', marginTop: '12px' },
    price: { fontSize: '18px', fontWeight: '600', color: '#fff' },
    paymentMethod: { marginTop: '12px' },
    label: {
        display: 'block',
        fontSize: '14px',
        fontWeight: '600',
        marginBottom: '8px',
        color: '#dbdee1',
    },
    select: {
        width: '100%',
        padding: '10px',
        backgroundColor: 'rgba(255,255,255,0.06)',
        border: '1px solid rgba(255,255,255,0.12)',
        borderRadius: '8px',
        color: '#fff',
        fontSize: '14px',
    },
    purchaseBtn: {
        width: '100%',
        padding: '14px',
        background: 'linear-gradient(135deg, #23a559, #1a8047)',
        border: 'none',
        borderRadius: '10px',
        color: '#fff',
        fontSize: '16px',
        fontWeight: '600',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        marginTop: '12px',
        boxShadow: '0 4px 12px rgba(35,165,89,0.3)',
    },
    transferView: { maxWidth: '500px', margin: '0 auto' },
    form: { display: 'flex', flexDirection: 'column', gap: '16px' },
    formGroup: { display: 'flex', flexDirection: 'column', gap: '8px' },
    input: {
        padding: '10px',
        backgroundColor: 'rgba(255,255,255,0.06)',
        border: '1px solid rgba(255,255,255,0.12)',
        borderRadius: '8px',
        color: '#fff',
        fontSize: '14px',
    },
    hint: { fontSize: '12px', color: '#949ba4' },
    transferBtn: {
        width: '100%',
        padding: '14px',
        background: 'linear-gradient(135deg, #5865f2, #4752c4)',
        border: 'none',
        borderRadius: '10px',
        color: '#fff',
        fontSize: '16px',
        fontWeight: '600',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        marginTop: '12px',
        boxShadow: '0 4px 12px rgba(88,101,242,0.3)',
    },
    historyView: { display: 'flex', flexDirection: 'column', gap: '16px' },
    transactions: { display: 'flex', flexDirection: 'column', gap: '8px' },
    transaction: {
        background: 'rgba(255,255,255,0.04)',
        border: '1px solid rgba(255,255,255,0.07)',
        borderRadius: '12px',
        padding: '16px',
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    txIcon: { fontSize: '24px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
    txDetails: { flex: 1 },
    txTitle: { fontSize: '14px', fontWeight: '600' },
    txDate: { fontSize: '12px', color: '#949ba4', marginTop: '4px' },
    txAmount: { fontSize: '18px', fontWeight: 'bold' },
    empty: { textAlign: 'center', padding: '40px', color: '#949ba4' },
};

export default styles;
