// UserProfilePanel/styles.js - Extracted style definitions
const styles = {
    overlay: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 9999,
      backdropFilter: 'blur(8px)',
    },
    panel: {
      width: '900px',
      maxHeight: '90vh',
      background: 'linear-gradient(135deg, #1e1e2e 0%, #2a2a3e 100%)',
      borderRadius: '16px',
      boxShadow: '0 25px 50px rgba(0, 0, 0, 0.5)',
      display: 'flex',
      flexDirection: 'column',
      overflow: 'hidden',
      border: '1px solid rgba(255, 255, 255, 0.1)',
    },
    header: {
      padding: '24px 32px',
      background: 'linear-gradient(90deg, #5865f2 0%, #7289da 100%)',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    },
    title: {
      fontSize: '24px',
      fontWeight: '700',
      color: '#fff',
      margin: 0,
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
    },
    closeBtn: {
      background: 'rgba(255, 255, 255, 0.15)',
      border: 'none',
      color: '#fff',
      width: '36px',
      height: '36px',
      borderRadius: '50%',
      cursor: 'pointer',
      fontSize: '20px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      transition: 'all 0.2s',
    },
    tabBar: {
      display: 'flex',
      gap: '8px',
      padding: '20px 32px',
      minHeight: '70px',
      background: 'rgba(0, 0, 0, 0.2)',
      borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
      overflowX: 'auto',
      alignItems: 'center',
    },
    body: {
      display: 'flex',
      height: 'calc(90vh - 88px)', // Header yüksekliği çıkarılmış
      overflow: 'hidden',
    },
    sidebar: {
      width: '240px',
      background: 'rgba(0, 0, 0, 0.3)',
      borderRight: '1px solid rgba(255, 255, 255, 0.1)',
      overflowY: 'auto',
      padding: '12px 8px',
    },
    sidebarSection: {
      marginBottom: '24px',
    },
    sidebarHeader: {
      padding: '8px 16px',
      fontSize: '12px',
      fontWeight: '700',
      color: '#b9bbbe',
      textTransform: 'uppercase',
      letterSpacing: '0.5px',
      marginBottom: '4px',
    },
    sidebarBtn: (active) => ({
      width: '100%',
      padding: '10px 16px',
      background: active ? 'rgba(88, 101, 242, 0.15)' : 'transparent',
      border: 'none',
      borderLeft: active ? '3px solid #5865f2' : '3px solid transparent',
      borderRadius: '6px',
      color: active ? '#fff' : '#b9bbbe',
      cursor: 'pointer',
      fontWeight: active ? '600' : '400',
      fontSize: '14px',
      textAlign: 'left',
      transition: 'all 0.2s',
      marginBottom: '2px',
      display: 'flex',
      alignItems: 'center',
    }),
    tab: (active) => ({
      padding: '10px 20px',
      background: active ? 'linear-gradient(135deg, #5865f2 0%, #7289da 100%)' : 'rgba(255, 255, 255, 0.05)',
      border: 'none',
      borderRadius: '10px',
      color: '#fff',
      cursor: 'pointer',
      fontWeight: active ? '600' : '400',
      fontSize: '14px',
      transition: 'all 0.3s',
      whiteSpace: 'nowrap',
      boxShadow: active ? '0 4px 15px rgba(88, 101, 242, 0.4)' : 'none',
    }),
    content: {
      flex: 1,
      overflowY: 'auto',
      padding: '32px',
    },
    card: {
      background: 'rgba(255, 255, 255, 0.03)',
      borderRadius: '12px',
      padding: '24px',
      marginBottom: '20px',
      border: '1px solid rgba(255, 255, 255, 0.05)',
      transition: 'all 0.3s',
    },
    sectionTitle: {
      fontSize: '18px',
      fontWeight: '600',
      color: '#fff',
      marginBottom: '16px',
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
    },
    inputGroup: {
      marginBottom: '20px',
    },
    label: {
      display: 'block',
      color: '#b9bbbe',
      fontSize: '13px',
      fontWeight: '600',
      marginBottom: '8px',
      textTransform: 'uppercase',
      letterSpacing: '0.5px',
    },
    input: {
      width: '100%',
      padding: '12px 16px',
      background: 'rgba(0, 0, 0, 0.3)',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      borderRadius: '8px',
      color: '#fff',
      fontSize: '14px',
      outline: 'none',
      transition: 'all 0.2s',
      boxSizing: 'border-box',
    },
    button: (variant = 'primary') => ({
      padding: '12px 24px',
      background: variant === 'primary'
        ? 'linear-gradient(135deg, #5865f2 0%, #7289da 100%)'
        : variant === 'danger'
          ? 'linear-gradient(135deg, #ed4245 0%, #c9302c 100%)'
          : 'rgba(255, 255, 255, 0.1)',
      border: 'none',
      borderRadius: '8px',
      color: '#fff',
      fontWeight: '600',
      fontSize: '14px',
      cursor: 'pointer',
      transition: 'all 0.3s',
      boxShadow: variant === 'primary' ? '0 4px 15px rgba(88, 101, 242, 0.3)' : 'none',
    }),
    avatarSection: {
      display: 'flex',
      alignItems: 'center',
      gap: '24px',
      marginBottom: '24px',
    },
    avatar: {
      width: '100px',
      height: '100px',
      borderRadius: '50%',
      objectFit: 'cover',
      border: '4px solid rgba(88, 101, 242, 0.5)',
      boxShadow: '0 8px 20px rgba(0, 0, 0, 0.3)',
    },
    badge: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '6px',
      padding: '6px 12px',
      background: 'linear-gradient(135deg, #ffd700 0%, #ffed4e 100%)',
      borderRadius: '20px',
      fontSize: '12px',
      fontWeight: '600',
      color: '#1e1e2e',
      margin: '4px',
    },
    progressBar: {
      width: '100%',
      height: '10px',
      background: 'rgba(0, 0, 0, 0.3)',
      borderRadius: '10px',
      overflow: 'hidden',
      marginTop: '8px',
    },
    progressFill: (percent) => ({
      width: `${percent}%`,
      height: '100%',
      background: 'linear-gradient(90deg, #5865f2 0%, #7289da 50%, #43b581 100%)',
      borderRadius: '10px',
      transition: 'width 0.5s ease',
    }),
    qrCode: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '16px',
      padding: '24px',
      background: '#fff',
      borderRadius: '12px',
      marginTop: '16px',
    },
    backupCodesGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '12px',
      marginTop: '16px',
    },
    backupCode: {
      padding: '12px',
      background: 'rgba(0, 0, 0, 0.4)',
      borderRadius: '8px',
      fontFamily: 'monospace',
      fontSize: '14px',
      textAlign: 'center',
      color: '#43b581',
      border: '1px solid rgba(67, 181, 129, 0.3)',
    },
    themeGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: '16px',
      marginTop: '16px',
    },
    themeCard: (active) => ({
      padding: '16px',
      background: active ? 'linear-gradient(135deg, #5865f2 0%, #7289da 100%)' : 'rgba(255, 255, 255, 0.05)',
      borderRadius: '12px',
      cursor: 'pointer',
      textAlign: 'center',
      transition: 'all 0.3s',
      border: active ? '2px solid #fff' : '2px solid transparent',
    }),
    sessionCard: {
      padding: '16px',
      background: 'rgba(255, 255, 255, 0.05)',
      borderRadius: '8px',
      marginBottom: '12px',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    settingRow: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '16px',
      background: 'rgba(255, 255, 255, 0.03)',
      borderRadius: '8px',
      marginBottom: '12px',
    },
  };

export default styles;
