export const styles = {
  overlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.85)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 999999 },
  modal: { backgroundColor: '#1e1e1e', borderRadius: '8px', width: '90%', maxWidth: '900px', maxHeight: '90vh', display: 'flex', flexDirection: 'column', boxShadow: '0 8px 32px rgba(0,0,0,0.4)' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '20px', borderBottom: '1px solid #2c2f33' },
  headerLeft: { display: 'flex', alignItems: 'center' },
  title: { margin: 0, fontSize: '20px', color: '#ffffff' },
  closeButton: { background: 'none', border: 'none', color: '#99aab5', cursor: 'pointer', fontSize: '20px', padding: '5px' },
  filters: { display: 'flex', gap: '10px', padding: '15px 20px', borderBottom: '1px solid #2c2f33', flexWrap: 'wrap' },
  filterButton: { padding: '8px 16px', backgroundColor: '#2c2f33', border: 'none', borderRadius: '4px', color: '#ffffff', cursor: 'pointer', fontSize: '14px', transition: 'background-color 0.2s' },
  filterButtonActive: { backgroundColor: '#5865f2' },
  exportButton: { marginLeft: 'auto', padding: '8px 16px', backgroundColor: '#43b581', border: 'none', borderRadius: '4px', color: '#ffffff', cursor: 'pointer', fontSize: '14px', display: 'flex', alignItems: 'center' },
  content: { padding: '20px', overflowY: 'auto', flex: 1 },
  loading: { textAlign: 'center', color: '#99aab5', padding: '40px' },
  empty: { textAlign: 'center', color: '#99aab5', padding: '40px' },
  resultsList: { display: 'flex', flexDirection: 'column', gap: '15px' },
  resultCard: { backgroundColor: '#2c2f33', borderRadius: '6px', padding: '15px' },
  resultHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' },
  resultStatus: { display: 'flex', alignItems: 'center', fontSize: '14px' },
  timestamp: { fontSize: '12px', color: '#99aab5' },
  resultBody: { display: 'flex', flexDirection: 'column', gap: '15px' },
  resultInfo: { display: 'flex', flexDirection: 'column', gap: '8px' },
  infoRow: { display: 'flex', alignItems: 'center', gap: '10px', fontSize: '14px', color: '#dcddde' },
  progressBar: { flex: 1, height: '8px', backgroundColor: '#1e1e1e', borderRadius: '4px', overflow: 'hidden' },
  progressFill: { height: '100%', transition: 'width 0.3s' },
  flags: { display: 'flex', flexWrap: 'wrap', gap: '5px' },
  flag: { padding: '4px 8px', backgroundColor: '#f04747', borderRadius: '4px', fontSize: '12px', color: '#ffffff' },
  actions: { display: 'flex', gap: '10px', justifyContent: 'flex-end' },
  actionButton: { padding: '8px 16px', border: 'none', borderRadius: '4px', color: '#ffffff', cursor: 'pointer', fontSize: '14px', display: 'flex', alignItems: 'center' },
  approveButton: { backgroundColor: '#43b581' },
  blockButton: { backgroundColor: '#f04747' },
  ignoreButton: { backgroundColor: '#99aab5' },
};
