export const styles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 999999,
    },
    modal: {
        backgroundColor: '#1e1e1e',
        borderRadius: '8px',
        width: '90%',
        maxWidth: '900px',
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '20px',
        borderBottom: '1px solid #2c2f33',
    },
    headerLeft: {
        display: 'flex',
        alignItems: 'center',
    },
    title: {
        margin: 0,
        fontSize: '20px',
        color: '#ffffff',
    },
    closeButton: {
        background: 'none',
        border: 'none',
        color: '#99aab5',
        cursor: 'pointer',
        fontSize: '20px',
        padding: '5px',
    },
    content: {
        padding: '20px',
        overflowY: 'auto',
        flex: 1,
    },
    loading: {
        textAlign: 'center',
        color: '#99aab5',
        padding: '40px',
    },
    section: {
        marginBottom: '24px',
    },
    sectionHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '16px',
    },
    sectionTitle: {
        margin: 0,
        fontSize: '16px',
        color: '#ffffff',
        fontWeight: '600',
    },
    addButton: {
        padding: '8px 16px',
        backgroundColor: '#5865f2',
        border: 'none',
        borderRadius: '4px',
        color: '#ffffff',
        cursor: 'pointer',
        fontSize: '14px',
        display: 'flex',
        alignItems: 'center',
    },
    createForm: {
        backgroundColor: '#2c2f33',
        borderRadius: '6px',
        padding: '20px',
        marginBottom: '16px',
    },
    formGroup: {
        marginBottom: '16px',
    },
    label: {
        display: 'block',
        color: '#dcddde',
        fontSize: '14px',
        marginBottom: '8px',
        fontWeight: '500',
    },
    input: {
        width: '100%',
        padding: '10px',
        backgroundColor: '#1e1e1e',
        border: '1px solid #2c2f33',
        borderRadius: '4px',
        color: '#ffffff',
        fontSize: '14px',
    },
    eventsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: '8px',
    },
    eventCheckbox: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        color: '#dcddde',
        fontSize: '14px',
        cursor: 'pointer',
    },
    eventLabel: {
        userSelect: 'none',
    },
    formActions: {
        display: 'flex',
        gap: '10px',
        justifyContent: 'flex-end',
    },
    createButton: {
        padding: '10px 20px',
        backgroundColor: '#43b581',
        border: 'none',
        borderRadius: '4px',
        color: '#ffffff',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '500',
    },
    cancelButton: {
        padding: '10px 20px',
        backgroundColor: '#4f545c',
        border: 'none',
        borderRadius: '4px',
        color: '#ffffff',
        cursor: 'pointer',
        fontSize: '14px',
    },
    webhooksList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    empty: {
        textAlign: 'center',
        color: '#99aab5',
        padding: '40px',
    },
    webhookCard: {
        backgroundColor: '#2c2f33',
        borderRadius: '6px',
        padding: '16px',
    },
    webhookHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    webhookName: {
        fontSize: '16px',
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: '4px',
    },
    webhookUrl: {
        fontSize: '13px',
        color: '#5865f2',
        marginBottom: '4px',
        wordBreak: 'break-all',
    },
    webhookEvents: {
        fontSize: '12px',
        color: '#99aab5',
    },
    webhookActions: {
        display: 'flex',
        gap: '8px',
    },
    iconButton: {
        background: 'none',
        border: 'none',
        color: '#99aab5',
        cursor: 'pointer',
        fontSize: '16px',
        padding: '5px',
    },
    deliveriesList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        maxHeight: '300px',
        overflowY: 'auto',
    },
    deliveryCard: {
        backgroundColor: '#2c2f33',
        borderRadius: '6px',
        padding: '12px',
    },
    deliveryHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '8px',
    },
    deliveryStatus: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    deliveryStatusText: {
        fontSize: '14px',
        fontWeight: '600',
        color: '#ffffff',
    },
    deliveryTime: {
        fontSize: '12px',
        color: '#99aab5',
    },
    deliveryBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        fontSize: '13px',
        color: '#dcddde',
    },
    deliveryInfo: {
        display: 'flex',
        gap: '8px',
    },
    deliveryError: {
        color: '#f04747',
        marginTop: '4px',
    },
    retryButton: {
        marginTop: '12px',
        padding: '6px 12px',
        backgroundColor: '#5865f2',
        border: 'none',
        borderRadius: '4px',
        color: '#ffffff',
        cursor: 'pointer',
        fontSize: '12px',
        display: 'flex',
        alignItems: 'center',
    },
};
