// frontend/src/components/UserWarningsPanel/styles.js
const styles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10000,
        backdropFilter: 'blur(5px)',
    },
    panel: {
        backgroundColor: 'var(--bg-charcoal-deep)',
        borderRadius: '12px',
        width: '90%',
        maxWidth: '1000px',
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.5)',
        overflow: 'hidden',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '20px',
        borderBottom: '1px solid var(--bg-primary)',
    },
    headerLeft: { display: 'flex', alignItems: 'center', gap: '12px' },
    headerIcon: { fontSize: '24px', color: '#f0b132' },
    title: { margin: 0, color: 'var(--color-white)', fontSize: '24px', fontWeight: '600' },
    headerRight: { display: 'flex', gap: '12px' },
    addBtn: {
        backgroundColor: 'var(--color-success)',
        color: 'var(--color-white)',
        border: 'none',
        borderRadius: '6px',
        padding: '8px 16px',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '600',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    closeButton: {
        background: 'none',
        border: 'none',
        color: 'var(--text-secondary)',
        cursor: 'pointer',
        fontSize: '24px',
        padding: '8px',
    },
    statsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
        gap: '16px',
        padding: '20px',
        borderBottom: '1px solid var(--bg-primary)',
    },
    statCard: {
        backgroundColor: 'var(--bg-void)',
        borderRadius: '8px',
        padding: '16px',
        textAlign: 'center',
    },
    statIcon: { fontSize: '32px', marginBottom: '8px' },
    statValue: { fontSize: '28px', fontWeight: 'bold', color: 'var(--color-white)', marginBottom: '4px' },
    statLabel: { fontSize: '13px', color: 'var(--text-secondary)' },
    searchBar: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '16px 20px',
        borderBottom: '1px solid var(--bg-primary)',
        backgroundColor: 'var(--bg-void)',
    },
    searchIcon: { color: 'var(--text-secondary)', fontSize: '16px' },
    searchInput: {
        flex: 1,
        backgroundColor: 'var(--bg-charcoal-deep)',
        border: '1px solid var(--bg-primary)',
        borderRadius: '6px',
        padding: '8px 12px',
        color: 'var(--color-white)',
        fontSize: '14px',
    },
    warningsList: { flex: 1, overflowY: 'auto', padding: '20px' },
    loading: { textAlign: 'center', color: 'var(--text-secondary)', padding: '40px', fontSize: '14px' },
    empty: { textAlign: 'center', color: 'var(--text-secondary)', padding: '60px' },
    emptyIcon: { fontSize: '48px', marginBottom: '16px', opacity: 0.5 },
    userCard: {
        backgroundColor: 'var(--bg-void)',
        borderRadius: '8px',
        padding: '16px',
        marginBottom: '16px',
    },
    userHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '12px',
        paddingBottom: '12px',
        borderBottom: '1px solid var(--bg-secondary)',
    },
    userInfo: { display: 'flex', alignItems: 'center', gap: '12px' },
    userIcon: { fontSize: '20px', color: 'var(--color-primary)' },
    userName: { color: 'var(--color-white)', fontSize: '18px', fontWeight: '600' },
    badge: {
        padding: '4px 8px',
        borderRadius: '4px',
        fontSize: '11px',
        fontWeight: '600',
        color: '#fff',
        textTransform: 'uppercase',
    },
    riskBadge: {
        padding: '4px 8px',
        borderRadius: '4px',
        fontSize: '11px',
        fontWeight: '700',
        color: 'var(--color-white)',
        backgroundColor: 'var(--color-danger)',
        animation: 'pulse 1.5s infinite',
    },
    banBtn: {
        backgroundColor: 'var(--color-danger)',
        color: 'var(--color-white)',
        border: 'none',
        borderRadius: '6px',
        padding: '8px 16px',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '600',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    userWarnings: { display: 'flex', flexDirection: 'column', gap: '8px' },
    warningItem: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '12px',
        backgroundColor: 'var(--bg-charcoal-deep)',
        borderRadius: '6px',
    },
    warningLeft: { display: 'flex', alignItems: 'center', gap: '12px', flex: 1 },
    severityDot: { width: '12px', height: '12px', borderRadius: '50%', flexShrink: 0 },
    warningContent: { flex: 1 },
    warningReason: { color: 'var(--color-white)', fontSize: '14px', marginBottom: '4px' },
    warningMeta: {
        color: 'var(--text-muted)',
        fontSize: '12px',
        display: 'flex',
        gap: '8px',
        flexWrap: 'wrap',
    },
    removeBtn: {
        background: 'none',
        border: 'none',
        color: 'var(--color-danger)',
        cursor: 'pointer',
        fontSize: '14px',
        padding: '8px',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10001,
    },
    modal: {
        backgroundColor: 'var(--bg-charcoal-deep)',
        borderRadius: '12px',
        width: '90%',
        maxWidth: '500px',
        maxHeight: '80vh',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    modalHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '20px',
        borderBottom: '1px solid var(--bg-primary)',
    },
    modalTitle: { margin: 0, color: 'var(--color-white)', fontSize: '20px', fontWeight: '600' },
    modalClose: {
        background: 'none',
        border: 'none',
        color: 'var(--text-secondary)',
        cursor: 'pointer',
        fontSize: '20px',
    },
    modalContent: { flex: 1, overflowY: 'auto', padding: '20px' },
    formGroup: { marginBottom: '20px' },
    label: {
        display: 'block',
        color: 'var(--text-secondary)',
        fontSize: '14px',
        fontWeight: '600',
        marginBottom: '8px',
    },
    select: {
        width: '100%',
        backgroundColor: 'var(--bg-void)',
        border: '1px solid var(--bg-secondary)',
        borderRadius: '6px',
        padding: '10px',
        color: 'var(--color-white)',
        fontSize: '14px',
    },
    input: {
        width: '100%',
        backgroundColor: 'var(--bg-void)',
        border: '1px solid var(--bg-secondary)',
        borderRadius: '6px',
        padding: '10px',
        color: 'var(--color-white)',
        fontSize: '14px',
    },
    textarea: {
        width: '100%',
        backgroundColor: 'var(--bg-void)',
        border: '1px solid var(--bg-secondary)',
        borderRadius: '6px',
        padding: '10px',
        color: 'var(--color-white)',
        fontSize: '14px',
        resize: 'vertical',
        fontFamily: 'inherit',
    },
    hint: { color: 'var(--text-muted)', fontSize: '12px', marginTop: '4px' },
    modalActions: {
        display: 'flex',
        gap: '12px',
        padding: '16px 20px',
        borderTop: '1px solid var(--bg-primary)',
    },
    cancelBtn: {
        flex: 1,
        backgroundColor: 'var(--bg-charcoal-deep)',
        color: 'var(--color-white)',
        border: 'none',
        borderRadius: '6px',
        padding: '10px 16px',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '600',
    },
    submitBtn: {
        flex: 1,
        backgroundColor: 'var(--color-success)',
        color: 'var(--color-white)',
        border: 'none',
        borderRadius: '6px',
        padding: '10px 16px',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '600',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
    },
};

export default styles;
