const styles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10000,
    },
    modal: {
        width: '95%',
        maxWidth: '1200px',
        maxHeight: '90vh',
        backgroundColor: '#2f3136',
        borderRadius: '12px',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.5)',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '20px 24px',
        borderBottom: '1px solid #202225',
    },
    headerLeft: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    headerRight: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    title: {
        color: '#fff',
        fontSize: '20px',
        fontWeight: '600',
        margin: 0,
    },
    periodSelect: {
        padding: '8px 12px',
        backgroundColor: '#36393f',
        border: '1px solid #40444b',
        borderRadius: '4px',
        color: '#dcddde',
        fontSize: '14px',
        cursor: 'pointer',
    },
    closeBtn: {
        background: 'none',
        border: 'none',
        color: '#72767d',
        fontSize: '20px',
        cursor: 'pointer',
        padding: '4px',
    },
    content: {
        flex: 1,
        overflowY: 'auto',
        padding: '24px',
    },
    loadingState: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '60px',
        color: '#72767d',
        gap: '16px',
    },
    spinner: {
        width: '40px',
        height: '40px',
        border: '3px solid #36393f',
        borderTopColor: '#5865f2',
        borderRadius: '50%',
        animation: 'spin 1s linear infinite',
    },
    errorState: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '60px',
        color: '#dcddde',
        textAlign: 'center',
    },
    statsRow: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '16px',
        marginBottom: '24px',
    },
    statCard: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
        padding: '20px',
        backgroundColor: '#36393f',
        borderRadius: '8px',
    },
    statIcon: {
        width: '48px',
        height: '48px',
        borderRadius: '12px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#fff',
        fontSize: '20px',
    },
    statInfo: {
        display: 'flex',
        flexDirection: 'column',
    },
    statLabel: {
        color: '#72767d',
        fontSize: '12px',
        marginBottom: '4px',
    },
    statValue: {
        color: '#fff',
        fontSize: '24px',
        fontWeight: '700',
    },
    statSubtext: {
        color: '#72767d',
        fontSize: '11px',
    },
    statChange: {
        fontSize: '12px',
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        marginTop: '4px',
    },
    chartsRow: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))',
        gap: '16px',
        marginBottom: '24px',
    },
    chartCard: {
        backgroundColor: '#36393f',
        borderRadius: '8px',
        padding: '20px',
    },
    chartTitle: {
        color: '#fff',
        fontSize: '14px',
        fontWeight: '600',
        marginBottom: '16px',
    },
    barChart: {
        display: 'flex',
        alignItems: 'flex-end',
        gap: '4px',
        height: '120px',
    },
    barContainer: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        height: '100%',
    },
    bar: {
        width: '100%',
        backgroundColor: '#5865f2',
        borderRadius: '4px 4px 0 0',
        transition: 'height 0.3s',
        minHeight: '4px',
    },
    barLabel: {
        color: '#72767d',
        fontSize: '10px',
        marginTop: '4px',
    },
    hourlyChart: {
        display: 'grid',
        gridTemplateColumns: 'repeat(12, 1fr)',
        gap: '4px',
    },
    hourBlock: {
        aspectRatio: '1',
        borderRadius: '4px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#fff',
        fontSize: '10px',
        cursor: 'default',
    },
    listsRow: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
        gap: '16px',
        marginBottom: '24px',
    },
    listCard: {
        backgroundColor: '#36393f',
        borderRadius: '8px',
        padding: '20px',
    },
    listTitle: {
        color: '#fff',
        fontSize: '14px',
        fontWeight: '600',
        marginBottom: '16px',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    list: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    listItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '8px 12px',
        backgroundColor: '#2f3136',
        borderRadius: '4px',
    },
    listRank: {
        color: '#5865f2',
        fontWeight: '600',
        width: '24px',
    },
    listName: {
        color: '#dcddde',
        flex: 1,
    },
    listValue: {
        color: '#72767d',
        fontSize: '12px',
    },
    emptyList: {
        color: '#72767d',
        textAlign: 'center',
        padding: '20px',
    },
    pieChart: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    contentBarContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    contentBarLabel: {
        display: 'flex',
        justifyContent: 'space-between',
        color: '#dcddde',
        fontSize: '12px',
    },
    contentBarTrack: {
        height: '8px',
        backgroundColor: '#202225',
        borderRadius: '4px',
        overflow: 'hidden',
    },
    contentBarFill: {
        height: '100%',
        borderRadius: '4px',
        transition: 'width 0.3s',
    },
    comparisonSection: {
        backgroundColor: '#36393f',
        borderRadius: '8px',
        padding: '20px',
    },
    sectionTitle: {
        color: '#fff',
        fontSize: '14px',
        fontWeight: '600',
        marginBottom: '16px',
    },
    comparisonGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '16px',
    },
    comparisonCard: {
        backgroundColor: '#2f3136',
        borderRadius: '8px',
        padding: '16px',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    comparisonLabel: {
        color: '#fff',
        fontWeight: '600',
    },
    comparisonValues: {
        display: 'flex',
        gap: '24px',
    },
    comparisonValue: {
        display: 'flex',
        flexDirection: 'column',
    },
    comparisonPeriod: {
        color: '#72767d',
        fontSize: '11px',
    },
    comparisonNumber: {
        color: '#dcddde',
        fontSize: '18px',
        fontWeight: '600',
    },
    comparisonChange: {
        fontSize: '14px',
    },
};

export default styles;
