const styles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10000,
        padding: '20px',
    },
    panel: {
        backgroundColor: '#111214',
        borderRadius: '8px',
        width: '100%',
        maxWidth: '1200px',
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column',
    },
    header: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '20px',
        borderBottom: '1px solid #0b0e1b',
    },
    headerLeft: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    headerActions: {
        display: 'flex',
        gap: '12px',
    },
    title: {
        margin: 0,
        fontSize: '20px',
        color: '#ffffff',
    },
    createButton: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        backgroundColor: '#5865f2',
        color: '#ffffff',
        border: 'none',
        padding: '8px 16px',
        borderRadius: '4px',
        cursor: 'pointer',
        fontSize: '14px',
    },
    closeButton: {
        background: 'none',
        border: 'none',
        color: '#b5bac1',
        cursor: 'pointer',
        padding: '8px',
    },
    filters: {
        display: 'flex',
        gap: '8px',
        padding: '16px 20px',
        borderBottom: '1px solid #0b0e1b',
    },
    filterButton: {
        padding: '8px 16px',
        borderRadius: '4px',
        border: 'none',
        color: '#ffffff',
        cursor: 'pointer',
        fontSize: '13px',
    },
    content: {
        flex: 1,
        overflowY: 'auto',
        padding: '20px',
    },
    empty: {
        textAlign: 'center',
        padding: '60px 20px',
        color: '#b5bac1',
    },
    tournamentGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
        gap: '16px',
    },
    tournamentCard: {
        backgroundColor: '#17191c',
        borderRadius: '8px',
        padding: '16px',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    cardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'start',
    },
    tournamentName: {
        color: '#ffffff',
        fontSize: '16px',
        fontWeight: 'bold',
        flex: 1,
    },
    statusBadge: {
        padding: '4px 8px',
        borderRadius: '12px',
        fontSize: '11px',
        color: '#ffffff',
        textTransform: 'uppercase',
        fontWeight: 'bold',
    },
    cardBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    cardInfo: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        color: '#b5bac1',
        fontSize: '13px',
    },
    cardFooter: {
        display: 'flex',
        gap: '8px',
        marginTop: 'auto',
    },
    viewButton: {
        flex: 1,
        backgroundColor: '#0d0e10',
        color: '#ffffff',
        border: 'none',
        padding: '8px',
        borderRadius: '4px',
        cursor: 'pointer',
        fontSize: '13px',
    },
    joinButton: {
        flex: 1,
        backgroundColor: '#3ba55d',
        color: '#ffffff',
        border: 'none',
        padding: '8px',
        borderRadius: '4px',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: 'bold',
    },
    leaveButton: {
        flex: 1,
        backgroundColor: '#f23f42',
        color: '#ffffff',
        border: 'none',
        padding: '8px',
        borderRadius: '4px',
        cursor: 'pointer',
        fontSize: '13px',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10001,
    },
    modal: {
        backgroundColor: '#17191c',
        borderRadius: '8px',
        padding: '24px',
        width: '90%',
        maxWidth: '500px',
        maxHeight: '80vh',
        overflowY: 'auto',
    },
    modalTitle: {
        color: '#ffffff',
        marginBottom: '16px',
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    input: {
        width: '100%',
        backgroundColor: '#0d0e10',
        border: 'none',
        color: '#dbdee1',
        padding: '10px',
        borderRadius: '4px',
        fontSize: '14px',
        outline: 'none',
    },
    modalButtons: {
        display: 'flex',
        gap: '8px',
        justifyContent: 'flex-end',
        marginTop: '16px',
    },
    cancelButton: {
        backgroundColor: 'transparent',
        color: '#ffffff',
        border: 'none',
        padding: '8px 16px',
        borderRadius: '4px',
        cursor: 'pointer',
    },
    submitButton: {
        backgroundColor: '#5865f2',
        color: '#ffffff',
        border: 'none',
        padding: '8px 16px',
        borderRadius: '4px',
        cursor: 'pointer',
        fontWeight: '500',
    },
    modalHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '16px',
    },
    modalClose: {
        background: 'none',
        border: 'none',
        color: '#b5bac1',
        cursor: 'pointer',
        padding: '4px',
    },
    modalContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    detailSection: {
        backgroundColor: '#111214',
        padding: '16px',
        borderRadius: '8px',
    },
    bracketInfo: {
        textAlign: 'center',
        padding: '20px',
        color: '#b5bac1',
    },
    participantList: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
        gap: '8px',
    },
    participant: {
        backgroundColor: '#17191c',
        padding: '8px 12px',
        borderRadius: '4px',
        color: '#dbdee1',
        fontSize: '13px',
        display: 'flex',
        justifyContent: 'space-between',
    },
    seed: {
        color: '#f0b232',
        fontWeight: 'bold',
    },
};

export default styles;
