const styles = {
  overlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.85)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 999999 },
  modal: { backgroundColor: '#1e1e1e', borderRadius: '8px', width: '90%', maxWidth: '800px', maxHeight: '90vh', display: 'flex', flexDirection: 'column', boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '20px', borderBottom: '1px solid #2c2f33' },
  headerLeft: { display: 'flex', alignItems: 'center' },
  title: { margin: 0, fontSize: '20px', color: '#ffffff' },
  closeButton: { background: 'none', border: 'none', color: '#99aab5', cursor: 'pointer', fontSize: '20px', padding: '5px' },
  toolbar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 20px', borderBottom: '1px solid #2c2f33' },
  count: { fontSize: '14px', color: '#dcddde' },
  createButton: { padding: '8px 16px', backgroundColor: '#5865f2', border: 'none', borderRadius: '4px', color: '#ffffff', cursor: 'pointer', fontSize: '13px', display: 'flex', alignItems: 'center' },
  createForm: { padding: '20px', backgroundColor: '#2c2f33', borderBottom: '1px solid #2c2f33' },
  formRow: { marginBottom: '16px' },
  label: { display: 'block', fontSize: '14px', fontWeight: '600', color: '#dcddde', marginBottom: '6px' },
  input: { width: '100%', padding: '10px', backgroundColor: '#1e1e1e', border: '1px solid #2c2f33', borderRadius: '4px', color: '#ffffff', fontSize: '14px' },
  textarea: { width: '100%', padding: '10px', backgroundColor: '#1e1e1e', border: '1px solid #2c2f33', borderRadius: '4px', color: '#ffffff', fontSize: '14px', fontFamily: 'inherit', resize: 'vertical' },
  select: { width: '100%', padding: '10px', backgroundColor: '#1e1e1e', border: '1px solid #2c2f33', borderRadius: '4px', color: '#ffffff', fontSize: '14px' },
  checkbox: { display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px', cursor: 'pointer' },
  checkboxLabel: { fontSize: '14px', color: '#dcddde' },
  submitButton: { width: '100%', padding: '12px', backgroundColor: '#43b581', border: 'none', borderRadius: '4px', color: '#ffffff', cursor: 'pointer', fontSize: '14px', fontWeight: '600' },
  content: { padding: '20px', overflowY: 'auto', flex: 1 },
  loading: { textAlign: 'center', color: '#99aab5', padding: '40px' },
  empty: { textAlign: 'center', color: '#99aab5', padding: '40px' },
  respondersList: { display: 'flex', flexDirection: 'column', gap: '12px' },
  responderCard: { backgroundColor: '#2c2f33', borderRadius: '8px', padding: '16px', display: 'flex', justifyContent: 'space-between' },
  responderInfo: { flex: 1 },
  trigger: { fontSize: '14px', color: '#99aab5', marginBottom: '8px' },
  triggerValue: { color: '#5865f2', fontWeight: '600', fontFamily: 'monospace' },
  response: { fontSize: '14px', color: '#ffffff', marginBottom: '8px' },
  meta: { fontSize: '12px', color: '#99aab5' },
  actions: { display: 'flex', gap: '12px', alignItems: 'center' },
  toggleButton: { background: 'none', border: 'none', cursor: 'pointer', padding: '4px' },
  deleteButton: { background: 'none', border: 'none', color: '#f04747', cursor: 'pointer', fontSize: '16px', padding: '8px' },
};

export default styles;
