const styles = {
    overlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.85)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 999999,
    },
    modal: {
        backgroundColor: '#1e1e1e',
        borderRadius: '8px',
        width: '90%',
        maxWidth: '700px',
        maxHeight: '85vh',
        display: 'flex',
        flexDirection: 'column',
        color: '#fff',
    },
    header: {
        padding: '20px',
        borderBottom: '1px solid #444',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerLeft: { display: 'flex', alignItems: 'center', gap: '12px' },
    closeBtn: {
        background: 'none',
        border: 'none',
        color: '#fff',
        fontSize: '24px',
        cursor: 'pointer',
        padding: '8px',
    },
    content: { padding: '20px', overflowY: 'auto', flex: 1 },
    loading: { textAlign: 'center', padding: '40px', color: '#949ba4' },
    streakCard: {
        backgroundColor: '#111214',
        borderRadius: '12px',
        padding: '24px',
        display: 'flex',
        alignItems: 'center',
        gap: '20px',
        marginBottom: '24px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
    },
    streakInfo: { display: 'flex', flexDirection: 'column', gap: '4px' },
    streakNumber: { fontSize: '48px', fontWeight: 'bold', color: '#f23f42', lineHeight: 1 },
    streakLabel: {
        fontSize: '14px',
        color: '#949ba4',
        textTransform: 'uppercase',
        letterSpacing: '1px',
    },
    claimSection: { marginBottom: '32px' },
    sectionTitle: { fontSize: '16px', fontWeight: '600', marginBottom: '16px', color: '#dbdee1' },
    currentRewardCard: {
        background: 'linear-gradient(135deg, #5865f2 0%, #5865f2 100%)',
        borderRadius: '12px',
        padding: '24px',
        display: 'flex',
        alignItems: 'center',
        gap: '20px',
        marginBottom: '16px',
        boxShadow: '0 8px 16px rgba(88,101,242,0.3)',
    },
    rewardIcon: {
        fontSize: '48px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    rewardDetails: { flex: 1 },
    rewardAmount: { fontSize: '28px', fontWeight: 'bold', marginBottom: '4px' },
    rewardDescription: { fontSize: '14px', opacity: 0.9 },
    claimBtn: {
        width: '100%',
        padding: '16px',
        backgroundColor: '#23a559',
        border: 'none',
        borderRadius: '8px',
        color: '#fff',
        fontSize: '18px',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.2s',
        boxShadow: '0 4px 12px rgba(67,181,129,0.3)',
    },
    alreadyClaimed: { textAlign: 'center', padding: '40px 20px', marginBottom: '32px' },
    nextRewardTime: {
        marginTop: '16px',
        padding: '12px',
        backgroundColor: '#111214',
        borderRadius: '8px',
        fontSize: '16px',
        fontWeight: '600',
    },
    calendarSection: { marginBottom: '24px' },
    calendar: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(90px, 1fr))',
        gap: '12px',
    },
    calendarDay: {
        backgroundColor: '#111214',
        borderRadius: '8px',
        padding: '16px',
        textAlign: 'center',
        border: '2px solid transparent',
        transition: 'all 0.2s',
        position: 'relative',
    },
    calendarDayActive: {
        borderColor: '#23a559',
        backgroundColor: '#2c3136',
        boxShadow: '0 0 20px rgba(67,181,129,0.3)',
    },
    calendarDayClaimed: { opacity: 0.5 },
    dayNumber: { fontSize: '12px', color: '#949ba4', marginBottom: '8px', fontWeight: '600' },
    dayIcon: { fontSize: '32px', marginBottom: '8px', display: 'flex', justifyContent: 'center' },
    dayReward: { fontSize: '16px', fontWeight: 'bold' },
    claimedBadge: {
        position: 'absolute',
        top: '8px',
        right: '8px',
        color: '#23a559',
        fontSize: '16px',
    },
    info: { backgroundColor: '#111214', borderRadius: '8px', padding: '16px' },
    infoText: { fontSize: '14px', color: '#dbdee1', margin: '8px 0', lineHeight: '1.6' },
};

export default styles;
