export const styles = {
    overlay: {
        position: 'fixed',
        top: 0, left: 0, right: 0, bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 999999,
    },
    modal: {
        backgroundColor: '#1e1e1e',
        borderRadius: '8px',
        width: '90%',
        maxWidth: '900px',
        maxHeight: '90vh',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '20px',
        borderBottom: '1px solid #2c2f33',
    },
    headerLeft: {
        display: 'flex',
        alignItems: 'center',
    },
    title: {
        margin: 0,
        fontSize: '20px',
        color: '#ffffff',
    },
    closeButton: {
        background: 'none',
        border: 'none',
        color: '#99aab5',
        cursor: 'pointer',
        fontSize: '20px',
        padding: '5px',
    },
    tabs: {
        display: 'flex',
        borderBottom: '1px solid #2c2f33',
        padding: '0 20px',
    },
    tab: {
        padding: '12px 20px',
        backgroundColor: 'transparent',
        border: 'none',
        color: '#99aab5',
        cursor: 'pointer',
        fontSize: '14px',
        display: 'flex',
        alignItems: 'center',
        borderBottom: '2px solid transparent',
    },
    tabActive: {
        color: '#5865f2',
        borderBottom: '2px solid #5865f2',
    },
    content: {
        padding: '20px',
        overflowY: 'auto',
        flex: 1,
    },
    loading: {
        textAlign: 'center',
        color: '#99aab5',
        padding: '40px',
    },
    toolbar: {
        marginBottom: '20px',
    },
    createButton: {
        padding: '10px 20px',
        backgroundColor: '#5865f2',
        border: 'none',
        borderRadius: '4px',
        color: '#ffffff',
        cursor: 'pointer',
        fontSize: '14px',
        display: 'flex',
        alignItems: 'center',
        fontWeight: '500',
    },
    createForm: {
        backgroundColor: '#2c2f33',
        borderRadius: '8px',
        padding: '20px',
        marginBottom: '20px',
    },
    formTitle: {
        margin: '0 0 16px 0',
        fontSize: '16px',
        color: '#ffffff',
    },
    formGroup: {
        marginBottom: '16px',
    },
    label: {
        display: 'block',
        color: '#dcddde',
        fontSize: '14px',
        marginBottom: '8px',
        fontWeight: '500',
    },
    input: {
        width: '100%',
        padding: '10px',
        backgroundColor: '#1e1e1e',
        border: '1px solid #2c2f33',
        borderRadius: '4px',
        color: '#ffffff',
        fontSize: '14px',
    },
    scopesGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: '8px',
    },
    scopeCheckbox: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        color: '#dcddde',
        fontSize: '14px',
        cursor: 'pointer',
    },
    formActions: {
        display: 'flex',
        gap: '10px',
        justifyContent: 'flex-end',
        marginTop: '20px',
    },
    submitButton: {
        padding: '10px 20px',
        backgroundColor: '#43b581',
        border: 'none',
        borderRadius: '4px',
        color: '#ffffff',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: '500',
    },
    cancelButton: {
        padding: '10px 20px',
        backgroundColor: '#4f545c',
        border: 'none',
        borderRadius: '4px',
        color: '#ffffff',
        cursor: 'pointer',
        fontSize: '14px',
    },
    empty: {
        textAlign: 'center',
        color: '#99aab5',
        padding: '40px',
    },
    appsList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    appCard: {
        backgroundColor: '#2c2f33',
        borderRadius: '8px',
        padding: '16px',
    },
    appHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        marginBottom: '12px',
    },
    appName: {
        fontSize: '18px',
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: '4px',
    },
    appDescription: {
        fontSize: '14px',
        color: '#99aab5',
    },
    deleteButton: {
        background: 'none',
        border: 'none',
        color: '#f04747',
        cursor: 'pointer',
        fontSize: '16px',
        padding: '5px',
    },
    appDetails: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    credential: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        fontSize: '14px',
        color: '#dcddde',
    },
    code: {
        flex: 1,
        padding: '8px',
        backgroundColor: '#1e1e1e',
        borderRadius: '4px',
        fontFamily: 'monospace',
        fontSize: '13px',
        color: '#5865f2',
    },
    copyButton: {
        background: 'none',
        border: 'none',
        color: '#99aab5',
        cursor: 'pointer',
        fontSize: '14px',
        padding: '5px',
    },
    detail: {
        fontSize: '14px',
        color: '#dcddde',
    },
    uri: {
        fontSize: '13px',
        color: '#5865f2',
        marginLeft: '8px',
        fontFamily: 'monospace',
    },
    botsList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    botCard: {
        backgroundColor: '#2c2f33',
        borderRadius: '8px',
        padding: '16px',
    },
    botHeader: {
        display: 'flex',
        alignItems: 'center',
    },
    botName: {
        fontSize: '18px',
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: '4px',
    },
    botDescription: {
        fontSize: '14px',
        color: '#99aab5',
        marginBottom: '4px',
    },
    botStatus: {
        fontSize: '13px',
        color: '#dcddde',
    },
};
